Name: haldorHERO
Species: 7
Parts:
- Name: SK_ELVN_WARR_01_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_ELVN_WARR_01_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_ELVN_WARR_01_29ASHL_HU01
  PartType: AttachmentShoulderLeft
  PartVersion: 1
- Name: SK_ELVN_WARR_01_30ASHR_HU01
  PartType: AttachmentShoulderRight
  PartVersion: 1
- Name: SK_ELVN_WARR_02_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_ELVN_WARR_05_25AHPF_HU01
  PartType: AttachmentHipsFront
  PartVersion: 1
- Name: SK_FANT_KNGT_01_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_01_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_FANT_KNGT_01_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_01_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_FANT_KNGT_01_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_01_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_FANT_KNGT_01_31AEBL_HU01
  PartType: AttachmentElbowLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_01_32AEBR_HU01
  PartType: AttachmentElbowRight
  PartVersion: 1
- Name: SK_FANT_KNGT_02_02HAIR_HU01
  PartType: Hair
  PartVersion: 1
- Name: SK_FANT_KNGT_02_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_FANT_KNGT_04_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_04_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_26AHPB_HU01
  PartType: AttachmentHipsBack
  PartVersion: 1
- Name: SK_FANT_SKTN_03_27AHPL_SN01
  PartType: AttachmentHipsLeft
  PartVersion: 1
- Name: SK_FANT_SKTN_03_28AHPR_SN01
  PartType: AttachmentHipsRight
  PartVersion: 1
- Name: SK_ELVN_BASE_01_01HEAD_EV01
  PartType: Head
  PartVersion: 1
- Name: SK_GOBL_BASE_01_03EBRL_GO01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_GOBL_BASE_01_04EBRR_GO01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_GOBL_BASE_01_05EYEL_GO01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_GOBL_BASE_01_06EYER_GO01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_37TONG_HU01
  PartType: Tongue
  PartVersion: 1
- Name: SK_ELVN_BASE_01_36TETH_EV01
  PartType: Teeth
  PartVersion: 1
- Name: SK_HUMN_BASE_01_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_PIRT_CAPT_05_09FCHR_HU01
  PartType: FacialHair
  PartVersion: 1
ColorSet:
  Species: 7
  Name: Custom
  SourceColorPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: D5A57B
- ColorProperty: 2
  MainColor: D5A57B
- ColorProperty: 3
  MainColor: D5A57B
- ColorProperty: 4
  MainColor: BB8B67
- ColorProperty: 5
  MainColor: D5A57B
- ColorProperty: 6
  MainColor: D5A57B
- ColorProperty: 7
  MainColor: D5A57B
- ColorProperty: 8
  MainColor: BB8B67
- ColorProperty: 9
  MainColor: BB8B67
- ColorProperty: 10
  MainColor: BB8B67
- ColorProperty: 11
  MainColor: BB8B67
- ColorProperty: 12
  MainColor: BB8B67
- ColorProperty: 13
  MainColor: BB8B67
- ColorProperty: 14
  MainColor: D5A57B
- ColorProperty: 15
  MainColor: E79A9C
- ColorProperty: 16
  MainColor: FFF3CE
- ColorProperty: 17
  MainColor: E5D8AF
- ColorProperty: 18
  MainColor: E79A9C
- ColorProperty: 19
  MainColor: E79A9C
- ColorProperty: 20
  MainColor: D0D0D0
- ColorProperty: 21
  MainColor: D0D0D0
- ColorProperty: 22
  MainColor: 4B351D
- ColorProperty: 23
  MainColor: 4B351D
- ColorProperty: 24
  MainColor: 262626
- ColorProperty: 25
  MainColor: 262626
- ColorProperty: 26
  MainColor: 725130
- ColorProperty: 27
  MainColor: 725130
- ColorProperty: 28
  MainColor: 979797
- ColorProperty: 29
  MainColor: 979797
- ColorProperty: 30
  MainColor: B4B4B4
- ColorProperty: 31
  MainColor: B4B4B4
- ColorProperty: 32
  MainColor: 7E7E7E
- ColorProperty: 33
  MainColor: 352A1F
- ColorProperty: 34
  MainColor: CAA58E
- ColorProperty: 35
  MainColor: 939393
- ColorProperty: 36
  MainColor: 352A1F
- ColorProperty: 37
  MainColor: CAA58E
- ColorProperty: 38
  MainColor: B35149
- ColorProperty: 39
  MainColor: 944842
- ColorProperty: 40
  MainColor: AFA382
- ColorProperty: 41
  MainColor: 94896F
- ColorProperty: 42
  MainColor: 070707
- ColorProperty: 43
  MainColor: 686B72
- ColorProperty: 44
  MainColor: 2F2D4A
- ColorProperty: 45
  MainColor: 514C46
- ColorProperty: 46
  MainColor: 6A5C4D
- ColorProperty: 47
  MainColor: 070707
- ColorProperty: 48
  MainColor: 7A5D45
- ColorProperty: 49
  MainColor: 4F4130
- ColorProperty: 50
  MainColor: 7D6652
- ColorProperty: 51
  MainColor: 6A5C4D
- ColorProperty: 52
  MainColor: 070707
- ColorProperty: 53
  MainColor: 7A5D45
- ColorProperty: 54
  MainColor: 4F4130
- ColorProperty: 55
  MainColor: 7D6652
- ColorProperty: 56
  MainColor: 6A5C4D
- ColorProperty: 57
  MainColor: 948474
- ColorProperty: 58
  MainColor: 6A5C4D
- ColorProperty: 59
  MainColor: 4B3E30
- ColorProperty: 60
  MainColor: 7D6652
- ColorProperty: 61
  MainColor: 6A5C4D
- ColorProperty: 62
  MainColor: 948474
- ColorProperty: 63
  MainColor: 6A5C4D
- ColorProperty: 64
  MainColor: 4B3E30
- ColorProperty: 65
  MainColor: 7D6652
- ColorProperty: 66
  MainColor: 6A5C4D
- ColorProperty: 67
  MainColor: 070707
- ColorProperty: 68
  MainColor: 2F2C26
- ColorProperty: 69
  MainColor: 272727
- ColorProperty: 70
  MainColor: 4B3E30
- ColorProperty: 71
  MainColor: 6A5C4D
- ColorProperty: 72
  MainColor: 393939
- ColorProperty: 73
  MainColor: 332F26
- ColorProperty: 74
  MainColor: 624B3C
- ColorProperty: 75
  MainColor: 4B3E30
- ColorProperty: 76
  MainColor: 6A5C4D
- ColorProperty: 77
  MainColor: 424242
- ColorProperty: 78
  MainColor: 332F26
- ColorProperty: 79
  MainColor: 624B3C
- ColorProperty: 80
  MainColor: 4B3E30
- ColorProperty: 81
  MainColor: 6A5C4D
- ColorProperty: 82
  MainColor: 000000
- ColorProperty: 83
  MainColor: 332F26
- ColorProperty: 84
  MainColor: 514C46
- ColorProperty: 85
  MainColor: 998B79
- ColorProperty: 86
  MainColor: 575655
- ColorProperty: 87
  MainColor: 000000
- ColorProperty: 88
  MainColor: 332F26
- ColorProperty: 89
  MainColor: 514C46
- ColorProperty: 90
  MainColor: 998B79
- ColorProperty: 91
  MainColor: 575655
- ColorProperty: 92
  MainColor: A48937
- ColorProperty: 93
  MainColor: A48937
- ColorProperty: 94
  MainColor: B5B6B5
- ColorProperty: 95
  MainColor: 733935
- ColorProperty: 96
  MainColor: 988A7A
- ColorProperty: 97
  MainColor: 5A6D9A
- ColorProperty: 98
  MainColor: 383838
- ColorProperty: 99
  MainColor: 383838
- ColorProperty: 100
  MainColor: 383838
- ColorProperty: 101
  MainColor: 383838
- ColorProperty: 102
  MainColor: 383838
- ColorProperty: 103
  MainColor: 383838
- ColorProperty: 104
  MainColor: 383838
- ColorProperty: 105
  MainColor: 000000
- ColorProperty: 106
  MainColor: 383838
- ColorProperty: 107
  MainColor: 383838
- ColorProperty: 108
  MainColor: 383838
- ColorProperty: 109
  MainColor: 383838
- ColorProperty: 110
  MainColor: 000000
- ColorProperty: 111
  MainColor: 383838
- ColorProperty: 112
  MainColor: 383838
- ColorProperty: 113
  MainColor: 383838
- ColorProperty: 114
  MainColor: 383838
- ColorProperty: 115
  MainColor: 383838
- ColorProperty: 116
  MainColor: 383838
- ColorProperty: 117
  MainColor: 383838
- ColorProperty: 118
  MainColor: 383838
- ColorProperty: 119
  MainColor: 383838
- ColorProperty: 120
  MainColor: 383838
- ColorProperty: 121
  MainColor: 383838
- ColorProperty: 122
  MainColor: 383838
- ColorProperty: 123
  MainColor: 383838
- ColorProperty: 124
  MainColor: 383838
- ColorProperty: 125
  MainColor: 383838
- ColorProperty: 126
  MainColor: 383838
- ColorProperty: 127
  MainColor: 383838
- ColorProperty: 128
  MainColor: 383838
- ColorProperty: 129
  MainColor: 383838
- ColorProperty: 130
  MainColor: 383838
- ColorProperty: 131
  MainColor: 383838
- ColorProperty: 132
  MainColor: 383838
- ColorProperty: 133
  MainColor: 383838
- ColorProperty: 134
  MainColor: 383838
- ColorProperty: 135
  MainColor: 383838
- ColorProperty: 136
  MainColor: 383838
- ColorProperty: 137
  MainColor: 383838
- ColorProperty: 138
  MainColor: 383838
- ColorProperty: 139
  MainColor: 383838
- ColorProperty: 140
  MainColor: 383838
- ColorProperty: 141
  MainColor: 383838
- ColorProperty: 142
  MainColor: 383838
- ColorProperty: 143
  MainColor: 383838
- ColorProperty: 144
  MainColor: 383838
- ColorProperty: 145
  MainColor: 383838
- ColorProperty: 146
  MainColor: 383838
- ColorProperty: 147
  MainColor: 383838
- ColorProperty: 148
  MainColor: 383838
- ColorProperty: 149
  MainColor: 383838
- ColorProperty: 150
  MainColor: 383838
- ColorProperty: 151
  MainColor: 383838
- ColorProperty: 152
  MainColor: 383838
- ColorProperty: 153
  MainColor: 383838
- ColorProperty: 154
  MainColor: 383838
- ColorProperty: 155
  MainColor: 383838
- ColorProperty: 156
  MainColor: 383838
- ColorProperty: 157
  MainColor: 383838
- ColorProperty: 158
  MainColor: 383838
- ColorProperty: 159
  MainColor: 383838
- ColorProperty: 160
  MainColor: 131416
- ColorProperty: 161
  MainColor: 111212
- ColorProperty: 162
  MainColor: 2D2D2D
- ColorProperty: 163
  MainColor: 393B3F
- ColorProperty: 164
  MainColor: 8934CB
- ColorProperty: 165
  MainColor: 000000
- ColorProperty: 166
  MainColor: C2AC78
- ColorProperty: 167
  MainColor: C69B4D
- ColorProperty: 168
  MainColor: 6CB0CC
- ColorProperty: 169
  MainColor: 619990
- ColorProperty: 170
  MainColor: F9D92A
- ColorProperty: 171
  MainColor: 91F92A
- ColorProperty: 172
  MainColor: 9A9FA2
- ColorProperty: 173
  MainColor: 949AA2
- ColorProperty: 174
  MainColor: 8D997D
- ColorProperty: 175
  MainColor: 838865
- ColorProperty: 176
  MainColor: 33312E
- ColorProperty: 177
  MainColor: 282623
- ColorProperty: 178
  MainColor: 7B7772
- ColorProperty: 179
  MainColor: 54575D
- ColorProperty: 180
  MainColor: 8F8571
- ColorProperty: 181
  MainColor: 796E58
- ColorProperty: 182
  MainColor: 796E58
- ColorProperty: 183
  MainColor: 675848
- ColorProperty: 184
  MainColor: 6B5440
- ColorProperty: 185
  MainColor: 5D4A3A
- ColorProperty: 186
  MainColor: 1E1105
- ColorProperty: 187
  MainColor: 564535
- ColorProperty: 188
  MainColor: 9F8363
- ColorProperty: 189
  MainColor: 675A47
- ColorProperty: 190
  MainColor: 867867
- ColorProperty: 191
  MainColor: 716354
- ColorProperty: 192
  MainColor: BDB7B1
- ColorProperty: 193
  MainColor: AAA5A0
- ColorProperty: 194
  MainColor: 745B46
- ColorProperty: 195
  MainColor: 866D56
- ColorProperty: 196
  MainColor: 6C3198
- ColorProperty: 197
  MainColor: 5B3E6F
- ColorProperty: 198
  MainColor: 7B7879
- ColorProperty: 199
  MainColor: 565656
- ColorProperty: 200
  MainColor: FFFFFF
- ColorProperty: 201
  MainColor: FFFFFF
- ColorProperty: 202
  MainColor: FFFFFF
- ColorProperty: 203
  MainColor: FFFFFF
- ColorProperty: 204
  MainColor: FFFFFF
- ColorProperty: 205
  MainColor: FFFFFF
- ColorProperty: 206
  MainColor: FFFFFF
- ColorProperty: 207
  MainColor: FFFFFF
- ColorProperty: 208
  MainColor: FFFFFF
- ColorProperty: 209
  MainColor: FFFFFF
BlendShapes:
  BodyTypeValue: -100
  BodySizeValue: 18.2000008
  MuscleValue: 100
