#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class AvatarSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";

 static Unit caster,a,b,c,ally,baseHero,second;static CompositeSkill dash,blade;static DamageType pure;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start,speed,hp;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static AvatarSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("AvatarSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-avatar.txt")){File.Delete(W+"run-avatar.txt");Begin();return;}
 if(!SessionState.GetBool("AvatarSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.6f){Check(baseHero.effectors.Any(e=>e.effector.name=="Inquisitor_DomeVisual"),"Faith dome caster effect active");Capture("inquisitor-dome.png");Check(Cast(blade),"Avatar blade button accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.8f){Check(a.health<10000&&b.health<10000,"Blade hits two enemies in180degree arc");Check(c.health==10000,"Blade excludes rear enemy");Check(ally.health==10000,"Blade excludes ally");Check(a.moveSpeed<speed,"Blade slows survivors");Check(!Cast(blade),"Blade cooldown blocks repeat");Capture("avatar-blade.png");phase=3;return;}
 if(phase==3&&Time.time-start>3.8f){Check(Mathf.Abs(a.moveSpeed-speed)<.01f,"Blade slow expires after3sec");Move(a,center+Vector3.forward*3);Move(b,center+Vector3.forward*5);Move(c,center+Vector3.back*10);caster.LookAtInstant(new Vector2(a.transform.position.x,a.transform.position.z));hp=a.health;Check(Cast(dash),"Dash button accepted");phase=4;start=Time.time;return;}
 if(phase==4&&Time.time-start>.5f){Capture("avatar-dash-moving.png");phase=5;return;}
 if(phase==5&&Time.time-start>1.2f){Check(caster.transform.position.z>a.transform.position.z+1,"Dash passes through enemy");Check(UnityEngine.Object.FindObjectsByType<GroundDamageZone>(FindObjectsSortMode.None).Length>0,"Dash leaves fire zones");Check(a.health<hp,"Fire trail damages enemy");Check(ally.health==10000,"Fire trail excludes allies");Check(!Cast(dash),"Dash cooldown blocks repeat");Capture("avatar-firetrail.png");phase=6;return;}
 if(phase==6&&Time.time-start>4.5f){Check(!UnityEngine.Object.FindObjectsByType<GroundDamageZone>(FindObjectsSortMode.None).Any(),"All fire zones end after3sec");Check(!caster.GetComponent<SkillTravel>().Running,"Dash state ends");Reset(dash);Move(a,caster.transform.position+Vector3.forward*2);Check(Cast(dash),"Dash can be reused");a.Die(-1,null,false);phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>1.5f){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death does not freeze cast");second=Spawn(center+Vector3.right*5,0,"Heroes/Humans/Inquisitor_Avatar");Move(b,second.transform.position+Vector3.forward*2);second.LookAtInstant(new Vector2(b.transform.position.x,b.transform.position.z));float before=b.health;blade.Use(second,0,0);Check(b.health<before,"Second Avatar independently damages target with same skill asset");a=Spawn(caster.transform.position+Vector3.forward*2,foeOwner);Reset(dash);Cast(dash);caster.Die(-1,null,false);phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>4.5f){Check(!caster||!caster.GetComponent<SkillTravel>()||!caster.GetComponent<SkillTravel>().Running,"Dead caster cannot keep dashing");Check(!UnityEngine.Object.FindObjectsByType<GroundDamageZone>(FindObjectsSortMode.None).Any(),"Death leaves no indefinite trail zones");caster=second;a.Die(-1,null,false);b.Die(-1,null,false);c.Die(-1,null,false);Reset(dash);Check(!Cast(dash),"No target rejects dash");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Move(Unit u,Vector3 p){if(u)Knockback.MoveTo(u,p,false);}
 static bool Cast(CompositeSkill s){Register();return caster&&caster.UseAbilityItem(Array.IndexOf(caster.abilities,s),false,null,Vector3.zero,true);}
 static void Reset(CompositeSkill s)=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,s),false);
 static void Register(){var mm=MatchManager.instance;var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;((TeamWaveConfig)typeof(MatchManager).GetField("teamA",flags).GetValue(mm)).ownerPlayer=0;((TeamWaveConfig)typeof(MatchManager).GetField("teamB",flags).GetValue(mm)).ownerPlayer=foeOwner;var lists=(List<Unit>[])typeof(MatchManager).GetField("teamUnits",flags).GetValue(mm);lists[0].Clear();lists[0].AddRange(new[]{caster,ally,baseHero,second}.Where(u=>u&&!u.dead));lists[1].Clear();lists[1].AddRange(new[]{a,b,c}.Where(u=>u&&!u.dead));}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"avatar-runtime-results.txt",results);}
 static Unit Spawn(Vector3 p,int owner,string prefab="Humans/Swordsman"){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+prefab+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.SetHP(10000);u.armor=0;u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var pos,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=pos.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn(center,0,"Heroes/Humans/Inquisitor_Avatar");a=Spawn(center+Vector3.forward*2,foeOwner);b=Spawn(center+new Vector3(1.7f,0,1.5f),foeOwner);c=Spawn(center+Vector3.back*2,foeOwner);ally=Spawn(center+Vector3.left*1.5f,0);baseHero=Spawn(center+Vector3.left*4,0,"Heroes/Humans/Inquisitor_Base");speed=a.moveSpeed;
 dash=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Avatar_RighteousDash");blade=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Avatar_EcstasyBlade");pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");caster.LookAtInstant(new Vector2(a.transform.position.x,a.transform.position.z));
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,8,-7);camera.transform.LookAt(center);camera.orthographic=true;camera.orthographicSize=5.5f;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("AvatarSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"avatar-runtime-results.txt",results);File.WriteAllLines(W+"avatar-runtime-errors.txt",errors);File.WriteAllText(W+"avatar-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("AvatarSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif



