#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class BallistaSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit archer,foe,foe2,ally,far,tower,second;static PiercingLine pierce;static BonusDamageVsUnitType demolition;static float start,hp,lineHp;static int phase,foeOwner,impacts;static double boot;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static BallistaSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("BallistaSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void OnFired(Unit u,int id,int level,Unit target,Vector3 point){if(u==archer&&id==pierce.hitPresentation.id)impacts++;}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-ballista.txt")){try{File.Delete(W+"run-ballista.txt");}catch(IOException){return;}Begin();return;}
 if(!SessionState.GetBool("BallistaSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}

 if(phase==1&&Time.time-start>1){hp=foe2.health;archer.DealDamage(foe,100,archer.damageType,true,foe.transform.position);Check(foe2.health==hp,"Locked piercing does not affect extra targets");TechnologyManager.instance.UnlockTech(pierce.requiredTech[0].data[0],0);float first=foe.health;archer.DealDamage(foe,100,archer.damageType,true,foe.transform.position);Check(Mathf.Abs((first-foe.health)-(hp-foe2.health))<.01f,"Piercing deals full attack damage to extra target");Check(ally.health==10000&&far.health==10000,"Piercing excludes allies and targets outside corridor");TechnologyManager.instance.UnlockTech(pierce.requiredTech[0].data[0],0);Check(archer.OnAfterDamageDealCallbacks.Count(c=>c.Ability==pierce)==1,"Repeated unlock does not duplicate piercing");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.1f){Capture("ballista-piercing.png");TechnologyManager.instance.LockTech(pierce.requiredTech[0].data[0],0);hp=foe2.health;archer.DealDamage(foe,100,archer.damageType,true,foe.transform.position);Check(foe2.health==hp,"Lock removes piercing");StructureTests();phase=3;start=Time.time;return;}
 if(phase==3&&Time.time-start>.1f){Capture("ballista-demolition.png");TechnologyManager.instance.LockTech(demolition.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(pierce.requiredTech[0].data[0],0);hp=foe2.health;Shoot(archer,foe);archer.transform.position=center+Vector3.left*3;phase=4;start=Time.time;return;}
 if(phase==4&&Time.time-start>1f){Check(foe2.health<hp,"Real projectile pierces using launch position after caster moves");archer.transform.position=center;hp=foe2.health;second=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Ballista.prefab").GetComponent<Unit>(),center+Vector3.right*.2f,0,0);second.canAttack=false;second.doNotLookForTargets=true;second.Hold();Shoot(archer,foe);Shoot(second,foe);phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>1.2f){Check(Mathf.Abs(hp-foe2.health-200)<.1f,"Concurrent ballista projectiles each pierce once");second.Die(foeOwner,foe,false);impacts=0;hp=foe.health;archer.canAttack=true;archer.Attack(foe);phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>8f){archer.canAttack=false;archer.Hold();Check(foe.health<hp&&impacts>=4,"Repeated ordinary animated shots trigger piercing on primary and extra targets");Check(archer.unitState!=UnitStates.AbilityCasting,"Passive shots do not trap animator in casting");Capture("ballista-ordinary.png");hp=foe2.health;Shoot(archer,foe);archer.Die(foeOwner,foe,false);phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>1.2f){Check(foe2.health<hp,"Launched piercing shot survives caster death");Check(!archer.UseAbilityItem(0,false,foe,Vector3.zero),"Dead caster cannot cast");var p=Projectile.Spawn(0,null,AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/Projectiles/balista_projectile.prefab").GetComponent<Projectile>(),center+Vector3.up,Quaternion.identity,foe,true,100,archer.damageType,true,false);foe.Die(0,null,false);phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>2f){Check(!UnityEngine.Object.FindObjectsByType<Projectile>(FindObjectsSortMode.None).Any(p=>p.name.StartsWith("balista_projectile")),"Dead target projectile cleaned up");foe2.Die(0,null,false);ally.Die(foeOwner,null,false);far.Die(0,null,false);tower.Die(0,null,false);phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>4){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("PiercingHit")||v.name.StartsWith("DemolitionHit")),"Ballista impact VFX cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}

 static void Shoot(Unit u,Unit target){Projectile.SpawnAttack(u,u.projectileGO.GetComponent<Projectile>(),center+Vector3.up,Quaternion.identity,target,u.splashUnitSelector,u.splashUnitSelector,100,true,false);}
 static float HitTower(bool direct=true){float before=tower.health;archer.DealDamage(tower,100,archer.damageType,direct,tower.transform.position);return before-tower.health;}
 static void StructureTests(){float baseline=HitTower();TechnologyManager.instance.UnlockTech(demolition.requiredTech[0].data[0],0);float enhanced=HitTower();Check(baseline>0&&Mathf.Abs(enhanced/baseline-1.5f)<.005f,"Demolition increases actual tower damage exactly 50 percent");Check(Mathf.Abs(HitTower(false)-baseline)<.01f,"Demolition excludes indirect ability damage");TechnologyManager.instance.UnlockTech(demolition.requiredTech[0].data[0],0);Check(Mathf.Abs(HitTower()/baseline-1.5f)<.005f,"Repeated unlock does not stack demolition");TechnologyManager.instance.LockTech(demolition.requiredTech[0].data[0],0);Check(Mathf.Abs(HitTower()-baseline)<.01f,"Lock restores normal building damage");TechnologyManager.instance.UnlockTech(demolition.requiredTech[0].data[0],0);}
 static Unit Spawn(string path,Vector3 position,int owner){var u=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>(path).GetComponent<Unit>(),position,0,owner);u.maxHealth=10000;u.health=10000;u.armor=0;u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("BallistaSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);

  const string sample="Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab";
  archer=Spawn("Assets/Resources/UnitPrefabs/Units/Humans/Ballista.prefab",center,0);foe=Spawn(sample,center+Vector3.forward*6,foeOwner);foe2=Spawn(sample,center+Vector3.forward*3,foeOwner);ally=Spawn(sample,center+new Vector3(.5f,0,4),0);far=Spawn(sample,center+new Vector3(2,0,3),foeOwner);tower=Spawn("Assets/Resources/UnitPrefabs/Buildings/ORCtower.prefab",center+new Vector3(-4,0,6),foeOwner);
  archer.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));pierce=archer.abilities.OfType<PiercingLine>().Single();demolition=archer.abilities.OfType<BonusDamageVsUnitType>().Single();
  Check(archer.abilityLocked[Array.IndexOf(archer.abilities,pierce)]&&archer.abilityLocked[Array.IndexOf(archer.abilities,demolition)],"Both specializations start tech locked");
  SkillPresentationEvents.SkillFired+=OnFired;
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-5);camera.transform.LookAt(center+new Vector3(0,.5f,3));camera.orthographic=true;camera.orthographicSize=6;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"ballista-runtime-results.txt",results);}
 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"ballista-runtime-results.txt",results);File.WriteAllLines(W+"ballista-runtime-errors.txt",errors);File.WriteAllText(W+"ballista-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("BallistaSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


