#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class BloodBerserkerSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/BloodBerserker/";
 const string V="Assets/VFX/Skills/BloodBerserker/";
 const string A="Assets/Models/Units/Orcs/BloodBerserker/Animations/";
 static BloodBerserkerSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-berserker.txt"))return;try{File.Delete(W+"configure-berserker.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"berserker-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"berserker-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name,string label,VFXReferencer vfx){const string E="Assets/Resources/Effectors/Roster/Orcs/BloodBerserker/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}e.displayName=label;e.VFX=vfx;e.permanent=true;e.stacks=false;e.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_stat_damage.png");EditorUtility.SetDirty(e);return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);
 var rage=Asset<RageFromMissingHp>("BloodBerserker_DemonicRage");var thirst=Asset<LifestealPassive>("BloodBerserker_BloodThirst");var immunity=Asset<CompositePassive>("BloodBerserker_UnstoppableWrath");var heal=Asset<CompositeSkill>("BloodBerserker_LifestealVisual");
 rage.abilityName=new[]{"Демоническая Ярость"};rage.description=new[]{"Скорость атаки растёт с потерей здоровья, до +80% при20% HP. Ниже30% включается вампиризм."};rage.missingHpStep=0;rage.attackSpeedByMissingHp=new AnimationCurve(new Keyframe(0,0,1,1),new Keyframe(.8f,.8f,1,0),new Keyframe(1,.8f,0,0));rage.ragePresentation=Effect("BloodBerserker_Frenzy","Исступление",Vfx("BloodFrenzy","States/Aura_acceleration",.6f,true));rage.presentationMissingHpThreshold=.70001f;
 thirst.abilityName=new[]{"Кровавое исступление"};thirst.description=new[]{"Ниже30% HP прямые атаки восстанавливают30% урона по правилам штатного вампиризма. Жажда Крови повышает долю до50%."};thirst.healPercent=new[]{.3f};thirst.casterHpBelow=.3f;thirst.onlyDirectAttack=true;thirst.upgradeTechnology=Tech("Orki_T5_B1","Жажда Крови");thirst.upgradedHealPercent=.5f;thirst.healPresentation=heal;thirst.unitSelector=new UnitSelector{isEnemy=true,isUnit=true,isBuilding=true,isGround=true,isWater=true,isAir=true};
 immunity.abilityName=new[]{"Неудержимый Гнев"};immunity.description=new[]{"В исступлении ниже30% HP снимает замедления передвижения, атаки и эффекты снижения исходящего урона."};immunity.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{Tech("Orki_T5_B2","Неудержимый Гнев")}}};immunity.slowImmunity=new PassiveSlowImmunityBlock{enabled=true,casterHpBelow=.3f,alsoRemoveAttackSlow=true,alsoRemoveDamageReduction=true};
 heal.targetMode=SkillTargetMode.SmartUnit;heal.spawnSocket=SkillSocketType.None;heal.procAnimationState="";heal.impactVFX=Vfx("BloodSiphon","Regeneration/Regeneration_health",.45f);heal.impactVfxLifetime=.6f;
 const string M=V+"Materials/";InterflowEditorUI.EnsureFolder(M);foreach(var fx in new[]{rage.ragePresentation.VFX,heal.impactVFX}){var path=AssetDatabase.GetAssetPath(fx);var go=PrefabUtility.LoadPrefabContents(path);try{foreach(var ps in go.GetComponentsInChildren<ParticleSystem>(true)){var main=ps.main;main.startDelay=0;main.maxParticles=Mathf.Min(main.maxParticles,20);main.startColor=new Color(.7f,.03f,.015f,.65f);var color=ps.colorOverLifetime;var g=new Gradient();g.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(new Color(.4f,.015f,.01f),1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(0,1)});color.enabled=true;color.color=g;}foreach(var r in go.GetComponentsInChildren<Renderer>(true)){var mats=r.sharedMaterials;for(int i=0;i<mats.Length;i++){if(!mats[i])continue;var mp=M+mats[i].name+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(mp);if(!mat){mat=new Material(mats[i]);AssetDatabase.CreateAsset(mat,mp);for(int j=0;j<mat.shader.GetPropertyCount();j++)if(mat.shader.GetPropertyType(j)==UnityEngine.Rendering.ShaderPropertyType.Color){var p=mat.shader.GetPropertyName(j);var c=mat.GetColor(p);if(c.maxColorComponent>.01f)mat.SetColor(p,new Color(1,.04f,.02f,c.a));}EditorUtility.SetDirty(mat);}mats[i]=mat;}r.sharedMaterials=mats;}PrefabUtility.SaveAsPrefabAsset(go,path);}finally{PrefabUtility.UnloadPrefabContents(go);}}
 foreach(var a in new Ability[]{rage,thirst,immunity,heal}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_stat_damage.png")};EditorUtility.SetDirty(a);}
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/BloodBerserker.prefab";var root=PrefabUtility.LoadPrefabContents(prefab);try{var u=root.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=rage&&a!=thirst&&a!=immunity).Concat(new Ability[]{rage,thirst,immunity}).ToArray();u.abilityLevel=new int[u.abilities.Length];PrefabUtility.SaveAsPrefabAsset(root,prefab);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();}
}
#endif
