#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class CannonSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 static CannonSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-cannon.txt"))return;try{File.Delete(W+"configure-cannon.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"cannon-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"cannon-configured.txt",e.ToString());Debug.LogException(e);}}
 static void Configure(){const string folder="Assets/Resources/Ability/Roster/Humans/Cannon/";InterflowEditorUI.EnsureFolder(folder);var skill=AssetDatabase.LoadAssetAtPath<CompositePassive>(folder+"Cannon_ExplosiveShell.asset");if(!skill){skill=ScriptableObject.CreateInstance<CompositePassive>();skill.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);AssetDatabase.CreateAsset(skill,folder+"Cannon_ExplosiveShell.asset");}skill.abilityName=new[]{"Разрывной снаряд"};skill.description=new[]{"Базовая атака пушки наносит урон врагам в радиусе 2 м от попадания."};skill.maxLevels=1;skill.splash=new PassiveSplashBlock{enabled=true,enableSplashIfDisabled=true,radiusPercentChange=0,radiusFlatChange=2,newSplashReduction=1};skill.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};EditorUtility.SetDirty(skill);
 const string path="Assets/Resources/UnitPrefabs/Units/Humans/Cannon.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var unit=root.GetComponent<Unit>();unit.abilities=(unit.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=skill).Concat(new Ability[]{skill}).ToArray();unit.abilityLevel=new int[unit.abilities.Length];unit.splashUnitSelector=new UnitSelector(false,false,true,true,true,false,false,true,true,false,false,false);PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();}
}
#endif
