#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class FelFireHurlerSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/FelFireHurler/";
 const string V="Assets/VFX/Skills/FelFireHurler/";
 const string A="Assets/Models/Units/Orcs/FelFireHurler/Animations/";
 static FelFireHurlerSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-felfirehurler.txt"))return;try{File.Delete(W+"configure-felfirehurler.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"felfirehurler-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"felfirehurler-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(source.StartsWith("Assets/")?source:"Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);
 var flame=Asset<CompositePassive>("FelFireHurler_UnquenchableFlame");var burst=Asset<CompositeSkill>("FelFireHurler_DeathBurstVisual");
 const string E="Assets/Resources/Effectors/Roster/Orcs/FelFireHurler/";InterflowEditorUI.EnsureFolder(E);var burn=AssetDatabase.LoadAssetAtPath<Effector>(E+"FelFireHurler_FelFlame.asset");if(!burn){burn=ScriptableObject.CreateInstance<Effector>();burn.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(burn,E+"FelFireHurler_FelFlame.asset");}
 burn.displayName="Негасимое Пламя";burn.description="Зелёное пламя: -10% входящего лечения за стак, максимум 5. На 5 стаках специализация снижает броню на 15%; другая передаёт 2 стака соседям при смерти. Для альфы: 4 секунды, 3 магического урона/с за стак, радиус распространения 2.5 м.";burn.duration=4;burn.stacks=true;burn.maxStacks=5;burn.healingReduction=.1f;burn.damageAmount=3;burn.damageType=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");burn.maximumStackTechnology=Tech("Orki_T1_B1","Разогрев Скверны");burn.maximumStackEffects=new AbilityPassiveEffects{exactPercentageReductions=true,armorPercentageChange=-.15f};burn.deathSpreadTechnology=Tech("Orki_T1_B2","Оскверненный Взрыв");burn.deathSpreadRadius=2.5f;burn.deathSpreadStacks=2;burn.deathSpreadPresentation=burst;burn.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png");
 burn.VFX=Vfx("FelFlameBurn","Assets/Synty/PolygonDarkFortress/Prefabs/FX/FX_Fire_Small_01.prefab",.5f,true);
 var path=AssetDatabase.GetAssetPath(burn.VFX);var fx=PrefabUtility.LoadPrefabContents(path);try{var green=AssetDatabase.LoadAssetAtPath<Material>("Assets/Synty/PolygonDarkFortress/Materials/FX/Fire/FireFrames_Green_01.mat");if(!green)throw new Exception("Missing existing green fire material");fx.transform.GetChild(0).localPosition=Vector3.up*.45f;foreach(var ps in fx.GetComponentsInChildren<ParticleSystem>(true)){var sheet=ps.textureSheetAnimation;sheet.enabled=true;sheet.numTilesX=10;sheet.numTilesY=10;sheet.animation=ParticleSystemAnimationType.WholeSheet;sheet.frameOverTime=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,0,1,1));var m=ps.main;m.startDelay=0;m.maxParticles=10;m.startLifetime=.8f;m.startSize=new ParticleSystem.MinMaxCurve(1f,1.4f);m.startColor=Color.white;m.startSpeed=.35f;var size=ps.sizeOverLifetime;size.enabled=false;var shape=ps.shape;shape.enabled=true;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=.35f;var em=ps.emission;em.rateOverTime=8;}foreach(var renderer in fx.GetComponentsInChildren<ParticleSystemRenderer>(true)) {renderer.sharedMaterial=green;renderer.renderMode=ParticleSystemRenderMode.Billboard;}PrefabUtility.SaveAsPrefabAsset(fx,path);}finally{PrefabUtility.UnloadPrefabContents(fx);}
 burst.targetMode=SkillTargetMode.Self;burst.procAnimationState="";burst.spawnSocket=SkillSocketType.None;burst.impactVFX=Vfx("FelFlameDeathBurst","Assets/Models/Units/Orcs/FelWarlock/FelFireImpact.prefab",1);burst.impactVfxLifetime=1.1f;
 flame.abilityName=new[]{"Негасимое Пламя"};flame.description=new[]{burn.description};flame.attackEffectors=new PassiveAttackEffectorsBlock{enabled=true,effectors=new[]{burn}};
 foreach(var a in new Ability[]{flame,burst}){a.maxLevels=1;a.icon=new[]{burn.icon};EditorUtility.SetDirty(a);}EditorUtility.SetDirty(burn);
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/FelFireHurler.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=flame).Concat(new Ability[]{flame}).ToArray();u.abilityLevel=new int[u.abilities.Length];PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 File.WriteAllText(W+"felfirehurler-vfx-components.txt",string.Join("\n",burst.impactVFX.GetComponentsInChildren<Component>(true).Select(c=>c?c.GetType().Name:"MISSING")));
 }
}
#endif
