#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class FelFireHurlerSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,primary,near,ally,outside;static CompositePassive flame;static Effector burn;static DamageType physical;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start,hpBefore;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static FelFireHurlerSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("FelFireHurlerSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-felfirehurler.txt")){File.Delete(W+"run-felfirehurler.txt");Begin();return;}
 if(!SessionState.GetBool("FelFireHurlerSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.8f){Mechanics();hpBefore=primary.health;phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>1.1f){var loss=hpBefore-primary.health;Check(loss>=14&&loss<=20,"Five stacks deal about fifteen magic damage per second: "+loss);Capture("felfirehurler-five-stacks.png");TechnologyManager.instance.LockTech(burn.maximumStackTechnology,0);phase=3;start=Time.time;return;}
 if(phase==3&&Time.time-start>.3f){Check(Mathf.Abs(primary.armor-12)<.001f,"Lock technology removes max-stack armor reduction on next native tick");phase=4;return;}
 if(phase==4&&Time.time-start>3.3f){Check(Count(primary)==0,"Stacks expire after four seconds from last hit");primary.SetHP(500);primary.ChangeHP(100);Check(Mathf.Abs(primary.health-600)<.001f,"Healing returns to full strength after expiry");DeathTests();phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>.15f){Capture("felfirehurler-death-spread.png");phase=6;return;}
 if(phase==6&&Time.time-start>4.5f){Check(Count(near)==0,"Transferred stacks expire normally");primary=Spawn(center+Vector3.forward*4,foeOwner);caster.canAttack=true;caster.attackDamage=15;caster.Attack(primary);phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>6.5f){Check(primary.health<970&&Count(primary)>0,"Native animated green projectiles apply flame repeatedly");Check(Count(primary)<=5,"Concurrent projectile impacts respect cap");Capture("felfirehurler-native-attack.png");caster.canAttack=false;caster.Hold();caster.Die(-1,null,false);hpBefore=primary.health;phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>5f){Check(primary.health<hpBefore,"Existing flame keeps ticking after caster death");Check(Count(primary)==0,"Flame ends normally with dead caster");Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("FelFlame")),"Flame and death burst visuals fully cleaned");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("FelFireHurlerSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}


 static Unit Spawn(Vector3 p,int owner,bool isHurler=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(isHurler?"Orcs/FelFireHurler":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=1000;u.SetHP(1000);u.armor=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
 caster=Spawn(center,0,true);primary=Spawn(center+Vector3.forward*4,foeOwner);near=Spawn(primary.transform.position+Vector3.left*1.5f,foeOwner);ally=Spawn(primary.transform.position+Vector3.right*1.5f,0);outside=Spawn(primary.transform.position+Vector3.forward*6,foeOwner);primary.armor=10;
 flame=(CompositePassive)caster.abilities.First(a=>a.name=="FelFireHurler_UnquenchableFlame");burn=flame.attackEffectors.effectors[0];physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
 camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,8,-5);camera.transform.LookAt(center+new Vector3(0,.5f,2));camera.orthographic=true;camera.orthographicSize=5.5f;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"felfirehurler-runtime-results.txt",results);}
 static int Count(Unit u)=>u.effectors.Count(h=>h.effector==burn);
 static void Hit(Unit source,Unit victim,bool direct=true){source.DealDamage(victim,1,physical,direct,victim.transform.position);}
 static void Apply(Unit victim,int count){for(int i=0;i<count;i++)Hit(caster,victim);}
 static void Mechanics(){Check(!caster.abilityLocked[Array.IndexOf(caster.abilities,flame)],"Base flame passive unlocked");Hit(caster,primary,false);Check(Count(primary)==0,"Indirect damage cannot apply attack flame");Apply(primary,1);Check(Count(primary)==1,"One direct hit creates one native flame stack");primary.SetHP(500);primary.ChangeHP(100);Check(Mathf.Abs(primary.health-590)<.001f,"One stack reduces incoming healing exactly ten percent");Apply(primary,4);Check(Count(primary)==5,"Five hits reach five stacks");Check(primary.armor==10,"Locked specialization does not reduce armor");primary.SetHP(500);primary.ChangeHP(100);Check(Mathf.Abs(primary.health-550)<.001f,"Five stacks reduce healing exactly fifty percent");Apply(primary,10);Check(Count(primary)==5,"Further hits refresh rather than exceed five stacks");Check(primary.effectors.Where(h=>h.effector==burn).All(h=>h.currentTime==0),"Repeated hit refreshes all current stack durations");Check(primary.GetComponentsInChildren<VFXReferencer>(true).Count(v=>v.name.StartsWith("FelFlameBurn"))<=5,"Persistent visuals bounded by stack count");var icons=new List<UnitStatusIcons.Entry>();UnitStatusIcons.Collect(primary,icons);Check(icons.Any(i=>i.key==burn.id),"Bounded flame has native status icon");TechnologyManager.instance.UnlockTech(burn.maximumStackTechnology,0);Apply(primary,1);Check(Mathf.Abs(primary.armor-8.5f)<.001f,"Max-stack specialization reduces armor exactly fifteen percent");primary.ChangeArmor(2);Check(Mathf.Abs(primary.armor-10.2f)<.001f,"Armor reduction composes with another armor change");Effector.EffectorRemove(primary,primary.effectors.First(h=>h.effector==burn));Check(Count(primary)==4&&Mathf.Abs(primary.armor-12)<.001f,"Dropping below maximum restores armor without drift");Apply(primary,1);Check(Mathf.Abs(primary.armor-10.2f)<.001f,"Returning to five stacks reapplies reduction once");flame.Unlock(caster,0,0);Check(caster.attackEffectors.Count(e=>e==burn)==1,"Repeated passive unlock does not duplicate flame effectors");}
 static void DeathTests(){Apply(primary,5);primary.Die(-1,null,false);Check(Count(near)==0,"Locked death spread does nothing");primary=Spawn(center+Vector3.forward*4,foeOwner);TechnologyManager.instance.UnlockTech(burn.deathSpreadTechnology,0);Apply(primary,4);primary.Die(-1,null,false);Check(Count(near)==0,"Four stacks do not spread on death");primary=Spawn(center+Vector3.forward*4,foeOwner);Apply(primary,5);primary.Die(-1,null,false);Check(Count(near)==2,"Five-stack death passes exactly two stacks to neighbour");Check(Count(ally)==0&&Count(outside)==0,"Death spread excludes allies and distant enemies");var other=Spawn(center+Vector3.left*3,0,true);for(int i=0;i<10;i++)Hit(other,near);Check(Count(near)==5,"Multiple casters share target stack cap");other.Die(-1,null,false);Check(Count(near)==5,"Caster death does not remove existing target flame");}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("FelFlame")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}


 static void Finish(){File.WriteAllLines(W+"felfirehurler-runtime-results.txt",results);File.WriteAllLines(W+"felfirehurler-runtime-errors.txt",errors);File.WriteAllText(W+"felfirehurler-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("FelFireHurlerSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif
