#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class FelLordSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,a,b,ally,far,second;static CompositeSkill shot;static AutoAbilityUser auto;static Vector3 center,point;static Camera camera;static int foeOwner,phase,casts,impacts,priorCasts;static float start,speed;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static FelLordSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("FelLordSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-fellord.txt")){File.Delete(W+"run-fellord.txt");Begin();return;}
 if(!SessionState.GetBool("FelLordSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.5f){Check(shot.AutoCastReady(caster,0,out _),"Native target selection finds enemy");Check(Cast(),"Native cast accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.2f){Check(a.health==10000&&b.health==10000,"Windup delays line damage");Check(caster.hasCastAnim,"Dedicated native cast state exists");phase=3;return;}
 if(phase==3&&Time.time-start>.9f){Check(a.health==9920&&b.health==9920,"Line deals eighty damage to all enemies inside");Check(ally.health==10000&&far.health==10000,"Line excludes allies and side targets");Check(a.muted&&!b.muted,"Only mage silenced");Check(a.effectors.Count==0,"Mage loses accumulated speed effectors");Check(Mathf.Abs(a.attackSpeed-speed)<.001f,"Purge restores original attack interval");Check(a.mana==100,"Locked mana specialization does not burn");Check(Vector3.Distance(b.transform.position,point+Vector3.back*2)<.2f,"Locked pull does not move target");Check(!Cast(),"Cooldown blocks duplicate");Capture("fellord-fissure.png");phase=4;return;}
 if(phase==4&&Time.time-start>4){Check(!a.muted,"Silence ends after three seconds");Check(caster.unitState!=UnitStates.AbilityCasting,"Cast animation returns to idle");TechnologyManager.instance.UnlockTech(shot.line.pullTechnology,0);TechnologyManager.instance.UnlockTech(shot.disruption.manaBurnTechnology,0);caster.Hold();caster.agent.Warp(center);ResetCD();Check(Cast(),"Cast accepted with specializations");phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>.9f){Check(Mathf.Abs(a.mana-70)<.1f&&Mathf.Abs(a.health-9810)<.1f,"Mage burns thirty current mana into thirty pure damage");Check(b.mana==100&&b.health==9840,"Nonmage takes only base damage");Check(Vector3.Distance(a.transform.position,center+Vector3.forward*4)<1,"Pull gathers mage at middle of line");Capture("fellord-pull.png");priorCasts=casts;auto.enabled=true;phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>8){auto.enabled=false;Check(casts>priorCasts,"Autocast repeats after seven second cooldown");caster.Hold();caster.agent.Warp(center);a.agent.Warp(point);b.agent.Warp(point+Vector3.back*2);a.SetHP(10000);a.ChangeMP(100-a.mana);second=Spawn(center+Vector3.left*.4f,0,true);caster.LookAtInstant(new Vector2(point.x,point.z));second.LookAtInstant(new Vector2(point.x,point.z));shot.Use(caster,0,0,a);shot.Use(second,0,0,a);Check(a.health<9840&&a.mana<70,"Simultaneous lords have independent hits and current-mana burn");second.Die(-1,null,false);caster.Hold();caster.agent.Warp(center);foreach(var u in new[]{a,b,far})u.Die(-1,null,false);Check(!shot.AutoCastReady(caster,0,out _),"No enemy prevents autocast");a=Spawn(point,foeOwner);ResetCD();Check(Cast(),"Cast starts before victim dies");a.Die(-1,null,false);phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>1.5f){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death during windup releases casting state");a=Spawn(point,foeOwner);ResetCD();Cast();caster.Die(-1,null,false);phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>4){Check(a.health==10000,"Caster death cancels pending cast");Check(!Cast(),"Dead caster rejects cast");Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("FelFissure")||v.name.StartsWith("FelSilence")),"All fissure and silence visuals expire");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static bool Cast()=>caster.UseAbilityItem(Array.IndexOf(caster.abilities,shot),false,a,Vector3.zero);
 static void ResetCD()=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,shot),false);
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"fellord-runtime-results.txt",results);}
 static Unit Spawn(Vector3 p,int owner,bool siege=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(siege?"Orcs/FelLord":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.SetHP(10000);u.armor=0;u.maxMana=100;u.ChangeMP(100-u.mana);u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;point=center+Vector3.forward*6;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn(center,0,true);a=Spawn(point,foeOwner);b=Spawn(point+Vector3.back*2,foeOwner);ally=Spawn(point+Vector3.left*.8f,0);far=Spawn(point+Vector3.right*4,foeOwner);speed=a.attackSpeed;
 shot=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="FelLord_Fissure");auto=caster.GetComponent<AutoAbilityUser>();caster.LookAtInstant(new Vector2(point.x,point.z));a.unitCategory=Unit.UnitCategory.Mage;var buff=ScriptableObject.CreateInstance<Effector>();buff.permanent=true;buff.stacks=true;buff.passiveEffectsOn=true;buff.passiveEffects=new AbilityPassiveEffects{attackSpeedPercentageChange=.2f,moveSpeedPercentageChange=.1f};Effector.EffectorAdd(a,buff,caster,0);Effector.EffectorAdd(a,buff,caster,0);Check(a.attackSpeed<speed,"Two speed stacks applied before purge");
 SkillPresentationEvents.SkillFired+=(u,id,l,t,pt)=>{if(id==shot.id)casts++;};
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(8,10,-6);camera.transform.LookAt(center+Vector3.forward*3);camera.orthographic=true;camera.orthographicSize=6;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("FelLordSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"fellord-runtime-results.txt",results);File.WriteAllLines(W+"fellord-runtime-errors.txt",errors);File.WriteAllText(W+"fellord-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("FelLordSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


