#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class FelLordSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/FelLord/";
 const string V="Assets/VFX/Skills/FelLord/";
 const string A="Assets/Models/Units/Orcs/FelLord/Animations/";
 static FelLordSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-fellord.txt"))return;try{File.Delete(W+"configure-fellord.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"fellord-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"fellord-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name){const string E="Assets/Resources/Effectors/Roster/Orcs/FelLord/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var shot=Asset<CompositeSkill>("FelLord_Fissure");var mute=Asset<CompositeSkill>("FelLord_SilenceVisual");
 shot.abilityName=new[]{"Разрыв Скверны"};shot.description=new[]{"Каждые7с разлом наносит урон всем врагам по линии. Маги теряют ускоряющие бафы и получают немоту3с. Пленение Разломом притягивает к середине полосы; Выжигание Истоков сжигает30% текущей маны заглушенных целей. Альфа: линия8x2.4м, урон80 магический."};shot.targetMode=SkillTargetMode.SmartPoint;shot.targetStrategy=SkillTargetStrategy.Nearest;shot.unitSelector=new UnitSelector{isEnemy=true,isUnit=true,isBuilding=true,isGround=true,isWater=true};shot.radius=new[]{1.2f};shot.castRange=new[]{8f};shot.castTime=new[]{.6f};shot.cooldown=new[]{7f};shot.manaCost=new[]{0f};shot.duration=new[]{0f};shot.directionMatters=true;shot.spawnSocket=SkillSocketType.None;shot.procAnimationState="";
 shot.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{80f},damageType=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset"),targets=SkillDamageTargets.Enemies}}};
 mute.targetMode=SkillTargetMode.SmartUnit;mute.spawnSocket=SkillSocketType.None;mute.procAnimationState="";mute.impactVFX=Vfx("FelSilence","States/Stun",.45f);mute.impactVfxLifetime=3;
 shot.disruption=new SkillDisruptionBlock{enabled=true,categories=new[]{Unit.UnitCategory.Mage},additionalPrefabs=new[]{AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Heroes/Orcs/Korgal.prefab").GetComponent<Unit>()},silenceSeconds=3,purgeSpeedBuffs=true,manaBurnTechnology=Tech("Orki_T6_B2","Выжигание Истоков"),currentManaFraction=.3f,manaDamageType=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset"),presentation=mute};
 var impact=Vfx("FelFissureBurst","Fire/Fire_explosion_earth",.4f);
 const string M=V+"Materials/";InterflowEditorUI.EnsureFolder(M);foreach(var fx in new[]{impact,mute.impactVFX}){var path=AssetDatabase.GetAssetPath(fx);var root=PrefabUtility.LoadPrefabContents(path);try{foreach(var ps in root.GetComponentsInChildren<ParticleSystem>(true)){var main=ps.main;main.startDelay=0;main.maxParticles=Mathf.Min(20,main.maxParticles);main.startColor=new Color(.25f,1,.12f,1);var color=ps.colorOverLifetime;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(new Color(.3f,.8f,.1f),1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(1,.5f),new GradientAlphaKey(0,1)});color.enabled=true;color.color=gradient;}foreach(var renderer in root.GetComponentsInChildren<Renderer>(true)){var mats=renderer.sharedMaterials;for(int i=0;i<mats.Length;i++){var source=mats[i];if(!source)continue;var mp=M+source.name.Replace("Fel_","")+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(mp);if(!mat){mat=new Material(source);mat.name="Fel_"+source.name;AssetDatabase.CreateAsset(mat,mp);for(int j=0;j<mat.shader.GetPropertyCount();j++){if(mat.shader.GetPropertyType(j)!=UnityEngine.Rendering.ShaderPropertyType.Color)continue;var prop=mat.shader.GetPropertyName(j);var old=mat.GetColor(prop);if(old.maxColorComponent>.01f)mat.SetColor(prop,new Color(.2f,1,.1f,old.a));}EditorUtility.SetDirty(mat);}mats[i]=mat;}renderer.sharedMaterials=mats;}PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
 var fissurePath=V+"FelFissure.prefab";var fissurePrefab=AssetDatabase.LoadAssetAtPath<GameObject>(fissurePath);if(!fissurePrefab){var root=new GameObject("FelFissure");try{root.AddComponent<VFXReferencer>();var mat=new Material(AssetDatabase.LoadAssetAtPath<Material>("Assets/VFX/Materials/LaserBeam.mat"));mat.name="FelFissureGlow";AssetDatabase.CreateAsset(mat,V+"FelFissureGlow.mat");for(int row=0;row<3;row++){var g=new GameObject("Crack"+row);g.transform.SetParent(root.transform,false);var lr=g.AddComponent<LineRenderer>();lr.useWorldSpace=false;lr.sharedMaterial=mat;lr.positionCount=19;lr.widthMultiplier=row==0?.14f:.045f;lr.startColor=new Color(.35f,1,.04f,.8f);lr.endColor=new Color(.08f,.35f,.02f,.1f);for(int i=0;i<19;i++)lr.SetPosition(i,new Vector3((row-1)*.7f+Mathf.Sin(i*2.1f+row)*.18f,.09f,i*8f/18));}for(int i=0;i<4;i++){var part=(GameObject)PrefabUtility.InstantiatePrefab(impact.gameObject);part.transform.SetParent(root.transform,false);part.transform.localPosition=new Vector3(0,0,1+i*2);foreach(var ps in part.GetComponentsInChildren<ParticleSystem>(true)){var main=ps.main;main.startDelay=i*.04f;main.maxParticles=Mathf.Min(12,main.maxParticles);}}fissurePrefab=PrefabUtility.SaveAsPrefabAsset(root,fissurePath);}finally{UnityEngine.Object.DestroyImmediate(root);}}
 var editRoot=PrefabUtility.LoadPrefabContents(fissurePath);try{var lines=editRoot.GetComponentsInChildren<LineRenderer>(true);var mat=lines[0].sharedMaterial;foreach(var lr in lines){lr.widthMultiplier=.055f;lr.startColor=new Color(.16f,.5f,.015f,.65f);lr.endColor=new Color(.04f,.15f,.005f,.05f);lr.positionCount=25;int row=Array.IndexOf(lines,lr);for(int i=0;i<25;i++){float z=i*8f/24;float x=(Mathf.PerlinNoise(i*.73f,row*2.7f)-.5f)*1.3f+(row-1)*.25f;lr.SetPosition(i,new Vector3(x,.08f,z));}}
 for(int i=0;i<6;i++){var child=editRoot.transform.Find("Branch"+i);if(!child){var branch=new GameObject("Branch"+i);branch.transform.SetParent(editRoot.transform,false);child=branch.transform;}var lr=child.GetComponent<LineRenderer>();if(!lr)lr=child.gameObject.AddComponent<LineRenderer>();lr.useWorldSpace=false;lr.sharedMaterial=mat;lr.widthMultiplier=.035f;lr.startColor=new Color(.2f,.6f,.02f,.65f);lr.endColor=new Color(.03f,.08f,0,0);lr.positionCount=4;float z=.8f+i*1.15f;float side=i%2==0?1:-1;lr.SetPositions(new[]{new Vector3(0,.08f,z),new Vector3(side*.35f,.08f,z+.2f),new Vector3(side*.7f,.08f,z+.1f),new Vector3(side,.08f,z+.45f)});}
 foreach(var ps in editRoot.GetComponentsInChildren<ParticleSystem>(true))if(ps.name.Trim()=="circles"||ps.name=="glow")ps.gameObject.SetActive(false);PrefabUtility.SaveAsPrefabAsset(editRoot,fissurePath);}finally{PrefabUtility.UnloadPrefabContents(editRoot);}
 shot.line=new SkillLineBlock{enabled=true,length=8,width=2.4f,pullTechnology=Tech("Orki_T6_B1","Пленение Разломом"),presentation=fissurePrefab.GetComponent<VFXReferencer>(),visualLifetime=1.2f};
 foreach(var ability in new Ability[]{shot,mute}){ability.maxLevels=1;ability.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};EditorUtility.SetDirty(ability);}
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/FelLord.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(x=>x&&x!=shot).Concat(new Ability[]{shot}).ToArray();u.abilityLevel=new int[u.abilities.Length];var auto=go.GetComponent<AutoAbilityUser>();if(!auto)auto=go.AddComponent<AutoAbilityUser>();var so=new SerializedObject(auto);var list=so.FindProperty("autoAbilities");list.arraySize=1;list.GetArrayElementAtIndex(0).objectReferenceValue=shot;so.ApplyModifiedPropertiesWithoutUndo();var animator=go.GetComponentInChildren<Animator>(true);
string controllerPath=A+"FelLord_Skills.controller";var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);if(!controller){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),controllerPath))throw new Exception("Cannot copy caster animator");controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);}var sm=controller.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack1");var clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);clip.name="FelLord_Cast";AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);AssetDatabase.CreateAsset(clip,A+"FelLord_Cast.anim");cast=sm.AddState("cast");cast.motion=clip;cast.speed=clip.length/.95f;var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=controller;EditorUtility.SetDirty(controller);File.WriteAllLines(W+"fellord-animation.txt",sm.states.Select(x=>x.state.name+" | "+(x.state.motion?x.state.motion.name:"none")));PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();}}
#endif
