#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class FelSiegeBehemothSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/FelSiegeBehemoth/";
 const string V="Assets/VFX/Skills/FelSiegeBehemoth/";
 const string A="Assets/Models/Units/Orcs/FelSiegeBehemoth/Animations/";
 static FelSiegeBehemothSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-felsiege.txt"))return;try{File.Delete(W+"configure-felsiege.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"felsiege-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"felsiege-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name){const string E="Assets/Resources/Effectors/Roster/Orcs/FelSiegeBehemoth/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var shot=Asset<CompositeSkill>("FelSiege_FelVolley");var impact=Asset<CompositeSkill>("FelSiege_MeteorImpact");var stun=Asset<CompositeSkill>("FelSiege_StunVisual");var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");
 var slowTech=Tech("Orki_T4_B1","Разрушитель Защиты");var stunTech=Tech("Orki_T4_B2","Демонический Осколок");
 var armor=Effect("FelSiege_ScorchedArmor");armor.displayName="Выжженная броня";armor.duration=.3f;armor.stacks=false;armor.passiveEffectsOn=true;armor.passiveEffects=new AbilityPassiveEffects{armorPercentageChange=-.25f,exactPercentageReductions=true};armor.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_status_slow.png");EditorUtility.SetDirty(armor);
 var slow=Effect("FelSiege_AttackSlow");slow.displayName="Разрушитель Защиты";slow.duration=.3f;slow.stacks=false;slow.passiveEffectsOn=true;slow.passiveEffects=new AbilityPassiveEffects{attackSpeedPercentageChange=-.2f,exactPercentageReductions=true};slow.icon=armor.icon;EditorUtility.SetDirty(slow);
 string zonePath=V+"FelScorchedGround.prefab";var zoneAsset=AssetDatabase.LoadAssetAtPath<GameObject>(zonePath);if(!zoneAsset){if(!AssetDatabase.CopyAsset("Assets/VFX/Skills/OrcCatapult/BurningGround.prefab",zonePath))throw new Exception("Cannot copy zone");}
 var zoneRoot=PrefabUtility.LoadPrefabContents(zonePath);try{var so=new SerializedObject(zoneRoot.GetComponent<GroundDamageZone>());so.FindProperty("radius").floatValue=2.5f;so.FindProperty("duration").floatValue=6;so.FindProperty("damagePerSecond").floatValue=12;so.FindProperty("damageType").objectReferenceValue=magic;var z=so.FindProperty("zoneEffectors");z.arraySize=1;z.GetArrayElementAtIndex(0).objectReferenceValue=armor;var c=so.FindProperty("conditionalEffectors");c.arraySize=1;c.GetArrayElementAtIndex(0).FindPropertyRelative("effector").objectReferenceValue=slow;c.GetArrayElementAtIndex(0).FindPropertyRelative("requiredTechnology").objectReferenceValue=slowTech;so.ApplyModifiedPropertiesWithoutUndo();Tint(zoneRoot);
 var rim=zoneRoot.transform.Find("ZoneBoundary");if(!rim){var r=new GameObject("ZoneBoundary");r.transform.SetParent(zoneRoot.transform,false);rim=r.transform;}
 var line=rim.GetComponent<LineRenderer>();if(!line)line=rim.gameObject.AddComponent<LineRenderer>();var material=AssetDatabase.LoadAssetAtPath<Material>(V+"FelBoundary.mat");if(!material){material=new Material(AssetDatabase.LoadAssetAtPath<Material>("Assets/VFX/Materials/LaserBeam.mat"));material.name="FelBoundary";AssetDatabase.CreateAsset(material,V+"FelBoundary.mat");}
 line.sharedMaterial=material;line.useWorldSpace=false;line.loop=true;line.widthMultiplier=.025f;line.startColor=line.endColor=new Color(.15f,.5f,.03f,.5f);line.positionCount=64;for(int i=0;i<64;i++){float theta=i*Mathf.PI*2/64;line.SetPosition(i,new Vector3(Mathf.Cos(theta)*2.5f,.08f,Mathf.Sin(theta)*2.5f));}
 zoneAsset=PrefabUtility.SaveAsPrefabAsset(zoneRoot,zonePath);}finally{PrefabUtility.UnloadPrefabContents(zoneRoot);}
 var enemies=new UnitSelector{isEnemy=true,isUnit=true,isBuilding=true,isGround=true,isWater=true};
 shot.abilityName=new[]{"Скверно-Залп"};shot.description=new[]{"Метеорит по постройкам и скоплениям врагов. Зона на6с: броня−25%; Разрушитель Защиты: скорость атаки−20%; Демонический Осколок: главная цель оглушена2с. Альфа: попадание60 магического урона, зона12/с, радиус2.5м, дальность12м, CD10с."};shot.targetMode=SkillTargetMode.SmartUnit;shot.targetStrategy=SkillTargetStrategy.Cluster;shot.unitSelector=enemies;shot.radius=new[]{2.5f};shot.castRange=new[]{12f};shot.castTime=new[]{.45f};shot.cooldown=new[]{10f};shot.manaCost=new[]{0f};shot.duration=new[]{0f};shot.delivery=SkillDelivery.Projectile;shot.projectileFollowsTarget=true;shot.spawnSocket=SkillSocketType.None;shot.localOffset=new Vector3(0,2.4f,1.2f);shot.procAnimationState="";
 shot.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{60f},damageType=magic}}};
 string pp="Assets/Resources/Projectiles/FelSiege_Meteor.prefab";if(!AssetDatabase.LoadAssetAtPath<GameObject>(pp)){if(!AssetDatabase.CopyAsset("Assets/Models/Units/Orcs/FelSiegeBehemoth/FelMeteor.prefab",pp))throw new Exception("Cannot clone meteor");var ball=PrefabUtility.LoadPrefabContents(pp);try{var p=ball.GetComponent<Projectile>();p.id=Resources.LoadAll<GameObject>("Projectiles").Select(g=>g.GetComponent<Projectile>()).Where(p=>p).Select(p=>p.id).DefaultIfEmpty(0).Max()+1;p.speed=8;p.impactVFX=null;PrefabUtility.SaveAsPrefabAsset(ball,pp);}finally{PrefabUtility.UnloadPrefabContents(ball);}}shot.projectilePrefab=AssetDatabase.LoadAssetAtPath<GameObject>(pp).GetComponent<Projectile>();
 impact.abilityName=new[]{"Скверно-Залп — выжженная зона"};impact.targetMode=SkillTargetMode.SmartPoint;impact.unitSelector=enemies;impact.radius=new[]{2.5f};impact.duration=new[]{0f};impact.castTime=new[]{0f};impact.cooldown=new[]{0f};impact.spawnSocket=SkillSocketType.None;impact.procAnimationState="";impact.groundZone=new SkillGroundZoneBlock{enabled=true,zonePrefab=zoneAsset};impact.impactVFX=Vfx("FelMeteorImpact","Fire/Fire_explosion_earth",.8f);impact.impactVfxLifetime=1.2f;
 var fxRoot=PrefabUtility.LoadPrefabContents(AssetDatabase.GetAssetPath(impact.impactVFX));try{Tint(fxRoot);PrefabUtility.SaveAsPrefabAsset(fxRoot,AssetDatabase.GetAssetPath(impact.impactVFX));}finally{PrefabUtility.UnloadPrefabContents(fxRoot);}
 stun.targetMode=SkillTargetMode.SmartUnit;stun.spawnSocket=SkillSocketType.None;stun.procAnimationState="";stun.impactVFX=Vfx("MeteorStun","States/Stun",.65f);stun.impactVfxLifetime=2;
 shot.projectileImpact=new SkillProjectileImpactBlock{enabled=true,skill=impact,primaryStunTechnology=stunTech,primaryStunSeconds=2,stunPresentation=stun};
 foreach(var a in new Ability[]{shot,impact,stun}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};EditorUtility.SetDirty(a);}
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/FelSiegeBehemoth.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(x=>x&&x!=shot).Concat(new Ability[]{shot}).ToArray();u.abilityLevel=new int[u.abilities.Length];var auto=go.GetComponent<AutoAbilityUser>()??go.AddComponent<AutoAbilityUser>();var so=new SerializedObject(auto);var list=so.FindProperty("autoAbilities");list.arraySize=1;list.GetArrayElementAtIndex(0).objectReferenceValue=shot;so.ApplyModifiedPropertiesWithoutUndo();
 var animator=go.GetComponentInChildren<Animator>(true);string cp=A+"FelSiege_Skills.controller";if(!AssetDatabase.LoadAssetAtPath<AnimatorController>(cp)&&!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),cp))throw new Exception("Cannot copy controller");var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(cp);var sm=controller.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var ram=animator.GetComponentsInChildren<Transform>(true).First(t=>t.name=="SM_Veh_BatteringRam_01_Ram_01");var clip=new AnimationClip{name="FelSiege_Cast",frameRate=30};var path=AnimationUtility.CalculateTransformPath(ram,animator.transform);clip.SetCurve(path,typeof(Transform),"localPosition.z",new AnimationCurve(new Keyframe(0,ram.localPosition.z),new Keyframe(.4f,ram.localPosition.z-.2f),new Keyframe(.5f,ram.localPosition.z+.12f),new Keyframe(.8f,ram.localPosition.z)));AssetDatabase.CreateAsset(clip,A+"FelSiege_Cast.anim");cast=sm.AddState("cast");cast.motion=clip;var idle=sm.states.Select(x=>x.state).First(x=>x.name=="idleReady");var tr=cast.AddTransition(idle);tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=controller;EditorUtility.SetDirty(controller);PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}
 AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();}
 static void Tint(GameObject go){const string M=V+"Materials/";InterflowEditorUI.EnsureFolder(M);foreach(var ps in go.GetComponentsInChildren<ParticleSystem>(true)){var main=ps.main;main.startColor=new Color(.3f,1,.12f,.7f);var col=ps.colorOverLifetime;var g=new Gradient();g.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(new Color(.2f,.6f,.08f),1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(0,1)});col.enabled=true;col.color=g;}foreach(var r in go.GetComponentsInChildren<Renderer>(true)){var mats=r.sharedMaterials;for(int i=0;i<mats.Length;i++){if(!mats[i])continue;var path=M+mats[i].name.Replace("Fel_","")+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(mats[i]);mat.name="Fel_"+mats[i].name;AssetDatabase.CreateAsset(mat,path);for(int j=0;j<mat.shader.GetPropertyCount();j++)if(mat.shader.GetPropertyType(j)==UnityEngine.Rendering.ShaderPropertyType.Color){var p=mat.shader.GetPropertyName(j);var c=mat.GetColor(p);if(c.maxColorComponent>.01f)mat.SetColor(p,new Color(.3f,1,.1f,c.a));}EditorUtility.SetDirty(mat);}mats[i]=mat;}r.sharedMaterials=mats;}}
}
#endif


