#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class FelSiegeSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,a,b,ally,far,second;static CompositeSkill shot;static AutoAbilityUser auto;static Vector3 center,point;static Camera camera;static int foeOwner,phase,casts,impacts,priorCasts;static float start,speed;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static FelSiegeSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("FelSiegeSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-felsiege.txt")){File.Delete(W+"run-felsiege.txt");Begin();return;}
 if(!SessionState.GetBool("FelSiegeSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.5f){int dense=0;for(int i=0;i<100;i++)if(shot.AutoCastReady(caster,0,out var t)&&(t==a||t==b))dense++;Check(dense>50,"Native weighted cluster favors paired enemies");Check(Cast(),"Native cast accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.2f){Check(a.health==10000&&Zones().Length==0,"No damage or zone during windup");Check(caster.hasCastAnim,"Native cast animation available");phase=3;return;}
 if(phase==3&&Time.time-start>.55f){Check(Projectiles().Length==1&&Zones().Length==0,"One meteor flies before zone exists");Capture("felsiege-flight.png");phase=4;return;}
 if(phase==4&&Time.time-start>1.6f){Check(impacts==1&&Zones().Length==1,"Exactly one zone at impact");Check(Vector2.Distance(new Vector2(Zones()[0].transform.position.x,Zones()[0].transform.position.z),new Vector2(point.x,point.z))<.1f,"Zone centered on hit");Check(Mathf.Abs(Zones()[0].transform.position.y-point.y)<.1f,"Zone is on ground rather than target chest");Check(Mathf.Abs(b.armor-15)<.01f,"Zone reduces armor twenty-five percent");Check(b.attackSpeed==speed,"Locked specialization leaves attack speed unchanged");Check(!a.stunned&&!b.stunned,"Locked shard leaves enemies unstunned");Check(!Cast(),"Cooldown blocks repeated cast");Check(ally.health==10000&&far.health==10000&&ally.armor==20,"Allies and outside enemy excluded");Capture("felsiege-zone.png");phase=5;return;}
 if(phase==5&&Time.time-start>8){Check(Mathf.Abs(b.health-9928)<.2f,"Zone deals exactly seventy-two damage in six seconds");Check(Mathf.Abs(a.health-9868)<.2f,"Primary takes sixty hit damage plus zone");Check(Zones().Length==0&&Mathf.Abs(b.armor-20)<.01f,"Zone and armor effect expire");Check(caster.unitState!=UnitStates.AbilityCasting,"Animator returns from casting");TechnologyManager.instance.UnlockTech(AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Orki_T4_B1.asset"),0);ResetCD();Cast();phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>1.6f){Check(Mathf.Abs(b.attackSpeed-speed/.8f)<.001f,"Defense breaker reduces attack speed exactly twenty percent");b.agent.Warp(point+Vector3.right*5);phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>.6f){Check(Mathf.Abs(b.armor-20)<.01f&&Mathf.Abs(b.attackSpeed-speed)<.001f,"Leaving zone clears both debuffs");b.agent.Warp(point+Vector3.right*.7f);phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>.5f){Check(Mathf.Abs(b.attackSpeed-speed/.8f)<.001f,"Reentering reapplies debuff");TechnologyManager.instance.LockTech(AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Orki_T4_B1.asset"),0);phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>6){Check(Mathf.Abs(b.attackSpeed-speed)<.001f,"Lock and expiration restore speed");TechnologyManager.instance.UnlockTech(shot.projectileImpact.primaryStunTechnology,0);ResetCD();Cast();phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>1.5f){Check(a.stunned&&!b.stunned,"Shard stuns only primary for two seconds");Capture("felsiege-stun.png");phase=11;return;}
 if(phase==11&&Time.time-start>4){Check(!a.stunned,"Shard stun ends");priorCasts=casts;auto.enabled=true;phase=12;start=Time.time;return;}
 if(phase==12&&Time.time-start>11){auto.enabled=false;Check(casts>priorCasts,"Autocast reuses native cooldown");phase=13;start=Time.time;return;}
 if(phase==13&&Time.time-start>8){caster.Hold();caster.agent.Warp(center);second=Spawn(center+Vector3.left*4,0,true);int n=impacts;shot.Use(caster,0,0,a);shot.Use(second,0,0,a);priorCasts=n;phase=14;start=Time.time;return;}
 if(phase==14&&Time.time-start>1.8f){Check(impacts-priorCasts==2&&Zones().Length==2,"Two machines produce independent simultaneous zones: impacts="+(impacts-priorCasts)+" zones="+Zones().Length);phase=15;start=Time.time;return;}
 if(phase==15&&Time.time-start>7){priorCasts=impacts;shot.Use(second,0,0,a);second.Die(-1,null,false);phase=16;start=Time.time;return;}
 if(phase==16&&Time.time-start>1.6f){Check(impacts==priorCasts+1&&Zones().Length==1,"Launched meteor finishes after caster death");phase=17;start=Time.time;return;}
 if(phase==17&&Time.time-start>7){shot.Use(caster,0,0,a);a.Die(-1,null,false);phase=18;start=Time.time;return;}
 if(phase==18&&Time.time-start>2){Check(Projectiles().Length==0,"Target death in flight safely removes missile");foreach(var u in new[]{b,far})u.Die(-1,null,false);Check(!shot.AutoCastReady(caster,0,out _),"No target prevents automatic casting");b=Spawn(point,foeOwner);ResetCD();Check(caster.UseAbilityItem(Array.IndexOf(caster.abilities,shot),false,b,Vector3.zero),"Cast starts before target dies");b.Die(-1,null,false);phase=19;start=Time.time;return;}
 if(phase==19&&Time.time-start>2){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death during windup does not lock state");caster.Die(-1,null,false);Check(!Cast(),"Dead caster cannot cast");phase=20;start=Time.time;return;}
 if(phase==20&&Time.time-start>7){Check(Zones().Length==0&&Projectiles().Length==0,"All zones and missiles cleaned up");Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("FelMeteorImpact")||v.name.StartsWith("MeteorStun")),"Impact and stun VFX cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static GroundDamageZone[] Zones()=>UnityEngine.Object.FindObjectsByType<GroundDamageZone>(FindObjectsSortMode.None).Where(z=>z.name.StartsWith("FelScorchedGround")).ToArray();
 static Projectile[] Projectiles()=>UnityEngine.Object.FindObjectsByType<Projectile>(FindObjectsSortMode.None).Where(p=>p.name.StartsWith("FelSiege_Meteor")).ToArray();
 static bool Cast()=>caster.UseAbilityItem(Array.IndexOf(caster.abilities,shot),false,a,Vector3.zero);
 static void ResetCD()=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,shot),false);
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"felsiege-runtime-results.txt",results);}
 static Unit Spawn(Vector3 p,int owner,bool siege=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(siege?"Orcs/FelSiegeBehemoth":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.SetHP(10000);u.armor=20;u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;point=center+Vector3.forward*6;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn(center,0,true);a=Spawn(point,foeOwner);b=Spawn(point+Vector3.right*.7f,foeOwner);ally=Spawn(point+Vector3.left*.8f,0);far=Spawn(point+Vector3.right*4,foeOwner);speed=b.attackSpeed;
 shot=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="FelSiege_FelVolley");auto=caster.GetComponent<AutoAbilityUser>();caster.LookAtInstant(new Vector2(point.x,point.z));Check((int)caster.attackType==0,"Original melee attack retained");Check(GameManager.instance.gameProjectiles.ContainsKey(shot.projectilePrefab.id),"Meteor registered by native projectile ID");
 SkillPresentationEvents.SkillFired+=(u,id,l,t,pt)=>{if(id==shot.id)casts++;if(id==shot.projectileImpact.skill.id)impacts++;};
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(8,10,-6);camera.transform.LookAt(center+Vector3.forward*3);camera.orthographic=true;camera.orthographicSize=6;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("FelSiegeSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"felsiege-runtime-results.txt",results);File.WriteAllLines(W+"felsiege-runtime-errors.txt",errors);File.WriteAllText(W+"felsiege-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("FelSiegeSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


