#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class FelStalkerSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,primary,front,ally;static CompositePassive burn;static ChargeAttack charge;static DamageType physical,pure;static Vector3 center;static Camera camera;static int foeOwner,phase,hits;static float start,speed,observedStun;static Unit observedTarget;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static FelStalkerSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("FelStalkerSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-felstalker.txt")){File.Delete(W+"run-felstalker.txt");Begin();return;}
 if(!SessionState.GetBool("FelStalkerSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.6f){Mechanics();phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.4f){Check(!AbsorbShield.IsActiveOn(caster)&&!caster.effectors.Any(h=>h.effector==burn.manaBurn.shieldPresentation),"Depleted shield clears native status and visual");TechnologyManager.instance.UnlockTech(burn.manaBurn.shieldTechnology,0);primary.SetMP(100);Hit(primary);phase=21;start=Time.time;return;}
 if(phase==21&&Time.time-start>.4f){Check(caster.effectors.Any(h=>h.effector==burn.manaBurn.shieldPresentation),"Live shield has persistent native visual");Capture("felstalker-shield.png");caster.GetDamage(10,pure,foeOwner,primary,false,out _);TechnologyManager.instance.LockTech(burn.manaBurn.shieldTechnology,0);PrepareCharge(false);phase=3;start=Time.time;return;}
 if(phase==3&&Time.time-start>.18f){Check(Active()&&caster.target==primary,"Charge chooses farther mage before nearer fighter");Check(caster.moveSpeed>speed,"Charge increases native movement speed");Capture("felstalker-charge.png");phase=4;return;}
 if(phase==4&&(hits>0||Time.time-start>5)){Check(hits>0&&observedTarget==primary,"Native charge reaches chosen mage and attacks");Check(observedStun==0,"Locked stun specialization leaves charge hit unstunned");Check(primary.mana<100,"Native animated attack burns mana");PrepareCharge(true);phase=5;start=Time.time;return;}
 if(phase==5&&(hits>0||Time.time-start>5)){Check(hits>0&&observedStun>1.3f,"Unlocked charge first hit stuns for1.5 seconds");Check(!Active()&&Mathf.Abs(caster.moveSpeed-speed)<.001f,"Impact removes charge speed without drift");Capture("felstalker-stun.png");caster.canAttack=false;caster.Hold();hits=0;phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>.5f){Check(Cooldown()>6,"Charge retains cooldown after impact");Warp(caster,center);Warp(primary,center+Vector3.forward*6);caster.canAttack=true;phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>.4f){Check(!Active(),"Charge cannot restart during cooldown");phase=8;return;}
 if(phase==8&&(hits>0||Time.time-start>11)){Check(hits>0&&observedStun>1.3f,"Charge automatically repeats after native cooldown");caster.canAttack=false;caster.Hold();charge.Lock(caster,0,0);primary.Die(-1,null,false);front.Die(-1,null,false);primary=Spawn(center+Vector3.forward*6,foeOwner);primary.unitCategory=Unit.UnitCategory.Mage;Warp(caster,center);charge.Unlock(caster,0,0);caster.canAttack=true;phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>.18f){Check(Active(),"Fresh charge started for target-death case");primary.Die(-1,null,false);phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>.35f){Check(!Active()&&Mathf.Abs(caster.moveSpeed-speed)<.001f,"Target death cancels charge and speed immediately");charge.Lock(caster,0,0);charge.Unlock(caster,0,0);phase=11;start=Time.time;return;}
 if(phase==11&&Time.time-start>.3f){Check(!Active(),"No enemy target means no charge");primary=Spawn(center+Vector3.forward*6,foeOwner);Warp(caster,center);phase=12;start=Time.time;return;}
 if(phase==12&&Time.time-start>.18f){Check(Active(),"Charge starts when enemy appears");TechnologyManager.instance.UnlockTech(burn.manaBurn.shieldTechnology,0);Hit(primary);Check(AbsorbShield.IsActiveOn(caster),"Caster death case includes active mana shield");caster.Die(-1,null,false);primary.Die(-1,null,false);phase=13;start=Time.time;return;}
 if(phase==13&&Time.time-start>2){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("FelCharge")||v.name.StartsWith("FelMana")),"All charge, mana and shield visuals clear on death");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("FelStalkerSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static Unit Spawn(Vector3 p,int owner,bool stalker=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(stalker?"Orcs/FelStalker":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=1000;u.SetHP(1000);u.maxMana=100;u.SetMP(100);u.armor=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
 caster=Spawn(center,0,true);primary=Spawn(center+Vector3.forward*6,foeOwner);front=Spawn(center+new Vector3(-2,0,4),foeOwner);ally=Spawn(center+Vector3.right*3,0);
 burn=(CompositePassive)caster.abilities.First(a=>a.name=="FelStalker_ManaDevour");charge=(ChargeAttack)caster.abilities.First(a=>a.name=="FelStalker_BacklineCharge");charge.Lock(caster,0,0);speed=caster.moveSpeed;pure=burn.manaBurn.damageType;physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
 camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,8,-5);camera.transform.LookAt(center+Vector3.forward*2);camera.orthographic=true;camera.orthographicSize=5.5f;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"felstalker-runtime-results.txt",results);}
 static void Hit(Unit target,bool direct=true){caster.DealDamage(target,1,physical,direct,target.transform.position);}
 static void Mechanics(){Check(!caster.abilityLocked[Array.IndexOf(caster.abilities,burn)],"Mana burn base passive unlocked");primary.armor=30;float hp=primary.health;primary.GetDamage(1,physical,0,caster,false,out float basic);primary.SetHP(hp);Hit(primary);Check(Mathf.Abs(primary.health-(hp-basic-15))<.001f,"Burn adds15 pure damage regardless of30 armor");Check(primary.mana==85,"Attack removes exactly15 mana");Check(!AbsorbShield.IsActiveOn(caster),"Locked specialization grants no shield");primary.SetMP(4);hp=primary.health;Hit(primary);Check(primary.mana==0&&Mathf.Abs(primary.health-(hp-basic-4))<.001f,"Partial mana gives only actual4 bonus damage");hp=primary.health;Hit(primary);Check(Mathf.Abs(primary.health-(hp-basic))<.001f,"Zero mana gives no bonus damage");primary.SetMP(100);Hit(primary,false);Check(primary.mana==100,"Indirect damage does not burn mana");burn.Unlock(caster,0,0);Hit(primary);Check(primary.mana==85,"Repeated unlock does not duplicate burn");burn.Lock(caster,0,0);Hit(primary);Check(primary.mana==85,"Passive lock removes burn callback");burn.Unlock(caster,0,0);
 TechnologyManager.instance.UnlockTech(burn.manaBurn.shieldTechnology,0);primary.SetMP(100);Hit(primary);Hit(primary);Check(AbsorbShield.IsActiveOn(caster),"Burn specialization creates absorb shield");caster.SetHP(500);caster.GetDamage(20,pure,foeOwner,primary,false,out _);Check(Mathf.Abs(caster.health-495)<.001f,"Two15 burns accumulate15 shield and absorb that amount");primary.SetMP(4);Hit(primary);caster.GetDamage(3,pure,foeOwner,primary,false,out _);Check(Mathf.Abs(caster.health-494)<.001f,"Partial4 mana adds exactly2 shield");primary.SetMP(0);Hit(primary);Check(!AbsorbShield.IsActiveOn(caster),"Empty mana does not refresh depleted shield");
 TechnologyManager.instance.LockTech(burn.manaBurn.shieldTechnology,0);primary.SetMP(100);Hit(primary);Check(!AbsorbShield.IsActiveOn(caster),"Locked shield technology stops future shield generation");var other=Spawn(center+Vector3.left*3,0,true);var c=(ChargeAttack)other.abilities.First(a=>a is ChargeAttack);c.Lock(other,0,0);primary.SetMP(20);Hit(primary);other.DealDamage(primary,1,physical,true,primary.transform.position);Check(primary.mana==0,"Two casters consume only remaining shared mana");other.Die(-1,null,false);primary.armor=0;}
 static void Warp(Unit u,Vector3 p){u.Hold();u.GetComponent<NavMeshAgent>().Warp(p);}
 static object State()=>((IDictionary)typeof(ChargeAttack).GetField("states",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(charge))[caster];
 static bool Active(){var s=State();return s!=null&&(bool)s.GetType().GetField("active").GetValue(s);}
 static float Cooldown(){var s=State();return s==null?0:(float)s.GetType().GetField("cooldownLeft").GetValue(s);}
 static void PrepareCharge(bool stun){caster.canAttack=false;caster.Hold();charge.Lock(caster,0,0);if(stun)TechnologyManager.instance.UnlockTech(charge.stunRequiredTech,0);Warp(caster,center);Warp(primary,center+Vector3.forward*6);primary.unitCategory=Unit.UnitCategory.Mage;primary.SetMP(100);primary.SetHP(1000);hits=0;observedStun=-1;charge.Unlock(caster,0,0);caster.OnAfterDamageDealCallbacks.RemoveAll(c=>c.Callback==Observe);caster.OnAfterDamageDealCallbacks.Add(new AfterDamageDealCallback{Callback=Observe});caster.canAttack=true;}
 static void Observe(Unit t,Vector3 pos,Effector[] e,float damage,bool direct,DamageType type,Unit source,Projectile proj,int owner,int level){if(direct&&source==caster){hits++;observedTarget=t;observedStun=t?t.stunTime:0;}}
 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"felstalker-runtime-results.txt",results);File.WriteAllLines(W+"felstalker-runtime-errors.txt",errors);File.WriteAllText(W+"felstalker-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("FelStalkerSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif
