#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class FelStalkerSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/FelStalker/";
 const string V="Assets/VFX/Skills/FelStalker/";
 const string A="Assets/Models/Units/Orcs/FelStalker/Animations/";
 static FelStalkerSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-felstalker.txt"))return;try{File.Delete(W+"configure-felstalker.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"felstalker-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"felstalker-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name,string label,VFXReferencer visual){const string E="Assets/Resources/Effectors/Roster/Orcs/FelStalker/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}e.displayName=label;e.permanent=true;e.VFX=visual;EditorUtility.SetDirty(e);return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);
 var burn=Asset<CompositePassive>("FelStalker_ManaDevour");var charge=Asset<ChargeAttack>("FelStalker_BacklineCharge");var hit=Asset<CompositeSkill>("FelStalker_ManaImpact");var impact=Asset<CompositeSkill>("FelStalker_ChargeImpact");var stun=Asset<CompositeSkill>("FelStalker_StunVisual");stun.targetMode=SkillTargetMode.SmartUnit;stun.procAnimationState="";stun.spawnSocket=SkillSocketType.None;stun.impactVFX=Vfx("FelChargeStun","States/Stun",.5f);stun.impactVfxLifetime=1.5f;
 var pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");if(!pure){pure=ScriptableObject.CreateInstance<DamageType>();pure.id=InterflowEditorUI.NextFreeId("t:DamageType",o=>((DamageType)o).id);pure.displayName="Чистый";pure.ignoresArmor=true;pure.damageEffectivness=Array.Empty<DamageToArmor>();AssetDatabase.CreateAsset(pure,"Assets/Resources/DamageTypes/Pure.asset");}
 hit.targetMode=SkillTargetMode.SmartUnit;hit.procAnimationState="";hit.spawnSocket=SkillSocketType.None;hit.impactVFX=Vfx("FelManaImpact","Slash/Hit_magic",.35f);hit.impactVfxLifetime=.5f;
 impact.targetMode=SkillTargetMode.SmartUnit;impact.procAnimationState="";impact.spawnSocket=SkillSocketType.None;impact.impactVFX=Vfx("FelChargeImpact","Slash/Hit_stone",.5f);impact.impactVfxLifetime=.6f;
 var shield=Effect("FelStalker_ManaShield","Жажда Магии",Vfx("FelManaShield","Shields/Shield_wind",.5f,true));
 var trail=Effect("FelStalker_Charging","Прорыв в тыл",Vfx("FelChargeAura","States/Aura_acceleration",.45f,true));
 foreach(var v in new[]{shield.VFX,trail.VFX,hit.impactVFX,impact.impactVFX,stun.impactVFX}){var path=AssetDatabase.GetAssetPath(v);var root=PrefabUtility.LoadPrefabContents(path);try{root.transform.GetChild(0).localPosition=Vector3.up*(v==shield.VFX?.55f:v==trail.VFX?.1f:v==stun.impactVFX?1.6f:.7f);foreach(var ps in root.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.startDelay=0;m.maxParticles=Mathf.Min(m.maxParticles,30);if(v==shield.VFX)m.startColor=new Color(.6f,1,.65f,.35f);}PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
 burn.abilityName=new[]{"Пожирание Маны"};burn.description=new[]{"Атаки выжигают до 15 маны и наносят столько же чистого урона. Жажда Магии превращает 50% фактически выжженной маны в накапливающийся щит до поглощения."};burn.manaBurn=new PassiveManaBurnBlock{enabled=true,amount=15,damageType=pure,shieldTechnology=Tech("Orki_T2_B1","Жажда Магии"),shieldFraction=.5f,shieldDuration=0,shieldPresentation=shield,hitPresentation=hit};
 charge.abilityName=new[]{"Прорыв в тыл"};charge.description=new[]{"Разгоняется к магу в тылу; при отсутствии мага — к ближайшему противнику. Оскверненный Прорыв: первый удар после разгона оглушает на 1.5 с. Альфа: откат8с, поиск8м, минимум3м, скорость+80%, разгон3с."};charge.cooldown=new[]{8f};charge.castRange=new[]{8f};charge.minChargeDistance=3;charge.chargeDuration=3;charge.speedBonusPercent=.8f;charge.impactDamageMultiplier=new[]{1f};charge.impactStunSeconds=1.5f;charge.stunOnlySelectedCategory=false;charge.stunRequiredTech=Tech("Orki_T2_B2","Оскверненный Прорыв");charge.preferredCategories=new[]{Unit.UnitCategory.Mage};charge.unitSelector=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isWater=true};charge.chargePresentation=trail;charge.impactPresentation=impact;charge.stunPresentation=stun;
 const string M="Assets/VFX/Skills/FelStalker/Materials/";InterflowEditorUI.EnsureFolder(M);var trailPath=AssetDatabase.GetAssetPath(trail.VFX);var trailRoot=PrefabUtility.LoadPrefabContents(trailPath);try{foreach(var renderer in trailRoot.GetComponentsInChildren<Renderer>(true)){var mats=renderer.sharedMaterials;for(int i=0;i<mats.Length;i++){var source=mats[i];if(!source)continue;var path=M+source.name.Replace("Fel_","")+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(source);mat.name="Fel_"+source.name;AssetDatabase.CreateAsset(mat,path);for(int j=0;j<mat.shader.GetPropertyCount();j++){if(mat.shader.GetPropertyType(j)!=UnityEngine.Rendering.ShaderPropertyType.Color)continue;var property=mat.shader.GetPropertyName(j);var old=mat.GetColor(property);if(old.maxColorComponent<.01f)continue;mat.SetColor(property,new Color(.25f,.8f,.18f,old.a*.65f));}EditorUtility.SetDirty(mat);}mats[i]=mat;}renderer.sharedMaterials=mats;}PrefabUtility.SaveAsPrefabAsset(trailRoot,trailPath);}finally{PrefabUtility.UnloadPrefabContents(trailRoot);}
 var shieldPath=AssetDatabase.GetAssetPath(shield.VFX);var shieldRoot=PrefabUtility.LoadPrefabContents(shieldPath);try{foreach(var renderer in shieldRoot.GetComponentsInChildren<Renderer>(true)){var mats=renderer.sharedMaterials;for(int i=0;i<mats.Length;i++){var source=mats[i];if(!source)continue;var path=M+"Shield_"+source.name.Replace("Shield_","")+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(source);mat.name="Shield_"+source.name;AssetDatabase.CreateAsset(mat,path);for(int j=0;j<mat.shader.GetPropertyCount();j++){if(mat.shader.GetPropertyType(j)!=UnityEngine.Rendering.ShaderPropertyType.Color)continue;var property=mat.shader.GetPropertyName(j);var old=mat.GetColor(property);if(old.maxColorComponent<.01f)continue;mat.SetColor(property,new Color(.3f,.8f,.35f,old.a*.3f));}EditorUtility.SetDirty(mat);}mats[i]=mat;}renderer.sharedMaterials=mats;}PrefabUtility.SaveAsPrefabAsset(shieldRoot,shieldPath);}finally{PrefabUtility.UnloadPrefabContents(shieldRoot);}
 foreach(var a in new Ability[]{burn,charge,hit,impact,stun}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_stat_damage.png")};EditorUtility.SetDirty(a);}
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/FelStalker.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=burn&&a!=charge).Concat(new Ability[]{burn,charge}).ToArray();u.abilityLevel=new int[u.abilities.Length];PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
