#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class FelWarlockSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/FelWarlock/";
 const string V="Assets/VFX/Skills/FelWarlock/";
 const string A="Assets/Models/Units/Orcs/FelWarlock/Animations/";
 static FelWarlockSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-felwarlock.txt"))return;try{File.Delete(W+"configure-felwarlock.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"felwarlock-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"felwarlock-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name){const string E="Assets/Resources/Effectors/Roster/Orcs/FelWarlock/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var link=Asset<CompositeSkill>("FelWarlock_FelLink");var passive=Asset<CompositePassive>("FelWarlock_SacrificialCasting");var rupture=Asset<CompositeSkill>("FelWarlock_SoulRuptureVisual");
 var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");var pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");
 var material=AssetDatabase.LoadAssetAtPath<Material>(V+"FelChain.mat");if(!material){material=new Material(AssetDatabase.LoadAssetAtPath<Material>("Assets/VFX/Materials/LaserBeam.mat"));material.name="FelChain";if(material.HasProperty("_BaseColor"))material.SetColor("_BaseColor",new Color(.2f,.85f,.08f,.8f));if(material.HasProperty("_Color"))material.SetColor("_Color",new Color(.2f,.85f,.08f,.8f));AssetDatabase.CreateAsset(material,V+"FelChain.mat");}
 link.abilityName=new[]{"Скверно-Связь"};link.description=new[]{"Связывает до 3 врагов на 5с. 40% полученного одним урона копируется остальным. Разрыв Души: смерть связанной цели наносит остальным магический урон (альфа:40). Альфа: базовый CD10с, с пассивкой8с, радиус3м."};link.targetMode=SkillTargetMode.SmartPoint;link.targetStrategy=SkillTargetStrategy.Cluster;link.unitSelector=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isWater=true,isAir=true};link.maxTargets=3;link.radius=new[]{3f};link.castRange=new[]{9f};link.castTime=new[]{.6f};link.cooldown=new[]{10f};link.manaCost=new[]{0f};link.duration=new[]{0f};link.procAnimationState="";link.spawnSocket=SkillSocketType.RightHand;link.castVFX=Vfx("FelLinkCast","Range_attack/Hit_dark_magic",.3f);link.castVfxLifetime=.7f;
 rupture.targetMode=SkillTargetMode.SmartUnit;rupture.procAnimationState="";rupture.spawnSocket=SkillSocketType.None;rupture.impactVFX=Vfx("FelSoulRupture","Slash/Hit_magic",.55f);rupture.impactVfxLifetime=.7f;
 link.damageLink=new SkillDamageLinkBlock{enabled=true,duration=5,sharedFraction=.4f,sharedDamageType=pure,deathBurstTechnology=Tech("Orki_T3_B1","Разрыв Души"),deathBurstDamage=40,deathBurstDamageType=magic,deathPresentation=rupture,chainMaterial=material};
 passive.abilityName=new[]{"Жертвенное колдовство"};passive.description=new[]{"Каждый каст стоит 5% текущего здоровья; откат заклинаний уменьшен на20%. Кровавый Ритуал: следующий каст усиливается на25% за каждый процент максимального HP, потраченный предыдущим кастом. Усиление применяется к передаваемому цепями урону и Разрыву Души."};passive.spellCast=new PassiveSpellCastBlock{enabled=true,currentHpCost=.05f,cooldownMultiplier=.8f,ritualTechnology=Tech("Orki_T3_B2","Кровавый Ритуал"),nextDamagePerHpPercent=.25f};

 const string M=V+"Materials/";InterflowEditorUI.EnsureFolder(M);foreach(var fx in new[]{link.castVFX,rupture.impactVFX}){var path=AssetDatabase.GetAssetPath(fx);var root=PrefabUtility.LoadPrefabContents(path);try{foreach(var ps in root.GetComponentsInChildren<ParticleSystem>(true)){var main=ps.main;main.startDelay=0;main.maxParticles=Mathf.Min(20,main.maxParticles);main.startColor=new Color(.25f,1,.12f,1);var color=ps.colorOverLifetime;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(new Color(.3f,.8f,.1f),1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(1,.5f),new GradientAlphaKey(0,1)});color.enabled=true;color.color=gradient;}foreach(var renderer in root.GetComponentsInChildren<Renderer>(true)){var mats=renderer.sharedMaterials;for(int i=0;i<mats.Length;i++){var source=mats[i];if(!source)continue;var mp=M+source.name.Replace("Fel_","")+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(mp);if(!mat){mat=new Material(source);mat.name="Fel_"+source.name;AssetDatabase.CreateAsset(mat,mp);for(int j=0;j<mat.shader.GetPropertyCount();j++){if(mat.shader.GetPropertyType(j)!=UnityEngine.Rendering.ShaderPropertyType.Color)continue;var prop=mat.shader.GetPropertyName(j);var old=mat.GetColor(prop);if(old.maxColorComponent>.01f)mat.SetColor(prop,new Color(.2f,1,.1f,old.a));}EditorUtility.SetDirty(mat);}mats[i]=mat;}renderer.sharedMaterials=mats;}PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
 foreach(var ability in new Ability[]{link,passive,rupture}){ability.maxLevels=1;ability.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};EditorUtility.SetDirty(ability);}
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/FelWarlock.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(x=>x&&x!=link&&x!=passive).Concat(new Ability[]{passive,link}).ToArray();u.abilityLevel=new int[u.abilities.Length];var auto=go.GetComponent<AutoAbilityUser>()??go.AddComponent<AutoAbilityUser>();var so=new SerializedObject(auto);var list=so.FindProperty("autoAbilities");list.arraySize=1;list.GetArrayElementAtIndex(0).objectReferenceValue=link;so.ApplyModifiedPropertiesWithoutUndo();
 var animator=go.GetComponentInChildren<Animator>(true);var sockets=go.GetComponent<CharacterSockets>()??go.AddComponent<CharacterSockets>();var hand=animator.isHuman?animator.GetBoneTransform(HumanBodyBones.RightHand):go.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name=="Hand_R"||t.name=="RightHand"||t.name=="hand_r");if(!hand)throw new Exception("Missing right hand bone");var socketData=new SerializedObject(sockets);socketData.FindProperty("rightHand").objectReferenceValue=hand;socketData.ApplyModifiedPropertiesWithoutUndo();
string controllerPath=A+"FelWarlock_Skills.controller";var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);if(!controller){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),controllerPath))throw new Exception("Cannot copy caster animator");controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);}var sm=controller.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");var clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);clip.name="FelWarlock_Cast";AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);AssetDatabase.CreateAsset(clip,A+"FelWarlock_Cast.anim");cast=sm.AddState("cast");cast.motion=clip;cast.speed=clip.length/.7f;var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=controller;EditorUtility.SetDirty(controller);File.WriteAllLines(W+"felwarlock-animation.txt",sm.states.Select(x=>x.state.name+" | "+(x.state.motion?x.state.motion.name:"none")));PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
