#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class FelWarlockSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,a,b,c,ally,outside;static CompositeSkill link;static CompositePassive passive;static DamageType pure,physical;static AutoAbilityUser auto;static Vector3 center;static Camera camera;static int foeOwner,phase,casts,castsBeforeAuto;static float start;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static FelWarlockSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("FelWarlockSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-felwarlock.txt")){File.Delete(W+"run-felwarlock.txt");Begin();return;}
 if(!SessionState.GetBool("FelWarlockSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.5f){Check(Cast(),"Native unit accepts Fel Link cast");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.2f){Check(caster.health==1000&&Groups()==0,"No cost or link before cast animation finishes");Check(caster.hasCastAnim,"Native cast animation discovered");Capture("felwarlock-casting.png");phase=3;return;}
 if(phase==3&&Time.time-start>1){Check(Groups()==1&&UnityEngine.Object.FindFirstObjectByType<DamageLinkGroup>().MemberCount==3,"Native skill creates one group of three enemies");Check(Mathf.Abs(caster.health-950)<.01f,"Cast costs five percent current health");Check(caster.GetAbilityCooldown(Array.IndexOf(caster.abilities,link),false)>6&&caster.GetAbilityCooldown(Array.IndexOf(caster.abilities,link),false)<8,"Passive reduces native ten second cooldown to eight");Check(!Cast(),"Cooldown rejects repeat cast");ShareTests();Capture("felwarlock-link.png");phase=4;start=Time.time;return;}
 if(phase==4&&Time.time-start>5.5f){Check(Groups()==0,"Link ends after five seconds");Check(!UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None).Any(x=>x.GetType().Name=="DamageLinkView"),"Chain presentation ends with link");float hp=b.health;a.GetDamage(50,pure,0,caster,false,out _);Check(b.health==hp,"Expired link no longer shares damage");Check(caster.unitState!=UnitStates.AbilityCasting,"Caster leaves animation state");RitualTests();DeathTests();phase=41;start=Time.time;return;}
 if(phase==41&&Time.time-start>.2f){Capture("felwarlock-rupture.png");castsBeforeAuto=casts;auto.enabled=true;phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>10){auto.enabled=false;Check(casts>castsBeforeAuto,"Autocast repeats after cooldown");OverlapTests();foreach(var u in new[]{a,b,c,outside})if(u&&!u.dead)u.Die(-1,null,false);Check(!link.AutoCastReady(caster,0,out _),"No enemy prevents autocast");float hp=caster.health;link.Use(caster,0,0);Check(caster.health==hp,"No selected enemy consumes no health");a=Spawn(center+Vector3.forward*3,foeOwner);b=Spawn(center+new Vector3(1,0,3),foeOwner);c=Spawn(center+new Vector3(-1,0,3),foeOwner);ResetCD();Check(Cast(),"Cast begins before targets die");a.Die(-1,null,false);b.Die(-1,null,false);c.Die(-1,null,false);phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>1){Check(Groups()==0&&caster.unitState!=UnitStates.AbilityCasting,"Targets die during cast without stuck state");a=Spawn(center+Vector3.forward*3,foeOwner);b=Spawn(center+new Vector3(1,0,3),foeOwner);c=Spawn(center+new Vector3(-1,0,3),foeOwner);link.Use(caster,0,0,a.transform.position);Check(Groups()==1,"Link can be reused after interrupted target case");caster.Die(-1,null,false);Check(Groups()==0,"Caster death ends active link");phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>1.5f){Check(!UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None).Any(x=>x.GetType().Name=="DamageLinkView"),"Caster death cleans all chains");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("FelWarlockSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static Unit Spawn(Vector3 p,int owner,bool warlock=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(warlock?"Orcs/FelWarlock":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=1000;u.SetHP(1000);u.armor=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
 caster=Spawn(center,0,true);a=Spawn(center+Vector3.forward*3,foeOwner);b=Spawn(center+new Vector3(1,0,3),foeOwner);c=Spawn(center+new Vector3(-1,0,3),foeOwner);ally=Spawn(center+new Vector3(0,0,2),0);outside=Spawn(center+Vector3.forward*8,foeOwner);
 link=(CompositeSkill)caster.abilities.First(x=>x.name=="FelWarlock_FelLink");passive=(CompositePassive)caster.abilities.First(x=>x.name=="FelWarlock_SacrificialCasting");auto=caster.GetComponent<AutoAbilityUser>();pure=link.damageLink.sharedDamageType;physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");
 SkillPresentationEvents.SkillFired+=(u,id,l,t,pt)=>{if(u==caster&&id==link.id)casts++;};
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(6,7,-5);camera.transform.LookAt(center+Vector3.forward*2);camera.orthographic=true;camera.orthographicSize=4.5f;}
 static int Groups()=>UnityEngine.Object.FindObjectsByType<DamageLinkGroup>(FindObjectsSortMode.None).Count(g=>g.MemberCount>0);
 static void Clear(){foreach(var g in UnityEngine.Object.FindObjectsByType<DamageLinkGroup>(FindObjectsSortMode.None))g.End();}
 static void ResetHP(){foreach(var u in new[]{a,b,c}){u.SetHP(1000);u.armor=0;}}
 static bool Cast()=>caster.UseAbilityItem(Array.IndexOf(caster.abilities,link),false,null,a.transform.position);
 static void ResetCD()=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,link),false);
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"felwarlock-runtime-results.txt",results);}
 static void ShareTests(){a.GetDamage(100,pure,0,caster,false,out _);Check(a.health==900&&b.health==960&&c.health==960,"One hundred damage duplicates forty to each other enemy once");Check(ally.health==1000&&outside.health==1000,"Allies and distant enemy excluded");a.armor=20;float hp=b.health;a.GetDamage(100,physical,0,caster,true,out float actual);Check(Mathf.Abs(hp-b.health-actual*.4f)<.01f,"Copies post-armor actual damage without second armor calculation");a.armor=0;AbsorbShield.Apply(a,50,3);hp=b.health;a.GetDamage(100,pure,0,caster,false,out _);Check(Mathf.Abs(hp-b.health-20)<.01f,"Shield absorbed damage is not shared");hp=b.health;a.ChangeHP(20);Check(b.health==hp,"Healing never triggers link damage");}
 static void RitualTests(){Clear();ResetHP();caster.SetHP(1000);TechnologyManager.instance.UnlockTech(passive.spellCast.ritualTechnology,0);link.Use(caster,0,0,a.transform.position);a.GetDamage(100,pure,0,caster,false,out _);Check(b.health==960,"First ritual cast has no future boost yet");ResetHP();link.Use(caster,0,0,a.transform.position);Check(Mathf.Abs(caster.health-902.5f)<.01f,"Repeated cost uses current health");a.GetDamage(100,pure,0,caster,false,out _);Check(Mathf.Abs(b.health-910)<.01f,"Next spell gains125 percent from prior five percent max HP cost");Check(Groups()==1,"Same caster recast replaces previous link");ResetHP();link.Use(caster,0,0,a.transform.position);a.GetDamage(100,pure,0,caster,false,out _);Check(Mathf.Abs(b.health-912.5f)<.01f,"Ritual bonus consumed once and recalculated from next cost");TechnologyManager.instance.LockTech(passive.spellCast.ritualTechnology,0);Clear();ResetHP();link.Use(caster,0,0,a.transform.position);a.GetDamage(100,pure,0,caster,false,out _);Check(b.health==960,"Locking ritual removes pending bonus");passive.Lock(caster,0,0);float hp=caster.health;link.Use(caster,0,0,a.transform.position);Check(caster.health==hp&&SpellCastModifiers.Cooldown(caster)==1,"Passive lock removes cost and cooldown modifier");passive.Unlock(caster,0,0);passive.Unlock(caster,0,0);hp=caster.health;link.Use(caster,0,0,a.transform.position);Check(Mathf.Abs(caster.health-hp*.95f)<.01f&&Mathf.Abs(SpellCastModifiers.Cooldown(caster)-.8f)<.01f,"Repeated passive unlock does not duplicate modifiers");}
 static void DeathTests(){Clear();ResetHP();link.Use(caster,0,0,a.transform.position);a.SetHP(1);a.GetDamage(2,pure,0,caster,false,out _);Check(a.dead&&Mathf.Abs(b.health-999.6f)<.01f,"Lethal hit shares actual remaining health even before death");Clear();a=Spawn(center+Vector3.forward*3,foeOwner);ResetHP();TechnologyManager.instance.UnlockTech(link.damageLink.deathBurstTechnology,0);link.Use(caster,0,0,a.transform.position);a.SetHP(1);a.GetDamage(2,pure,0,caster,false,out _);Check(Mathf.Abs(b.health-959.6f)<.01f&&Mathf.Abs(c.health-959.6f)<.01f,"Unlocked death rupture damages remaining linked enemies");Clear();a=Spawn(center+Vector3.forward*3,foeOwner);ResetHP();TechnologyManager.instance.LockTech(link.damageLink.deathBurstTechnology,0);}
 static void OverlapTests(){Clear();ResetHP();var other=Spawn(center+Vector3.right*2,0,true);link.Use(caster,0,0,a.transform.position);link.Use(other,0,0,a.transform.position);Check(Groups()==2,"Two casters keep independent link groups");a.GetDamage(100,pure,0,caster,false,out _);Check(a.health==900&&b.health==920&&c.health==920,"Overlapping links each copy once without recursive feedback");other.Die(-1,null,false);Check(Groups()==1,"Caster death clears only its own group");Clear();}
 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"felwarlock-runtime-results.txt",results);File.WriteAllLines(W+"felwarlock-runtime-errors.txt",errors);File.WriteAllText(W+"felwarlock-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("FelWarlockSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif
