#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class FireAltarSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Humans/FireAltar/";
 const string V="Assets/VFX/Skills/FireAltar/";
 const string A="Assets/Models/Units/Humans/FireAltar/Animations/";
 static FireAltarSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-firealtar.txt"))return;try{File.Delete(W+"configure-firealtar.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"firealtar-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"firealtar-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}


 static UnitSelector Enemies()=>new UnitSelector(false,false,true,true,true,false,false,true,true,false,false,false);
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder("Assets/Resources/Effectors/Roster/Humans/FireAltar");
 var pool=Asset<EveryNthAttack>("FireAltar_CleansingPool");var charge=Asset<EveryNthAttack>("FireAltar_EmpoweredCharge");var poolEffect=Asset<CompositeSkill>("FireAltar_CleansingPool_Impact");var chargeEffect=Asset<CompositeSkill>("FireAltar_EmpoweredCharge_Impact");var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");
 foreach(var s in new[]{poolEffect,chargeEffect}){s.targetMode=SkillTargetMode.SmartPoint;s.targetStrategy=SkillTargetStrategy.Nearest;s.unitSelector=Enemies();s.castTime=new[]{0f};s.manaCost=new[]{0f};s.cooldown=new[]{0f};s.procAnimationState="";s.spawnSocket=SkillSocketType.None;s.maxLevels=1;}
 string zonePath=V+"CleansingGround.prefab";var zoneAsset=AssetDatabase.LoadAssetAtPath<GameObject>(zonePath);if(!zoneAsset){var root=new GameObject("CleansingGround");try{var zone=root.AddComponent<GroundDamageZone>();var data=new SerializedObject(zone);data.FindProperty("radius").floatValue=2;data.FindProperty("damagePerSecond").floatValue=12;data.FindProperty("damageType").objectReferenceValue=magic;data.FindProperty("duration").floatValue=4;var selector=data.FindProperty("targetSelector");foreach(var name in new[]{"isEnemy","isUnit","isBuilding","isGround","isWater"})selector.FindPropertyRelative(name).boolValue=true;data.ApplyModifiedPropertiesWithoutUndo();
 for(int i=0;i<5;i++){var fire=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/Fire/Fire_cartoon_gold.prefab"));fire.transform.SetParent(root.transform,false);fire.transform.localPosition=i==0?Vector3.zero:new Vector3(Mathf.Cos((i-1)*Mathf.PI/2)*1.25f,0,Mathf.Sin((i-1)*Mathf.PI/2)*1.25f);fire.transform.localScale=new Vector3(.55f,.35f,.55f);foreach(var ps in fire.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=true;m.maxParticles=16;m.startLifetime=.7f;var e=ps.emission;e.rateOverTime=8;}}
 zoneAsset=PrefabUtility.SaveAsPrefabAsset(root,zonePath);}finally{UnityEngine.Object.DestroyImmediate(root);}}
 poolEffect.radius=new[]{2f};poolEffect.groundZone=new SkillGroundZoneBlock{enabled=true,zonePrefab=zoneAsset,zoneCount=1};poolEffect.impactVFX=Vfx("PoolIgnition","Fire/Fire_explosion_earth",.6f);poolEffect.impactVfxLifetime=1f;
 chargeEffect.radius=new[]{1f};chargeEffect.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{100f},damageType=magic,targets=SkillDamageTargets.Enemies}}};chargeEffect.impactVFX=Vfx("EmpoweredImpact","Fire/Fire_explosion_air",.7f);chargeEffect.impactVfxLifetime=1.4f;
 pool.abilityName=new[]{"Очищающая Лужа"};pool.description=new[]{"Попадание оставляет область Света радиусом 2 м на 4 секунды. Враги внутри получают 12 магического урона в секунду."};charge.abilityName=new[]{"Усиленный Заряд"};charge.description=new[]{"Попадание дополнительно наносит 100 магического урона врагам в радиусе 1 м от центра взрыва."};
 foreach(var s in new[]{pool,charge}){s.everyN=1;s.maxLevels=1;s.onlyDirectAttack=true;s.onProcSkill=s==pool?poolEffect:chargeEffect;s.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};s.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/"+(s==pool?"Lyudi_T4_B1":"Lyudi_T4_B2")+".asset")}}};EditorUtility.SetDirty(s);}EditorUtility.SetDirty(poolEffect);EditorUtility.SetDirty(chargeEffect);
 string deploymentPath="Assets/Resources/Effectors/Roster/Humans/FireAltar/FireAltar_Deployment.asset";var deploy=AssetDatabase.LoadAssetAtPath<Effector>(deploymentPath);if(!deploy){deploy=ScriptableObject.CreateInstance<Effector>();deploy.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(deploy,deploymentPath);}deploy.displayName="Развертывание";deploy.description="Подготовка Алтаря к стрельбе: 1.75 секунды без движения.";deploy.duration=1.75f;deploy.VFX=Vfx("DeploymentEmbers","Fire/Fire_cartoon_gold",.45f,true);EditorUtility.SetDirty(deploy);
 var glow=PrefabUtility.LoadPrefabContents(V+"DeploymentEmbers.prefab");try{glow.transform.GetChild(0).localPosition=Vector3.up*.8f;foreach(var ps in glow.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=true;m.startDelay=0;m.maxParticles=20;var e=ps.emission;e.rateOverTime=12;}PrefabUtility.SaveAsPrefabAsset(glow,V+"DeploymentEmbers.prefab");}finally{PrefabUtility.UnloadPrefabContents(glow);}
 var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(A+"FireAltar_Alpha.controller");foreach(var name in new[]{"idle","walk","attack","building","idleReady","casting"})if(!controller.parameters.Any(p=>p.name==name))controller.AddParameter(name,AnimatorControllerParameterType.Bool);foreach(var name in new[]{"movespeed","attackspeed","blendingIndex"})if(!controller.parameters.Any(p=>p.name==name))controller.AddParameter(new AnimatorControllerParameter{name=name,type=AnimatorControllerParameterType.Float,defaultFloat=1});
 var states=controller.layers[0].stateMachine.states.Select(s=>s.state).ToArray();var idle=states.Single(s=>s.name=="idle0");var ready=states.Single(s=>s.name=="idleReady");var walk=states.Single(s=>s.name=="walk");var attack=states.Single(s=>s.name=="attack0");
 if(attack.transitions.Length==0){var t=attack.AddTransition(ready);t.hasExitTime=true;t.exitTime=1;t.duration=.05f;}
 foreach(var from in new[]{idle,ready})if(!from.transitions.Any(t=>t.destinationState==walk)){var t=from.AddTransition(walk);t.hasExitTime=false;t.duration=.05f;t.AddCondition(AnimatorConditionMode.If,0,"walk");}
 if(walk.transitions.Length==0){var t=walk.AddTransition(idle);t.hasExitTime=false;t.duration=.05f;t.AddCondition(AnimatorConditionMode.IfNot,0,"walk");}EditorUtility.SetDirty(controller);
 const string prefab="Assets/Resources/UnitPrefabs/Units/Humans/FireAltar.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=pool&&a!=charge&&AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(a))!="745d7ba2997971a49a5ae87f4199a234").Concat(new Ability[]{pool,charge}).ToArray();u.abilityLevel=new int[u.abilities.Length];var gate=go.GetComponent<WeaponDeployment>()??go.AddComponent<WeaponDeployment>();gate.seconds=1.75f;gate.deploymentVisual=deploy;PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
