#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class GurtagSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";


 static Unit caster,second,a,b,front,back,human,wolf,slaver,mage;static CompositeSkill ram,furnace,monolith;static DamageType pure,magic,physical;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start,hp,enemyHp,frontHp,speed,attackSpeed,stored;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static GurtagSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("GurtagSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-gurtag.txt")){File.Delete(W+"run-gurtag.txt");Begin();return;}
 if(!SessionState.GetBool("GurtagSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.6f){caster.SetHP(1000);enemyHp=a.health;a.DealDamage(caster,10,physical,true,caster.transform.position);Check(Mathf.Abs(enemyHp-a.health-10)<.1f,"Enemy melee receives10magic retaliation");enemyHp=a.health;a.DealDamage(caster,10,magic,false,caster.transform.position);Check(a.health==enemyHp,"No retaliation against DoT");enemyHp=back.health;back.DealDamage(caster,10,physical,true,caster.transform.position);Check(back.health==enemyHp,"No retaliation against ranged attacks");hp=human.health;human.DealDamage(caster,10,physical,true,caster.transform.position);Check(human.health==hp,"No retaliation against allies");Capture("gurtag-plating.png");enemyHp=a.health;Check(Cast(ram),"Ram button accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>1.3f){Check(caster.transform.position.z>center.z+2,"Ram moves caster forward");Check(Mathf.Abs(enemyHp-a.health-70)<.1f,"Ram40physical+30fire magic");Check(a.transform.position.z>center.z+5,"T1 infantry knocked forward2m");Check(Mathf.Abs(wolf.transform.position.z-center.z-4)<.5f,"Ram does not displace beast");Check(Mathf.Abs(b.transform.position.z-center.z-4)<.5f,"Ram does not displace high tier");Check(!Cast(ram),"Ram cooldown blocks repeat");Capture("gurtag-ram.png");Move(caster,center);Move(a,center+Vector3.forward*2);Move(b,center+Vector3.forward*12);Move(wolf,center+Vector3.right*12);caster.SetHP(1000);caster.canAttack=true;Check(Cast(furnace),"Furnace button accepted");phase=3;start=Time.time;return;}
 if(phase==3&&Time.time-start>.8f){caster.canAttack=false;Check(!caster.canMove&&SkillActionLock.Active(caster),"Furnace roots caster");Check(!Cast(monolith),"Furnace blocks concurrent cast");a.DealDamage(caster,100,physical,false,caster.transform.position);Check(Mathf.Abs(caster.health-940)<.1f,"Furnace reduces incoming damage40percent");slaver.LookAtInstant(new Vector2(caster.transform.position.x,caster.transform.position.z));var whip=slaver.abilities.OfType<CompositeSkill>().First(x=>x.name=="OrcSlaver_Whip");Check(whip.targetPrefabs.Any(p=>p.unitTypeID==caster.unitTypeID),"Slaver can target Gurtag per document");hp=caster.health;whip.Use(slaver,0,0);Check(Mathf.Abs(caster.health-hp*.85f)<.1f,"Allied Slaver drains15percent currentHP");stored=1000-caster.health;Check(Mathf.Abs(caster.GetComponent<SkillBuff>().StoredDamage-stored)<.1f,"Furnace accumulates actual damage and allied sacrifice");caster.ChangeHP(25);Check(Mathf.Abs(caster.GetComponent<SkillBuff>().StoredDamage-stored)<.1f,"Healing does not erase stored damage");enemyHp=a.health;frontHp=human.health;Capture("gurtag-furnace.png");phase=4;return;}
 if(phase==4&&Time.time-start>1.8f&&Time.time-start<2.1f)Capture("gurtag-furnace-charge.png");
 if(phase==4&&Time.time-start>4.8f){Check(Mathf.Abs(enemyHp-a.health-stored)<.2f,"Furnace detonates stored HP loss once");Check(human.health==frontHp,"Furnace explosion excludes allies");Check(caster.canMove&&!SkillActionLock.Active(caster)&&caster.GetComponents<SkillBuff>().All(buff=>buff.StoredDamage==0),"Furnace removes root and buff after4sec");caster.canAttack=false;Check(!Cast(furnace),"Furnace cooldown blocks repeat");Capture("gurtag-furnace-end.png");hp=caster.health;a.DealDamage(caster,100,physical,false,Vector3.zero);Check(Mathf.Abs(hp-caster.health-100)<.1f,"Incoming protection removed after furnace");Move(a,center+Vector3.forward*2);a.armor=0;Move(mage,center+new Vector3(1,0,1));Move(human,center+new Vector3(-1,0,1));human.SetHP(500);mage.SetHP(1000);Check(Cast(monolith),"Monolith button accepted");enemyHp=a.health;phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>2.6f){Check(a.armor<=-4&&a.armor>=-6,"Monolith stacks armor loss2persec");Check(a.health<enemyHp-20,"Monolith deals periodic fel damage");Check(mage.GetComponent<SpellCastModifiers>().HealthCostExemptions==1,"FelWarlock receives HP cost exemption");Check(!human.GetComponent<SpellCastModifiers>()||human.GetComponent<SpellCastModifiers>().HealthCostExemptions==0,"Other allies do not receive caster exemption");hp=human.health;human.DealDamage(a,100,physical,true,Vector3.zero);Check(Mathf.Abs(human.health-hp-25)<.1f,"Ally receives25percent lifesteal");hp=mage.health;using(SpellCastModifiers.Begin(mage,true)){}Check(mage.health==hp,"FelWarlock HP cast cost waived");Check(!Cast(monolith),"Monolith cooldown blocks repeat");Capture("gurtag-monolith.png");Move(human,center+Vector3.right*10);Move(mage,center+Vector3.left*10);phase=6;return;}
 if(phase==6&&Time.time-start>3.4f){Check(mage.GetComponent<SpellCastModifiers>().HealthCostExemptions==0,"Leaving zone removes HP cost exemption");hp=mage.health;using(SpellCastModifiers.Begin(mage,true)){}Check(Mathf.Abs(mage.health-hp*.95f)<.2f,"FelWarlock HP price restored outside zone");hp=human.health;human.DealDamage(a,100,physical,true,Vector3.zero);Check(human.health==hp,"Lifesteal removed outside zone");phase=7;return;}
 if(phase==7&&Time.time-start>8.8f){Check(!UnityEngine.Object.FindObjectsByType<GroundDamageZone>(FindObjectsSortMode.None).Any(z=>z.name.Contains("CinderMonolith")),"Monolith despawns after7sec");Check(Mathf.Abs(a.armor)<.1f,"Armor stacks expire after zone ends");Check(!mage.effectors.Any(h=>h.effector.name=="Gurtag_MonolithBlessing"),"No lingering monolith blessing");Reset(furnace);Check(Cast(furnace),"Furnace reusable after reset");phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>.8f){second=Spawn(center+Vector3.right*6,0,"Heroes/Orcs/Gurtag");second.SetHP(1000);furnace.Use(second,0,0);second.GetDamage(100,physical,foeOwner,a,false,out _);Check(Mathf.Abs(second.GetComponent<SkillBuff>().StoredDamage-60)<.1f,"Two Gurtags store damage independently");Check(caster.GetComponent<SkillBuff>().StoredDamage<.1f,"First Gurtag storage independent from second");enemyHp=a.health;caster.Die(-1,null,false);phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>4.6f){Check(a.health==enemyHp,"Death during furnace cancels final detonation");Check(!caster||!Cast(ram),"Dead caster cannot cast");Check(!second.GetComponent<SkillBuff>()&&second.canMove,"Second caster buff expires independently");caster=second;Move(caster,center);Reset(ram);a.Die(-1,null,false);b.Die(-1,null,false);back.Die(-1,null,false);wolf.Die(-1,null,false);Check(!Cast(ram),"No enemies rejects ram without spending cooldown");a=Spawn(center+Vector3.forward*3,foeOwner);caster.LookAtInstant(new Vector2(a.transform.position.x,a.transform.position.z));Reset(ram);Check(Cast(ram),"Ram reusable");a.Die(-1,null,false);phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>1.5f){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death releases cast animator");Check(!caster.GetComponent<SkillTravel>()||!caster.GetComponent<SkillTravel>().Running,"No stuck dash after target death");var animator=caster.GetComponentInChildren<Animator>();Check(!animator.GetCurrentAnimatorStateInfo(0).IsName("brace"),"Brace presentation returns to normal");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Move(Unit u,Vector3 p){if(u)Knockback.MoveTo(u,p,false);}
 static bool Cast(CompositeSkill s){Register();return caster&&caster.UseAbilityItem(Array.IndexOf(caster.abilities,s),false,null,Vector3.zero,true);}
 static void Reset(CompositeSkill s)=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,s),false);
 static void Register(){var mm=MatchManager.instance;var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;((TeamWaveConfig)typeof(MatchManager).GetField("teamA",flags).GetValue(mm)).ownerPlayer=0;((TeamWaveConfig)typeof(MatchManager).GetField("teamB",flags).GetValue(mm)).ownerPlayer=foeOwner;var lists=(List<Unit>[])typeof(MatchManager).GetField("teamUnits",flags).GetValue(mm);lists[0].Clear();lists[0].AddRange(new[]{caster,second,front,back,human,wolf}.Where(u=>u&&!u.dead));lists[1].Clear();lists[1].AddRange(new[]{a,b}.Where(u=>u&&!u.dead));}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"gurtag-runtime-results.txt",results);}
 static Unit Spawn(Vector3 p,int owner,string prefab="Humans/Swordsman"){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+prefab+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.SetHP(10000);u.armor=0;u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var pos,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=pos.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn(center,0,"Heroes/Orcs/Gurtag");a=Spawn(center+Vector3.forward*4,foeOwner);b=Spawn(center+new Vector3(1,0,4),foeOwner,"Humans/SteelPaladin");back=Spawn(center+Vector3.forward*10,foeOwner,"Humans/RoyalArcher");wolf=Spawn(center+new Vector3(-1,0,4),foeOwner,"Orcs/WarWolf");human=Spawn(center+new Vector3(-1,0,1),0);mage=Spawn(center+Vector3.right*10,0,"Orcs/FelWarlock");slaver=Spawn(center+Vector3.back*2,0,"Orcs/OrcSlaver");
 ram=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Gurtag_FelRam");furnace=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Gurtag_PainFurnace");monolith=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Gurtag_CinderMonolith");pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");caster.LookAtInstant(new Vector2(a.transform.position.x,a.transform.position.z));Register();
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-7);camera.transform.LookAt(center+Vector3.forward);camera.orthographic=true;camera.orthographicSize=6;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("GurtagSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"gurtag-runtime-results.txt",results);File.WriteAllLines(W+"gurtag-runtime-errors.txt",errors);File.WriteAllText(W+"gurtag-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("GurtagSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif



