#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class GurtagSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Heroes/Orcs/Gurtag/";
 const string V="Assets/VFX/Skills/Gurtag/";
 const string A="Assets/Models/Units/Heroes/Orcs/Gurtag/Animations/";
 static GurtagSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-gurtag.txt"))return;try{File.Delete(W+"configure-gurtag.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"gurtag-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"gurtag-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();if(name=="FurnaceCharge")root.AddComponent<SkillBuffPose>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Effector Effect(string name,string label,float duration,AbilityPassiveEffects stats){const string E="Assets/Resources/Effectors/Roster/Heroes/Orcs/Gurtag/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}e.displayName=label;e.duration=duration;e.passiveEffectsOn=true;e.passiveEffects=stats;EditorUtility.SetDirty(e);return e;}

 static Unit Prefab(string name)=>AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+name+".prefab").GetComponent<Unit>();
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var armor=Asset<CompositePassive>("Gurtag_SplinterPlating");var sparks=Asset<CompositeSkill>("Gurtag_Sparks");var ram=Asset<CompositeSkill>("Gurtag_FelRam");var furnace=Asset<CompositeSkill>("Gurtag_PainFurnace");var explosion=Asset<CompositeSkill>("Gurtag_FurnaceExplosion");var monolith=Asset<CompositeSkill>("Gurtag_CinderMonolith");
 var friends=new UnitSelector{isOwn=true,isAlly=true,isUnit=true,isGround=true,isAir=true,isWater=true};var enemies=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isAir=true,isWater=true};
 var physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");
 foreach(var a in new Ability[]{armor,sparks,ram,furnace,explosion,monolith}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_tech_shields.png")};EditorUtility.SetDirty(a);}
 foreach(var a in new[]{sparks,ram,furnace,explosion,monolith}){a.buttonCast=true;a.castTime=new[]{.4f};a.duration=new[]{0f};a.cooldown=new[]{0f};a.manaCost=new[]{0f};a.unitSelector=enemies;a.spawnSocket=SkillSocketType.None;}
 sparks.abilityName=new[]{"Обшивка — искры"};sparks.targetMode=SkillTargetMode.Self;sparks.impactVFX=Vfx("ShieldSparks","Area_generic/Area_generic_green_outbreak",.15f);sparks.impactVfxLifetime=.45f;
 armor.abilityName=new[]{"Осколочная обшивка"};armor.description=new[]{"Каждый вражеский прямой удар в ближнем бою возвращает атакующему10магического урона. Не отвечает на дальние атаки, DoT и союзников."};armor.defense=new PassiveDefenseBlock{enabled=true,incomingMultiplier=1,onlyDirectAttack=true,onlyEnemyMelee=true,counterAttackFlat=10,counterDamageType=magic,presentation=sparks};
 ram.abilityName=new[]{"Таран Скверны"};ram.description=new[]{"Короткий рывок во вражеский строй, физический и огненный урон, отбрасывание пехоты Т1–Т3. Альфа: CD10с, дальность5м, радиус2м, 40физического+30магического огнём, рывок0.45с, отбрасывание2м. Звери и машины не отбрасываются."};ram.targetMode=SkillTargetMode.SmartPoint;ram.targetStrategy=SkillTargetStrategy.Nearest;ram.targetFrontAngle=120;ram.independentAreaTargets=true;ram.areaSelector=enemies;ram.castRange=new[]{5f};ram.radius=new[]{2f};ram.cooldown=new[]{10f};ram.casterMove=new SkillCasterMoveBlock{enabled=true,travelSeconds=.45f};ram.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{40f},damageType=physical},new SkillDamageEntry{amount=new[]{30f},damageType=magic}}};ram.knockback=new SkillKnockbackBlock{enabled=true,maxTier=3,distance=2,alongCasterFacing=true,targetPrefabs=new[]{"Humans/Swordsman","Humans/Swordsman_Inquisition","Humans/RoyalArcher","Humans/InquisitionArcher","Humans/VanguardMage","Humans/PriestOfLight","Orcs/OrcWarrior","Orcs/OrcWarlock","Orcs/OrcSlaver","Orcs/FelFireHurler","Orcs/FelWarlock"}.Select(Prefab).ToArray()};ram.impactVFX=Vfx("RamImpact","Area_generic/Area_generic_green_outbreak",.65f);ram.impactVfxLifetime=1;
 explosion.abilityName=new[]{"Печь — накопленный взрыв"};explosion.targetMode=SkillTargetMode.SmartPoint;explosion.radius=new[]{3f};explosion.impactVFX=Vfx("FurnaceExplosion","Area_generic/Area_generic_green_outbreak",1);explosion.impactVfxLifetime=1.1f;
 furnace.abilityName=new[]{"Печь Боль"};furnace.description=new[]{"Стоит4с: входящий урон−40%. Фактическая потеря HP, включая Погонщика, накапливается и наносится врагам кольцом в конце. Гибель отменяет взрыв. Альфа: CD16с, радиус3м, магический урон100%накопленного."};furnace.targetMode=SkillTargetMode.Self;furnace.cooldown=new[]{16f};furnace.buff=new SkillBuffBlock{enabled=true,duration=new[]{4f},brace=true,storeHealthLoss=true,incomingDamageMultiplier=new[]{.6f},detonationRadius=new[]{3f},detonationDamageType=magic,detonationSelector=enemies,detonationPresentation=explosion,buffVFX=Vfx("FurnaceCharge","Fire/Fire_cartoon_poison",.3f,true)};
 var erosion=Effect("Gurtag_ArmorErosion","Изгарь: броня−2",1.15f,new AbilityPassiveEffects{armorChange=-2});erosion.stacks=true;erosion.maxStacks=7;erosion.VFX=Vfx("ArmorAsh","Fog/Fog_poison",.13f,true);
 var blessing=Effect("Gurtag_MonolithBlessing","Монолит: вампиризм+25%",.3f,new AbilityPassiveEffects());blessing.lifestealFraction=.25f;blessing.waiveSpellHealthCost=true;blessing.freeCostPrefabs=new[]{Prefab("Orcs/FelWarlock")};blessing.VFX=Vfx("MonolithBlessing","Regeneration/Regeneration_health",.22f,true);EditorUtility.SetDirty(blessing);EditorUtility.SetDirty(erosion);
 monolith.abilityName=new[]{"Монолит Изгари"};monolith.description=new[]{"Зона7с: врагам−2брони/с со стаками и урон Скверной; союзникам+25%вампиризма, Т3Чернокнижникам бесплатные HP-касты. Альфа: CD40с, радиус3м,15магического/с; эрозия держится1.15с после последнего импульса."};monolith.targetMode=SkillTargetMode.Self;monolith.cooldown=new[]{40f};monolith.groundZone=new SkillGroundZoneBlock{enabled=true,zonePrefab=Zone(erosion,blessing,magic,enemies,friends),zoneCount=1,forwardOffset=1};monolith.castVFX=Vfx("MonolithCast","Area_generic/Area_generic_green",.6f);monolith.castVfxLifetime=.9f;
 // The document explicitly includes Gurtag among recipients of allied Slaver sacrifice.
 var whip=Resources.LoadAll<CompositeSkill>("Ability").First(x=>x.name=="OrcSlaver_Whip");var hero=Prefab("Heroes/Orcs/Gurtag");if(!whip.targetPrefabs.Contains(hero))whip.targetPrefabs=whip.targetPrefabs.Concat(new[]{hero}).ToArray();EditorUtility.SetDirty(whip);
 RefineCharge(furnace.buff.buffVFX);Assign(new Ability[]{ram,furnace,monolith,armor});AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
 static GameObject Zone(Effector erosion,Effector blessing,DamageType magic,UnitSelector enemies,UnitSelector friends){string path=V+"CinderMonolith.prefab";var root=new GameObject("CinderMonolith");try{var z=root.AddComponent<GroundDamageZone>();var so=new SerializedObject(z);so.FindProperty("radius").floatValue=3;so.FindProperty("duration").floatValue=7;so.FindProperty("damagePerSecond").floatValue=15;so.FindProperty("damageType").objectReferenceValue=magic;so.FindProperty("zoneEffectors").arraySize=1;so.FindProperty("zoneEffectors").GetArrayElementAtIndex(0).objectReferenceValue=erosion;so.ApplyModifiedPropertiesWithoutUndo();SetSelector(z,"targetSelector",enemies);z.effectorInterval=1;z.allyEffectors=new[]{blessing};z.allySelector=friends;
 var effect=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/Area_generic/Area_generic_green.prefab"));effect.transform.SetParent(root.transform,false);effect.SetActive(false);effect.transform.localScale=Vector3.one*.9f;foreach(var ps in effect.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=true;m.maxParticles=Mathf.Min(m.maxParticles,30);}
 var shield=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Models/Units/Orcs/OgreGladiator/SM_Wep_Shield_01.prefab"));shield.name="PlantedSyntyShield";shield.transform.SetParent(root.transform,false);shield.transform.localPosition=new Vector3(0,.8f,0);shield.transform.localRotation=Quaternion.Euler(-12,0,0);shield.transform.localScale=Vector3.one*1.1f;foreach(var c in shield.GetComponentsInChildren<Collider>())UnityEngine.Object.DestroyImmediate(c);
 var fire=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/Fire/Fire_cartoon_poison.prefab"));fire.transform.SetParent(root.transform,false);fire.transform.localPosition=Vector3.up;fire.transform.localScale=Vector3.one*.35f;foreach(var ps in fire.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=true;m.maxParticles=Mathf.Min(m.maxParticles,20);}
 AddGroundLines(root,3,.08f,true);
 return PrefabUtility.SaveAsPrefabAsset(root,path);
 }finally{UnityEngine.Object.DestroyImmediate(root);}}
 static void RefineCharge(VFXReferencer vfx){var path=AssetDatabase.GetAssetPath(vfx.gameObject);var root=PrefabUtility.LoadPrefabContents(path);try{var first=root.transform.GetChild(0);first.localScale=Vector3.one*.55f;AddGroundLines(root,1.2f,-.9f,false);PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
 static void AddGroundLines(GameObject root,float radius,float y,bool cracks){var mat=AssetDatabase.LoadAssetAtPath<Material>(V+"CinderBoundary.mat");if(!mat){mat=new Material(AssetDatabase.LoadAssetAtPath<Material>("Assets/VFX/Materials/LaserBeam.mat"));AssetDatabase.CreateAsset(mat,V+"CinderBoundary.mat");}var child=root.transform.Find("CinderBoundary");if(!child){child=new GameObject("CinderBoundary").transform;child.SetParent(root.transform,false);}var line=child.GetComponent<LineRenderer>();if(!line)line=child.gameObject.AddComponent<LineRenderer>();line.sharedMaterial=mat;line.useWorldSpace=false;line.loop=true;line.widthMultiplier=.035f;line.startColor=line.endColor=new Color(.16f,.55f,.025f,.6f);line.positionCount=64;for(int i=0;i<64;i++){float a=i*Mathf.PI*2/64;line.SetPosition(i,new Vector3(Mathf.Cos(a)*radius,y,Mathf.Sin(a)*radius));}
 if(cracks)for(int n=0;n<7;n++){var go=new GameObject("FelCrack"+n);go.transform.SetParent(root.transform,false);var lr=go.AddComponent<LineRenderer>();lr.sharedMaterial=mat;lr.useWorldSpace=false;lr.widthMultiplier=.045f;lr.startColor=lr.endColor=new Color(.1f,.45f,.015f,.45f);lr.positionCount=5;for(int j=0;j<5;j++){float a=n*Mathf.PI*2/7+(j%2==0?.07f:-.07f);float r=.35f+j*.58f;lr.SetPosition(j,new Vector3(Mathf.Cos(a)*r,.09f,Mathf.Sin(a)*r));}}
 }
 static void SetSelector(UnityEngine.Object o,string name,UnitSelector value){typeof(GroundDamageZone).GetField(name,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(o,value);}
 static void Assign(Ability[] abilities){const string path="Assets/Resources/UnitPrefabs/Units/Heroes/Orcs/Gurtag.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var u=root.GetComponent<Unit>();u.abilities=abilities;u.abilityLevel=new int[abilities.Length];var animator=root.GetComponentInChildren<Animator>(true);string cp=A+"Gurtag_Skills.controller";var ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(cp);if(!ctrl){AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),cp);ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(cp);}var sm=ctrl.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast)cast=sm.AddState("cast");var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");string clipPath=A+"Gurtag_Cast.anim";var clip=AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);if(!clip){clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);AssetDatabase.CreateAsset(clip,clipPath);}AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);cast.motion=clip;cast.speed=clip.length/.9f;if(cast.transitions.Length==0){var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}var brace=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="brace");if(!brace)brace=sm.AddState("brace");brace.motion=sm.states.Select(x=>x.state).First(x=>x.name=="idleReady").motion;brace.speed=0;animator.runtimeAnimatorController=ctrl;EditorUtility.SetDirty(ctrl);EditorUtility.SetDirty(clip);PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
}
#endif
