#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class HaldorSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Heroes/Humans/Haldor/";
 const string V="Assets/VFX/Skills/Haldor/";
 const string A="Assets/Models/Units/Heroes/Humans/Haldor/Animations/";
 static HaldorSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-haldor.txt"))return;try{File.Delete(W+"configure-haldor.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"haldor-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"haldor-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Effector Effect(string name,string label,float duration,AbilityPassiveEffects stats){const string E="Assets/Resources/Effectors/Roster/Heroes/Humans/Haldor/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}e.displayName=label;e.duration=duration;e.passiveEffectsOn=true;e.passiveEffects=stats;EditorUtility.SetDirty(e);return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var aura=Asset<EffectorAura>("Haldor_Duty");var strike=Asset<CompositeSkill>("Haldor_SynodStrike");var courage=Asset<CompositeSkill>("Haldor_Courage");var verdict=Asset<CompositeSkill>("Haldor_IronVerdict");var cleave=Asset<CompositePassive>("Haldor_CourageSplash");var hit=Asset<CompositeSkill>("Haldor_CleaveVisual");
 var friends=new UnitSelector{isOwn=true,isAlly=true,isUnit=true,isGround=true,isWater=true,isAir=true};var enemies=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isWater=true};
 var duty=Effect("Haldor_DutyBuff","Обитель Долга",.3f,new AbilityPassiveEffects{armorChange=1,healthRegenChange=1.5f});
 duty.VFX=Vfx("DutyBlessing","Regeneration/Regeneration_mana_loop",.22f,true);
 aura.abilityName=new[]{"Обитель Долга"};aura.description=new[]{"Союзные юниты в радиусе3м получают +1 к броне и +1.5HP/с. Эффект пропадает при выходе из ауры."};aura.radius=new[]{3f};aura.unitSelector=friends;aura.effectors=new[]{duty};
 foreach(var skill in new[]{strike,courage,verdict}){skill.maxLevels=1;skill.buttonCast=true;skill.castTime=new[]{.65f};skill.manaCost=new[]{0f};skill.duration=new[]{0f};skill.procAnimationState="";skill.spawnSocket=SkillSocketType.None;}
 strike.abilityName=new[]{"Удар Синода"};strike.description=new[]{"Молот наносит45 физического урона врагам в конусе перед Халдором и оглушает на1.2с. CD9с. Альфа: дальность3м, угол100°."};strike.targetMode=SkillTargetMode.Cone;strike.radius=new[]{3f};strike.castRange=new[]{3f};strike.coneAngle=100;strike.cooldown=new[]{9f};strike.unitSelector=enemies;strike.directionMatters=true;strike.castConditions=new SkillCastConditions{requireAreaTarget=true};strike.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{45f},damageType=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset")}}};strike.status=new SkillStatusBlock{enabled=true,stunSeconds=new[]{1.2f}};strike.castVFX=Vfx("SynodShock","Range_attack/Hit_wind",.9f);strike.castVfxLifetime=1.2f;
 var fury=Effect("Haldor_CourageBuff","Боевой кураж",5,new AbilityPassiveEffects{attackSpeedPercentageChange=.3f});fury.VFX=Vfx("BattleCourage","States/Aura_acceleration",.5f,true);
 courage.abilityName=new[]{"Боевой кураж"};courage.description=new[]{"На5с +30% скорости атаки; каждый удар наносит полный урон соседним врагам вокруг Халдора. Альфа: радиус2.5м, CD12с."};courage.targetMode=SkillTargetMode.Self;courage.cooldown=new[]{12f};courage.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=fury}}};courage.castTime=new[]{.2f};
 cleave.abilityName=new[]{"Боевой кураж — круговой удар"};cleave.cleave=new PassiveCleaveBlock{enabled=true,centerOnCaster=true,requiredEffector=fury,radius=2.5f,damageFraction=1,targets=enemies,hitPresentation=hit};hit.targetMode=SkillTargetMode.SmartUnit;hit.spawnSocket=SkillSocketType.None;hit.procAnimationState="";hit.impactVFX=Vfx("HammerImpact","Slash/Hit_stone",.45f);hit.impactVfxLifetime=.7f;
 verdict.abilityName=new[]{"Железный Приговор"};verdict.description=new[]{"На6с Халдор и все боевые союзники его линии получают иммунитет к контролю и35% снижения любого входящего урона. CD40с."};verdict.targetMode=SkillTargetMode.WholeTeam;verdict.unitSelector=friends;verdict.includeSelf=true;verdict.cooldown=new[]{40f};verdict.buff=new SkillBuffBlock{enabled=true,duration=new[]{6f},incomingDamageMultiplier=new[]{.65f},controlImmunity=true,buffVFX=Vfx("IronVerdict","Shields/Shield_freezing",.6f,true)};
 var shieldPath=AssetDatabase.GetAssetPath(verdict.buff.buffVFX);var shieldRoot=PrefabUtility.LoadPrefabContents(shieldPath);try{shieldRoot.transform.GetChild(0).localPosition=new Vector3(0,-1.16f,0);foreach(var ps in shieldRoot.GetComponentsInChildren<ParticleSystem>(true)){if(ps.name=="snow"||ps.name=="snowflake"||ps.name=="circle")ps.gameObject.SetActive(false);}PrefabUtility.SaveAsPrefabAsset(shieldRoot,shieldPath);}finally{PrefabUtility.UnloadPrefabContents(shieldRoot);}
 foreach(var ability in new Ability[]{aura,strike,courage,verdict,cleave,hit}){ability.maxLevels=1;ability.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_tech_shields.png")};EditorUtility.SetDirty(ability);}EditorUtility.SetDirty(duty);EditorUtility.SetDirty(fury);
 const string prefab="Assets/Resources/UnitPrefabs/Units/Heroes/Humans/Haldor.prefab";var root=PrefabUtility.LoadPrefabContents(prefab);try{var unit=root.GetComponent<Unit>();unit.abilities=new Ability[]{strike,courage,verdict,aura,cleave};unit.abilityLevel=new int[unit.abilities.Length];
 var animator=root.GetComponentInChildren<Animator>(true);string ctrlPath=A+"Haldor_Skills.controller";var ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(ctrlPath);if(!ctrl){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),ctrlPath))throw new Exception("Cannot copy Haldor controller");ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(ctrlPath);}var sm=ctrl.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast)cast=sm.AddState("cast");
 var sourceClip=AssetDatabase.LoadAllAssetsAtPath("Assets/DoubleL/FBX_Animations/Two Hand Base/Skills/InPlace/2Hand_Base_Skill_7_InPlace.fbx").OfType<AnimationClip>().First(c=>!c.name.StartsWith("__preview__"));var castClip=AssetDatabase.LoadAssetAtPath<AnimationClip>(A+"Haldor_Cast.anim");if(!castClip){castClip=UnityEngine.Object.Instantiate(sourceClip);AssetDatabase.CreateAsset(castClip,A+"Haldor_Cast.anim");}castClip.name="Haldor_Cast";AnimationUtility.SetAnimationEvents(castClip,Array.Empty<AnimationEvent>());var cs=AnimationUtility.GetAnimationClipSettings(castClip);cs.loopTime=false;AnimationUtility.SetAnimationClipSettings(castClip,cs);cast.motion=castClip;cast.speed=castClip.length/1.5f;if(cast.transitions.Length==0){var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=ctrl;EditorUtility.SetDirty(ctrl);EditorUtility.SetDirty(castClip);File.WriteAllLines(W+"haldor-animation.txt",sm.states.Select(x=>x.state.name+" | "+(x.state.motion?x.state.motion.name:"none")));PrefabUtility.SaveAsPrefabAsset(root,prefab);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif

