#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class HaldorSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";

 static Unit caster,a,b,ally,far,other,second;static CompositeSkill strike,courage,verdict;static EffectorAura aura;static Effector fury,duty;static DamageType physical,pure;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start,speed,hp;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static HaldorSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("HaldorSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-haldor.txt")){File.Delete(W+"run-haldor.txt");Begin();return;}
 if(!SessionState.GetBool("HaldorSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>1){Check(ally.armor==1&&Mathf.Abs(ally.healthRegen-1.5f)<.01f,"Duty aura grants armor1 and regeneration1.5");Check(ally.health>500,"Aura actually heals during ticks");Check(far.armor==0&&a.armor==0,"Aura excludes distant ally and enemy");Check(ally.effectors.Count(e=>e.effector==duty)==1,"Aura refresh does not stack");Capture("haldor-duty.png");ally.agent.Warp(center+Vector3.left*7);Check(Cast(strike),"Native Synod button cast accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.2f){Check(a.health==10000,"Synod windup delays damage");Check(caster.hasCastAnim,"Haldor dedicated cast animation present");phase=3;return;}
 if(phase==3&&Time.time-start>.85f){Check(a.health==9955&&a.stunned,"Cone deals45 physical and stuns");Check(b.health==10000,"Cone excludes rear enemy");Check(ally.armor==0&&ally.healthRegen==0,"Aura leaves no stats after exit");Check(!Cast(strike),"Nine second cooldown rejects repeat");Capture("haldor-synod.png");phase=4;return;}
 if(phase==4&&Time.time-start>2){Check(a.stunned==false,"Stun ends after1.2 seconds");Check(caster.unitState!=UnitStates.AbilityCasting,"Cast returns to idle");Check(Cast(courage),"Courage button cast accepted");phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>.5f){Check(Mathf.Abs(caster.attackSpeed-speed/1.3f)<.01f,"Courage grants30percent attack speed");a.SetHP(10000);b.SetHP(10000);b.agent.Warp(center+Vector3.back*1.8f);caster.DealDamage(a,100,physical,true,a.transform.position);Check(a.health==9900&&b.health==9900,"Courage splashes full hit around caster without duplicate primary");float bh=b.health;caster.DealDamage(a,100,physical,false,a.transform.position);Check(b.health==bh,"Indirect damage does not recurse cleave");Capture("haldor-courage.png");phase=6;return;}
 if(phase==6&&Time.time-start>5.6f){Check(Mathf.Abs(caster.attackSpeed-speed)<.01f&&!caster.effectors.Any(e=>e.effector==fury),"Courage stats and buff expire");float bh=b.health;caster.DealDamage(a,100,physical,true,a.transform.position);Check(b.health==bh,"Cleave stops when courage expires");Check(Cast(verdict),"Iron Verdict button accepted");phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>.9f){Check(caster.GetComponent<ControlImmunity>()&&caster.GetComponent<ControlImmunity>().Active,"Verdict protects caster");Check(far.GetComponent<ControlImmunity>()&&far.GetComponent<ControlImmunity>().Active,"Verdict reaches distant same-line ally");float h=far.health;far.GetDamage(100,pure,foeOwner,a,false,out _);Check(Mathf.Abs(h-far.health-65)<.1f,"Verdict reduces pure incoming damage35percent");far.Stun(2);Check(far.stunned==false,"Verdict blocks incoming control");Check(!other.GetComponent<SkillBuff>(),"Verdict excludes unit outside command line");Check(!Cast(verdict),"Forty second ultimate cooldown blocks repeat");Capture("haldor-verdict.png");phase=8;return;}
 if(phase==8&&Time.time-start>7){Check(!far.GetComponent<SkillBuff>(),"Six second ultimate ends");float h=far.health;far.GetDamage(100,pure,foeOwner,a,false,out _);Check(Mathf.Abs(h-far.health-100)<.1f,"Damage reduction removed after ultimate");far.Stun(.5f);Check(far.stunned,"Control immunity removed after ultimate");Reset(strike);Check(Cast(strike),"Synod reusable after cooldown");phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>1.6f){second=Spawn(center+Vector3.right*5,0,true);var c2=second.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Haldor_Courage");courage.Use(caster,0,0);c2.Use(second,0,0);Check(caster.effectors.Any(e=>e.effector==fury)&&second.effectors.Any(e=>e.effector==fury),"Two Haldors have independent courage buffs");second.Die(-1,null,false);Check(caster.effectors.Any(e=>e.effector==fury),"Other caster death does not remove own buff");a.Die(-1,null,false);b.Die(-1,null,false);Check(!strike.AutoCastReady(caster,0,out _),"No target blocks offensive autocast");a=Spawn(center+Vector3.forward*2,foeOwner);Reset(strike);Cast(strike);a.Die(-1,null,false);phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>1.6f){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death does not freeze animator");a=Spawn(center+Vector3.forward*2,foeOwner);Reset(strike);Cast(strike);caster.Die(-1,null,false);phase=11;start=Time.time;return;}
 if(phase==11&&Time.time-start>7){Check(a.health==10000,"Caster death cancels pending strike");Check(!Cast(strike),"Dead caster cannot cast");Check(!UnityEngine.Object.FindObjectsByType<SkillBuff>(FindObjectsSortMode.None).Any(),"No lingering timed SkillBuff");Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("IronVerdict")||v.name.StartsWith("BattleCourage")||v.name.StartsWith("SynodShock")),"Timed visual effects end");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static bool Cast(CompositeSkill s)=>caster.UseAbilityItem(Array.IndexOf(caster.abilities,s),false,null,Vector3.zero,true);
 static void Reset(CompositeSkill s)=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,s),false);
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"haldor-runtime-results.txt",results);}
 static Unit Spawn(Vector3 p,int owner,bool hero=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(hero?"Heroes/Humans/Haldor":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.SetHP(10000);u.armor=0;u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var pos,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=pos.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn(center,0,true);a=Spawn(center+Vector3.forward*2,foeOwner);b=Spawn(center+Vector3.back*2,foeOwner);ally=Spawn(center+Vector3.left*1.7f,0);ally.SetHP(500);far=Spawn(center+Vector3.right*15,0);other=Spawn(center+Vector3.right*10,0);speed=caster.attackSpeed;
 strike=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Haldor_SynodStrike");courage=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Haldor_Courage");verdict=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Haldor_IronVerdict");aura=caster.abilities.OfType<EffectorAura>().Single();duty=aura.effectors[0];fury=courage.effectors.records[0].effector;physical=strike.damage.entries[0].damageType;pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");caster.LookAtInstant(new Vector2(a.transform.position.x,a.transform.position.z));
 var mm=MatchManager.instance;var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;((TeamWaveConfig)typeof(MatchManager).GetField("teamA",flags).GetValue(mm)).ownerPlayer=0;var lists=(List<Unit>[])typeof(MatchManager).GetField("teamUnits",flags).GetValue(mm);lists[0].Clear();lists[0].AddRange(new[]{caster,ally,far});lists[1].Clear();lists[1].AddRange(new[]{a,b});
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,8,-7);camera.transform.LookAt(center);camera.orthographic=true;camera.orthographicSize=4.5f;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("HaldorSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"haldor-runtime-results.txt",results);File.WriteAllLines(W+"haldor-runtime-errors.txt",errors);File.WriteAllText(W+"haldor-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("HaldorSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif



