#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class InquisitionArcherSkillRuntimeCheck
{
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit archer,foe;static CompositePassive burn,curse;static float start,attackHp;static int phase;static double boot;static int foeOwner;static Vector3 center;static Camera camera;static bool captured;static Effector fire,vulnerability;static DamageType magic;static float hp;static List<string> results=new List<string>(),errors=new List<string>();
 static InquisitionArcherSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("InquisitionArcherSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
  if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
  if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-inquisitionarcher.txt")){try{File.Delete(W+"run-inquisitionarcher.txt");}catch(IOException){return;}Begin();return;}
  if(!SessionState.GetBool("InquisitionArcherSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
  if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}
  if(phase==1&&Time.time-start>1){BurnStart();phase=2;start=Time.time;return;}
  if(phase==2&&Time.time-start>.3f){Capture("inquisitionarcher-burning.png");phase=3;return;}
  if(phase==3&&Time.time-start>3.4f){Check(Mathf.Abs(hp-foe.health-30)<.08f,"Burn deals exactly 30 magic damage over 3 seconds");Check(!foe.effectors.Any(e=>e.effector==fire),"Burn expires after 3 seconds");CurseStart();phase=4;start=Time.time;return;}
  if(phase==4&&Time.time-start>.3f){Capture("inquisitionarcher-curse.png");phase=5;return;}
  if(phase==5&&Time.time-start>5.4f){Check(!foe.effectors.Any(e=>e.effector==vulnerability),"Curse expires after 5 seconds");Check(Mathf.Abs(InterflowCombat.ModifyIncomingDamage(foe,archer,magic,100,false)-100)<.01f,"Curse rule removed on expiration");TechnologyManager.instance.LockTech(curse.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(burn.requiredTech[0].data[0],0);archer.canAttack=true;archer.Attack(foe);phase=6;start=Time.time;return;}
  if(phase==6){if(foe.effectors.Any(e=>e.effector==fire)){archer.canAttack=false;archer.Hold();Check(true,"Real projectile impact applies burning");phase=7;start=Time.time;return;}if(Time.time-start>10)throw new Exception("No burning from actual arrow");}
  if(phase==7&&Time.time-start>4){foreach(var e in foe.effectors.ToArray())Effector.EffectorRemove(foe,e);Effector.EffectorAdd(foe,fire,archer,0);Effector.EffectorAdd(foe,vulnerability,archer,0);var eh=foe.effectors.First(e=>e.effector==fire);Effector.EffectorRemove(foe,eh);Check(foe.effectors.Any(e=>e.effector==vulnerability),"Removing burn preserves different debuff");phase=8;start=Time.time;return;}
  if(phase==8&&Time.time-start>.2f){Check(foe.GetComponentsInChildren<VFXReferencer>().Any(v=>v.name.StartsWith("CausticJudgment")),"Removing burn preserves curse visual");Check(!foe.GetComponentsInChildren<VFXReferencer>().Any(v=>v.name.StartsWith("CleansingBurn")),"Burn visual removed independently");foreach(var e in foe.effectors.ToArray())Effector.EffectorRemove(foe,e);Check(Mathf.Abs(InterflowCombat.ModifyIncomingDamage(foe,archer,magic,100,false)-100)<.01f,"Dispel removes vulnerability rule");DeathTests();phase=9;start=Time.time;return;}
  if(phase==9&&Time.time-start>4){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("CleansingBurn")||v.name.StartsWith("CausticJudgment")),"Debuff visuals cleaned up after death");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("InquisitionArcherSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/InquisitionArcher.prefab").GetComponent<Unit>();archer=Unit.SpawnInternal(prefab,center,0,0);foe=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>(),center+Vector3.forward*3,0,foeOwner);
  foreach(var u in new[]{archer,foe}){u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();}
  archer.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));
  burn=(CompositePassive)archer.abilities.First(a=>a.name=="InquisitionArcher_CleansingFire");curse=(CompositePassive)archer.abilities.First(a=>a.name=="InquisitionArcher_CausticJudgment");fire=burn.attackEffectors.effectors[0];vulnerability=curse.attackEffectors.effectors[0];magic=fire.damageType;
  Check(archer.abilityLocked[Array.IndexOf(archer.abilities,burn)]&&archer.abilityLocked[Array.IndexOf(archer.abilities,curse)],"Both skills initially tech locked");
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-5);camera.transform.LookAt(center+new Vector3(0,.5f,3));camera.orthographic=true;camera.orthographicSize=6;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"inquisitionarcher-runtime-results.txt",results);}
 static float Hit(){float hp=foe.health;archer.DealDamage(foe,100,archer.damageType,true,foe.transform.position+Vector3.up);return hp-foe.health;}
 static void BurnStart(){Hit();Check(!foe.effectors.Any(e=>e.effector==fire),"Locked burning does not apply");TechnologyManager.instance.UnlockTech(burn.requiredTech[0].data[0],0);Hit();Hit();Check(foe.effectors.Count(e=>e.effector==fire)==1,"Repeated hits refresh rather than stack burning");Check(Mathf.Abs(foe.effectors.First(e=>e.effector==fire).currentTime)<.001f,"Repeated hit refreshes burn duration");hp=foe.health;}
 static void CurseStart(){TechnologyManager.instance.LockTech(burn.requiredTech[0].data[0],0);Check(!archer.attackEffectors.Contains(fire),"Closing burning removes attack effector");TechnologyManager.instance.UnlockTech(curse.requiredTech[0].data[0],0);Hit();Hit();Check(foe.effectors.Count(e=>e.effector==vulnerability)==1,"Curse refreshes without stacking");Check(Mathf.Abs(InterflowCombat.ModifyIncomingDamage(foe,archer,magic,100,false)-115)<.01f,"Magic damage increased exactly 15%");Check(Mathf.Abs(InterflowCombat.ModifyIncomingDamage(foe,archer,archer.damageType,100,true)-100)<.01f,"Physical damage unaffected by magic vulnerability");}
 static void DeathTests(){archer.canAttack=false;archer.Hold();var shot=Projectile.Spawn(archer.owner,archer,archer.projectileGO.GetComponent<Projectile>(),archer.transform.position+Vector3.up,Quaternion.identity,foe,true,100,archer.damageType,true,false);Check(shot!=null,"Arrow in flight for death edge case");foe.Die(0,archer,false);archer.Die(foeOwner,foe,false);Check(foe.dead&&archer.dead,"Target and caster can die with arrow in flight");}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("CleansingBurn")||v.name.StartsWith("CausticJudgment")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"inquisitionarcher-runtime-results.txt",results);File.WriteAllLines(W+"inquisitionarcher-runtime-errors.txt",errors);File.WriteAllText(W+"inquisitionarcher-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("InquisitionArcherSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


