#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class InquisitorSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";

 static Unit caster,a,b,ally,far,second;static CompositeSkill bolt,prayer,ascension,dash,blade;static EffectorAura aura;static DamageType pure;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start,mp,hp,range;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static InquisitorSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("InquisitorSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-inquisitor.txt")){File.Delete(W+"run-inquisitor.txt");Begin();return;}
 if(!SessionState.GetBool("InquisitorSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.5f){Check(caster.maxMana==1000&&caster.mana==0,"Faith starts at zero with cap1000");Check(!Cast(ascension),"Ascension requires1000Faith");Check(!Cast(dash)&&!Cast(blade),"Avatar skills unavailable in base form");caster.DealDamage(a,10,pure,true,a.transform.position);Check(Mathf.Abs(caster.mana-5)<.01f,"Successful ranged hit gains5Faith");mp=caster.mana;a.GetDamage(0,pure,0,caster,true,out _);Check(caster.mana==mp,"Zero damage grants no Faith");ally.GetDamage(10,pure,0,caster,true,out _);Check(caster.mana==mp,"Friendly hit grants no Faith");a.SetHP(5);caster.DealDamage(a,10,pure,true,a.transform.position);Check(Mathf.Abs(caster.mana-mp-15)<.01f,"Killing shot gains5 plus10Faith");a=Spawn(center+Vector3.forward*3,foeOwner);mp=caster.mana;start=Time.time;phase=2;return;}
 if(phase==2&&Time.time-start>1.1f){Check(caster.mana>=mp+1&&caster.mana<mp+1.4f,"Combat generates1Faith per second");float h=ally.health;a.melee=false;ally.GetDamage(100,pure,foeOwner,a,true,out _);Check(Mathf.Abs(h-ally.health-85)<.1f,"Faith shield reduces ranged damage15percent");h=ally.health;a.melee=true;ally.GetDamage(100,pure,foeOwner,a,true,out _);Check(Mathf.Abs(h-ally.health-100)<.1f,"Faith shield excludes melee");h=ally.health;a.melee=false;ally.GetDamage(100,pure,foeOwner,a,false,out _);Check(Mathf.Abs(h-ally.health-100)<.1f,"Faith shield excludes indirect damage");Check(!far.effectors.Any(e=>e.effector==aura.effectors[0]),"Shield excludes outside radius");Capture("inquisitor-dome-final.png");caster.SetHP(500);ally.SetHP(500);Check(Cast(prayer),"Prayer button accepted");start=Time.time;phase=3;return;}
 if(phase==3&&Time.time-start>.9f){Check(Mathf.Abs(caster.health-725)<.1f,"Prayer heals self225");Check(Mathf.Abs(ally.health-650)<.1f,"Prayer heals ally150");Check(!Cast(prayer),"Prayer cooldown blocks repeat");Capture("inquisitor-prayer.png");Check(Cast(bolt),"Cleansing bolt button accepted");start=Time.time;phase=4;return;}
 if(phase==4&&Time.time-start>1.8f){Check(a.health<10000,"Bolt damages target");Check(a.armor==-2,"Bolt applies armor reduction on impact");Check(!Cast(bolt),"Bolt cooldown blocks repeat");Capture("inquisitor-bolt.png");start=Time.time;phase=5;return;}
 if(phase==5&&Time.time-start>5.3f){Check(a.armor==0,"Armor debuff expires after5sec");caster.SetMP(1000);Check(Cast(ascension),"Full Faith allows Ascension");start=Time.time;phase=6;return;}
 if(phase==6&&Time.time-start>.6f){Capture("inquisitor-leap.png");phase=7;return;}
 if(phase==7&&Time.time-start>1.5f){Check(caster.polymorphed&&caster.melee,"Ascension changes model and melee attack mode");Check(caster.mana==0,"Ascension consumes all Faith");Check(caster.polymorphTime>18&&caster.polymorphTime<=20,"Avatar duration20seconds");Check(!Cast(bolt)&&!Cast(prayer),"Base actives gated while Avatar");Check(a.health<9900,"Landing deals AoE damage");Capture("inquisitor-avatar.png");phase=8;return;}
 if(phase==8&&Time.time-start>22){Check(!caster.polymorphed&&!caster.melee,"After20sec original ranged form restored");Check(Mathf.Abs(caster.attackRange-range)<.01f&&caster.projectileGO,"Original range and projectile restored");Check(!Cast(dash),"Avatar skill closes after return");Reset(bolt);a.transform.position=caster.transform.position+Vector3.forward*3;Check(Cast(bolt),"Bolt reusable after return");start=Time.time;phase=9;return;}
 if(phase==9&&Time.time-start>1.6f){Check(caster.unitState!=UnitStates.AbilityCasting,"Animator leaves cast after return");second=Spawn(center+Vector3.right*5,0,true);second.DealDamage(a,10,pure,true,a.transform.position);Check(second.mana>=5&&second.mana<6,"Second Inquisitor has own Faith");second.Die(-1,null,false);mp=caster.mana;caster.SetMP(1000);Reset(ascension);a.Die(-1,null,false);b.Die(-1,null,false);Check(!Cast(ascension),"No enemy rejects Ascension");a=Spawn(caster.transform.position+Vector3.forward*3,foeOwner);Reset(bolt);Cast(bolt);a.Die(-1,null,false);start=Time.time;phase=10;return;}
 if(phase==10&&Time.time-start>1.8f){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death during cast releases state");a=Spawn(caster.transform.position+Vector3.forward*3,foeOwner);Reset(ascension);Cast(ascension);caster.Die(-1,null,false);start=Time.time;phase=11;return;}
 if(phase==11&&Time.time-start>2){Check(!Cast(prayer),"Dead caster cannot cast");Check(!caster||!caster.GetComponent<SkillTravel>()||!caster.GetComponent<SkillTravel>().Running,"Death leaves no running movement");Check(a.health==10000,"Caster death cancels pending landing damage");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static bool Cast(CompositeSkill s){Register();return caster&&caster.UseAbilityItem(Array.IndexOf(caster.abilities,s),false,null,Vector3.zero,true);}
 static void Register(){var mm=MatchManager.instance;var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;((TeamWaveConfig)typeof(MatchManager).GetField("teamA",flags).GetValue(mm)).ownerPlayer=0;((TeamWaveConfig)typeof(MatchManager).GetField("teamB",flags).GetValue(mm)).ownerPlayer=foeOwner;var lists=(List<Unit>[])typeof(MatchManager).GetField("teamUnits",flags).GetValue(mm);lists[0].Clear();lists[0].AddRange(new[]{caster,ally,far,second}.Where(u=>u&&!u.dead));lists[1].Clear();lists[1].AddRange(new[]{a,b}.Where(u=>u&&!u.dead));}
 static void Reset(CompositeSkill s)=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,s),false);
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"inquisitor-runtime-results.txt",results);}
 static Unit Spawn(Vector3 p,int owner,bool hero=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(hero?"Heroes/Humans/Inquisitor_Base":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.SetHP(10000);u.armor=0;u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var pos,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=pos.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn(center,0,true);a=Spawn(center+Vector3.forward*3,foeOwner);b=Spawn(center+Vector3.forward*5,foeOwner);ally=Spawn(center+Vector3.left*1.5f,0);far=Spawn(center+Vector3.right*15,0);range=caster.attackRange;
 bolt=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Inquisitor_CleansingBolt");prayer=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Inquisitor_Prayer");ascension=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Inquisitor_Ascension");dash=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Avatar_RighteousDash");blade=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Avatar_EcstasyBlade");aura=caster.abilities.OfType<EffectorAura>().Single();pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");caster.LookAtInstant(new Vector2(a.transform.position.x,a.transform.position.z));
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,8,-7);camera.transform.LookAt(center+Vector3.forward);camera.orthographic=true;camera.orthographicSize=4.5f;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("InquisitorSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"inquisitor-runtime-results.txt",results);File.WriteAllLines(W+"inquisitor-runtime-errors.txt",errors);File.WriteAllText(W+"inquisitor-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("InquisitorSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif



