#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class InquisitorSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Heroes/Humans/Inquisitor/";
 const string V="Assets/VFX/Skills/Inquisitor/";
 const string A="Assets/Models/Units/Heroes/Humans/Inquisitor/Animations/";
 static InquisitorSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-inquisitor.txt"))return;try{File.Delete(W+"configure-inquisitor.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"inquisitor-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"inquisitor-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Effector Effect(string name,string label,float duration,AbilityPassiveEffects stats){const string E="Assets/Resources/Effectors/Roster/Heroes/Humans/Inquisitor/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}e.displayName=label;e.duration=duration;e.passiveEffectsOn=true;e.passiveEffects=stats;EditorUtility.SetDirty(e);return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var faith=Asset<CompositePassive>("Inquisitor_Faith");var aura=Asset<EffectorAura>("Inquisitor_FaithShield");var bolt=Asset<CompositeSkill>("Inquisitor_CleansingBolt");var prayer=Asset<CompositeSkill>("Inquisitor_Prayer");var avatar=Asset<CompositeSkill>("Inquisitor_Ascension");var dash=Asset<CompositeSkill>("Avatar_RighteousDash");var blade=Asset<CompositeSkill>("Avatar_EcstasyBlade");var impact=Asset<CompositeSkill>("Inquisitor_BoltImpact");var trail=Asset<CompositeSkill>("Avatar_FireTrail");
 var friends=new UnitSelector{isOwn=true,isAlly=true,isUnit=true,isGround=true,isWater=true,isAir=true};var enemies=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isWater=true};
 var physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");
 var basePrefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Heroes/Humans/Inquisitor_Base.prefab");var shape=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Heroes/Humans/Inquisitor_Avatar.prefab").GetComponent<Unit>();
 faith.abilityName=new[]{"Шкала Веры"};faith.description=new[]{"Вера: 0–1000. +5 за успешный выстрел, +10 за убийство врага, +1/с в бою. В Аватаре не накапливается. Альфа: бой продолжается 5с после удара."};faith.combatResource=new PassiveCombatResourceBlock{enabled=true};
 var protection=Effect("Inquisitor_FaithProtection","Щит веры",.3f,new AbilityPassiveEffects());protection.incomingDamageMultiplier=.85f;protection.incomingRangedOnly=true;
 protection.VFX=Vfx("FaithProtection","Regeneration/Regeneration_mana_loop",.15f,true);
 aura.abilityName=new[]{"Щит веры"};aura.description=new[]{"Союзники в2м получают на15% меньше урона от прямых атак вражеских стрелков."};aura.originalFormOnly=true;aura.radius=new[]{2f};aura.unitSelector=friends;aura.effectors=new[]{protection};
 var dome=Effect("Inquisitor_DomeVisual","Купол веры",.3f,new AbilityPassiveEffects());dome.VFX=Vfx("FaithDome","Shields/Shield_freezing",1.2f,true);var dp=AssetDatabase.GetAssetPath(dome.VFX);var dr=PrefabUtility.LoadPrefabContents(dp);try{dr.transform.GetChild(0).localPosition=new Vector3(0,-2.33f,0);foreach(var ps in dr.GetComponentsInChildren<ParticleSystem>(true)){if(ps.name=="snow"||ps.name=="snowflake"||ps.name=="circle")ps.gameObject.SetActive(false);var m=ps.main;m.startColor=new Color(.65f,.55f,.3f,.12f);}PrefabUtility.SaveAsPrefabAsset(dr,dp);}finally{PrefabUtility.UnloadPrefabContents(dr);}aura.casterEffector=dome;EditorUtility.SetDirty(dome);

 foreach(var x in new[]{bolt,prayer,avatar,dash,blade,impact,trail}){x.buttonCast=true;x.maxLevels=1;x.castTime=new[]{.35f};x.manaCost=new[]{0f};x.duration=new[]{0f};x.spawnSocket=SkillSocketType.None;x.procAnimationState="";x.unitSelector=enemies;}
 bolt.abilityName=new[]{"Очищающий болт"};bolt.description=new[]{"Усиленный болт, снижение брони на5с. Альфа:70 физического урона, −2 брони, CD8с."};bolt.targetMode=SkillTargetMode.SmartUnit;bolt.castRange=new[]{8f};bolt.cooldown=new[]{8f};bolt.castConditions=new SkillCastConditions{requireOriginalForm=true};bolt.delivery=SkillDelivery.Projectile;bolt.projectileDirectAttack=true;bolt.projectilePrefab=basePrefab.GetComponent<Unit>().projectileGO.GetComponent<Projectile>();bolt.spawnSocket=SkillSocketType.Weapon;bolt.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{70f},damageType=physical}}};bolt.projectileImpact=new SkillProjectileImpactBlock{enabled=true,skill=impact};
 var armor=Effect("Inquisitor_PurifiedArmor","Очищение",5,new AbilityPassiveEffects{armorChange=-2});armor.VFX=Vfx("PurifiedArmor","States/Stun",.25f,true);
 impact.targetMode=SkillTargetMode.SmartUnit;impact.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=armor}}};impact.impactVFX=Vfx("BoltImpact","Range_attack/Hit_wind",.35f);impact.impactVfxLifetime=.6f;
 prayer.abilityName=new[]{"Святая молитва"};prayer.description=new[]{"Лечит союзных воинов на150HP и себя ещё на75HP. Альфа: радиус4м, CD14с."};prayer.targetMode=SkillTargetMode.AreaAroundSelf;prayer.radius=new[]{4f};prayer.unitSelector=friends;prayer.includeSelf=true;prayer.cooldown=new[]{14f};prayer.castConditions=new SkillCastConditions{requireOriginalForm=true};prayer.heal=new SkillHealBlock{enabled=true,flat=new[]{150f},extraSelf=new[]{75f}};prayer.impactVFX=Vfx("HolyPrayer","Regeneration/Regeneration_health",.75f);prayer.impactVfxLifetime=1.5f;
 avatar.abilityName=new[]{"Аватар Света"};avatar.description=new[]{"За1000 Веры прыжок в скопление врагов, удар и отбрасывание. Аватар на20с. Альфа:100 магического урона, радиус3м, дальность8м, отбрасывание2м."};avatar.targetMode=SkillTargetMode.SmartPoint;avatar.targetStrategy=SkillTargetStrategy.Cluster;avatar.radius=new[]{3f};avatar.castRange=new[]{8f};avatar.cooldown=new[]{20f};avatar.manaCost=new[]{1000f};avatar.castConditions=new SkillCastConditions{requireOriginalForm=true};avatar.casterMove=new SkillCasterMoveBlock{enabled=true,travelSeconds=.6f,leapHeight=1.4f};avatar.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{100f},damageType=magic}}};avatar.knockback=new SkillKnockbackBlock{enabled=true,distance=2};avatar.morph=new SkillMorphBlock{enabled=true,applyToCaster=true,copyAttackMode=true,shapeUnit=shape,duration=new[]{20f},disarmWhileMorphed=false,muteWhileMorphed=false};avatar.impactVFX=Vfx("AscensionImpact","Fire/Fire_explosion_earth",.85f);avatar.impactVfxLifetime=1.4f;
 dash.abilityName=new[]{"Праведный рывок"};dash.description=new[]{"Рывок к врагам с огненным следом. Альфа: дальность7м, CD6с, след3с по15 магического урона/с."};dash.targetMode=SkillTargetMode.SmartPoint;dash.castRange=new[]{7f};dash.radius=new[]{1f};dash.cooldown=new[]{6f};dash.castConditions=new SkillCastConditions{requiredShape=shape};dash.casterMove=new SkillCasterMoveBlock{enabled=true,travelSeconds=.4f,passThroughDistance=2,trailSkill=trail,trailSpacing=1};
 string zp=V+"RighteousFireGround.prefab";if(!AssetDatabase.LoadAssetAtPath<GameObject>(zp))AssetDatabase.CopyAsset("Assets/VFX/Skills/OrcCatapult/BurningGround.prefab",zp);var zr=PrefabUtility.LoadPrefabContents(zp);try{var so=new SerializedObject(zr.GetComponent<GroundDamageZone>());so.FindProperty("radius").floatValue=.65f;so.FindProperty("duration").floatValue=3;so.FindProperty("damagePerSecond").floatValue=15;so.FindProperty("damageType").objectReferenceValue=magic;so.FindProperty("zoneEffectors").arraySize=0;so.FindProperty("conditionalEffectors").arraySize=0;so.ApplyModifiedPropertiesWithoutUndo();foreach(var ps in zr.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.startColor=new Color(1,.68f,.16f,.7f);m.maxParticles=Mathf.Min(m.maxParticles,12);}zr.transform.localScale=Vector3.one*.4f;PrefabUtility.SaveAsPrefabAsset(zr,zp);}finally{PrefabUtility.UnloadPrefabContents(zr);}trail.targetMode=SkillTargetMode.SmartPoint;trail.groundZone=new SkillGroundZoneBlock{enabled=true,zonePrefab=AssetDatabase.LoadAssetAtPath<GameObject>(zp)};
 var slow=Effect("Avatar_EcstasySlow","Клинок Экстаза",3,new AbilityPassiveEffects{moveSpeedPercentageChange=-.3f});slow.VFX=Vfx("EcstasySlow","States/Stun",.2f,true);
 blade.abilityName=new[]{"Клинок Экстаза"};blade.description=new[]{"Удар по дуге180° с замедлением выживших. Альфа:90 физического урона, радиус3м, −30% скорости на3с, CD5с."};blade.targetMode=SkillTargetMode.Cone;blade.coneAngle=180;blade.radius=new[]{3f};blade.castRange=new[]{3f};blade.cooldown=new[]{5f};blade.directionMatters=true;blade.castConditions=new SkillCastConditions{requiredShape=shape,requireAreaTarget=true};blade.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{90f},damageType=physical}}};blade.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=slow}}};blade.castVFX=Vfx("EcstasySlash","Slash/Hit_stone",.6f);blade.castVfxLifetime=.8f;
 foreach(var ability in new Ability[]{faith,aura,bolt,prayer,avatar,dash,blade,impact,trail}){ability.maxLevels=1;ability.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_tech_shields.png")};EditorUtility.SetDirty(ability);}foreach(var e in new[]{protection,armor,slow})EditorUtility.SetDirty(e);
 Assign("Inquisitor_Base",new Ability[]{bolt,prayer,avatar,dash,blade,aura,faith},1000);Assign("Inquisitor_Avatar",new Ability[]{dash,blade},0);
 AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
 static void Assign(string name,Ability[] abilities,float mana){string path="Assets/Resources/UnitPrefabs/Units/Heroes/Humans/"+name+".prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var u=root.GetComponent<Unit>();u.abilities=abilities;u.abilityLevel=new int[abilities.Length];u.maxMana=mana;u.mana=0;u.manaRegen=0;var animator=root.GetComponentInChildren<Animator>(true);string cp=A+name+"_Skills.controller";var ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(cp);if(!ctrl){AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),cp);ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(cp);}var sm=ctrl.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast)cast=sm.AddState("cast");var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");string clipPath=A+name+"_Cast.anim";var clip=AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);if(!clip){clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);AssetDatabase.CreateAsset(clip,clipPath);}AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);cast.motion=clip;cast.speed=clip.length/.85f;if(cast.transitions.Length==0){var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=ctrl;EditorUtility.SetDirty(ctrl);EditorUtility.SetDirty(clip);PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
}
#endif
