#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class KorgalSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";


 static Unit caster,second,a,b,front,back,human,wolf;static CompositeSkill blast,spit,rite;static DamageType pure;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start,hp,enemyHp,frontHp,speed,attackSpeed;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static KorgalSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("KorgalSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-korgal.txt")){File.Delete(W+"run-korgal.txt");Begin();return;}
 if(!SessionState.GetBool("KorgalSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.6f){caster.SetHP(500);var sacrifice=Spawn(center+Vector3.right*10,0,"Orcs/OrcWarrior");sacrifice.Die(foeOwner,a,true);Check(caster.health==525,"Allied orc killed by enemy heals25");sacrifice=Spawn(center+Vector3.right*10,0,"Orcs/OrcWarrior");sacrifice.Die(0,caster,false);Check(caster.health==550,"Own sacrifice also heals25");sacrifice=Spawn(center+Vector3.right*10,foeOwner,"Orcs/OrcWarrior");sacrifice.Die(0,caster,false);Check(caster.health==550,"Enemy orc death grants no healing");sacrifice=Spawn(center+Vector3.right*10,0);sacrifice.Die(foeOwner,a,false);Check(caster.health==550,"Human ally death grants no healing");Capture("korgal-harvest.png");caster.SetHP(1000);a.armor=100;enemyHp=a.health;frontHp=front.health;Check(Cast(blast),"Discharge button accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>1){Check(caster.health==940,"Discharge costs60HP once");Check(Mathf.Abs(enemyHp-a.health-70)<.1f,"Discharge deals70pure through armor");Check(Mathf.Abs(frontHp-front.health-25)<.1f,"Discharge damages allied detonator25physical");Check(human.health==10000,"Discharge excludes allied humans");Check(back.health==10000&&wolf.health==10000,"Discharge excludes rear and animal targets");Check(!Cast(blast),"Discharge cooldown blocks repeat");Capture("korgal-discharge.png");caster.SetHP(50);Reset(blast);Check(!Cast(blast),"Lethal health cost rejects cast");caster.SetHP(1000);Move(front,center+Vector3.back*6);Reset(blast);Check(!Cast(blast),"No front orc rejects Discharge");Move(front,center+Vector3.forward*3);a.armor=0;enemyHp=a.health;Check(Cast(spit),"Rotten spit button accepted");phase=3;start=Time.time;return;}
 if(phase==3&&Time.time-start>.65f){Capture("korgal-spit-flight.png");phase=4;return;}
 if(phase==4&&Time.time-start>1.8f){Check(a.health<enemyHp&&b.health<10000,"Bile damages enemy cluster on impact");Check(Mathf.Abs(a.moveSpeed-speed*.75f)<.01f,"Bile reduces movement exactly25percent");Check(Mathf.Abs(a.attackSpeed-attackSpeed/.75f)<.01f,"Bile reduces attack frequency25percent");Check(!human.effectors.Any(e=>e.effector.name=="Korgal_BileSlow"),"Bile slow excludes allies");Check(!Cast(spit),"Spit cooldown blocks repeat");Capture("korgal-bile-impact.png");phase=5;return;}
 if(phase==5&&Time.time-start>6){Check(Mathf.Abs(a.moveSpeed-speed)<.01f&&Mathf.Abs(a.attackSpeed-attackSpeed)<.01f,"Bile slow expires after4sec");Check(caster.unitState!=UnitStates.AbilityCasting,"Cast animation ends");caster.SetHP(1000);front.SetHP(1000);back.SetHP(1000);Check(Cast(rite),"Bonfire button accepted");enemyHp=a.health;phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>1.2f){Check(caster.health<=800&&caster.health>=793,"Bonfire costs20percent currentHP plus selfburn");Check(front.GetComponents<SkillBuff>().Length==1&&back.GetComponents<SkillBuff>().Length==1,"Bonfire applies to front and rear orcs in current wave");Check(!human.GetComponent<SkillBuff>()&&!wolf.GetComponent<SkillBuff>(),"Bonfire excludes humans and beasts");Check(front.health<1000&&front.health>990,"Bonfire selfburn5HPpersec");Check(a.health<enemyHp,"Bonfire aura damages nearby enemies");Check(!Cast(rite),"Bonfire cooldown40blocks repeat");Capture("korgal-bonfire.png");enemyHp=a.health;hp=caster.health;front.Die(foeOwner,a,false);Check(Mathf.Abs(enemyHp-a.health-40)<.1f,"Orc death under Bonfire deals40AoE");Check(Mathf.Abs(caster.health-hp-25)<.1f,"Bonfire death also triggers SoulHarvest once");phase=7;return;}
 if(phase==7&&Time.time-start>7.3f){Check(!back.GetComponent<SkillBuff>()&&!caster.GetComponent<SkillBuff>(),"Bonfire components expire after6sec");hp=back.health;phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>1){Check(back.health==hp,"Selfburn stops when Bonfire expires");front=Spawn(center+Vector3.forward*3,0,"Orcs/OrcWarrior");Reset(blast);Check(Cast(blast),"Discharge reusable after cooldown");phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>1){second=Spawn(center+Vector3.right*6,0,"Heroes/Orcs/Korgal");second.SetHP(300);caster.SetHP(300);var sacrifice=Spawn(center+Vector3.right*10,0,"Orcs/OrcWarrior");sacrifice.Die(foeOwner,a,false);Check(caster.health==325&&second.health==325,"Two Korgals heal independently from one allied death");second.LookAtInstant(new Vector2(b.transform.position.x,b.transform.position.z));float before=b.health;spit.Use(second,0,0);Reset(spit);Check(Cast(spit),"Spit reusable");a.Die(-1,null,false);b.Die(-1,null,false);phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>2){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death releases cast");Reset(spit);Check(!Cast(spit),"No enemies rejects Spit");a=Spawn(center+Vector3.forward*4,foeOwner);Reset(spit);Cast(spit);caster.Die(-1,null,false);phase=11;start=Time.time;return;}
 if(phase==11&&Time.time-start>2){Check(!caster||caster.dead,"Caster death during spell handled");Check(!caster||!Cast(rite),"Dead caster cannot cast");Check(!UnityEngine.Object.FindObjectsByType<Projectile>(FindObjectsSortMode.None).Any(p=>p.name.Contains("Korgal_Bile")),"No stuck bile projectiles");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Move(Unit u,Vector3 p){if(u)Knockback.MoveTo(u,p,false);}
 static bool Cast(CompositeSkill s){Register();return caster&&caster.UseAbilityItem(Array.IndexOf(caster.abilities,s),false,null,Vector3.zero,true);}
 static void Reset(CompositeSkill s)=>caster.ChangeAbilityCooldown(-100,Array.IndexOf(caster.abilities,s),false);
 static void Register(){var mm=MatchManager.instance;var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;((TeamWaveConfig)typeof(MatchManager).GetField("teamA",flags).GetValue(mm)).ownerPlayer=0;((TeamWaveConfig)typeof(MatchManager).GetField("teamB",flags).GetValue(mm)).ownerPlayer=foeOwner;var lists=(List<Unit>[])typeof(MatchManager).GetField("teamUnits",flags).GetValue(mm);lists[0].Clear();lists[0].AddRange(new[]{caster,second,front,back,human,wolf}.Where(u=>u&&!u.dead));lists[1].Clear();lists[1].AddRange(new[]{a,b}.Where(u=>u&&!u.dead));}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"korgal-runtime-results.txt",results);}
 static Unit Spawn(Vector3 p,int owner,string prefab="Humans/Swordsman"){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+prefab+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.SetHP(10000);u.armor=0;u.healthRegen=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var au=u.GetComponent<AutoAbilityUser>();if(au)au.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var pos,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=pos.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn(center,0,"Heroes/Orcs/Korgal");front=Spawn(center+Vector3.forward*3,0,"Orcs/OrcWarrior");back=Spawn(center+Vector3.back*4,0,"Orcs/OrcWarrior");human=Spawn(center+new Vector3(1,0,3),0);wolf=Spawn(center+new Vector3(-4,0,3),0,"Orcs/WarWolf");a=Spawn(center+Vector3.forward*4,foeOwner);b=Spawn(center+new Vector3(1,0,4.4f),foeOwner);speed=a.moveSpeed;attackSpeed=a.attackSpeed;
 blast=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Korgal_FelDischarge");spit=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Korgal_RottenSpit");rite=caster.abilities.OfType<CompositeSkill>().Single(x=>x.name=="Korgal_SacrificialBonfire");pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");caster.LookAtInstant(new Vector2(a.transform.position.x,a.transform.position.z));Register();
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-7);camera.transform.LookAt(center+Vector3.forward);camera.orthographic=true;camera.orthographicSize=6;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("KorgalSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}



 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"korgal-runtime-results.txt",results);File.WriteAllLines(W+"korgal-runtime-errors.txt",errors);File.WriteAllText(W+"korgal-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("KorgalSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif



