#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class KorgalSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Heroes/Orcs/Korgal/";
 const string V="Assets/VFX/Skills/Korgal/";
 const string A="Assets/Models/Units/Heroes/Orcs/Korgal/Animations/";
 static KorgalSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-korgal.txt"))return;try{File.Delete(W+"configure-korgal.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"korgal-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"korgal-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Effector Effect(string name,string label,float duration,AbilityPassiveEffects stats){const string E="Assets/Resources/Effectors/Roster/Heroes/Orcs/Korgal/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}e.displayName=label;e.duration=duration;e.passiveEffectsOn=true;e.passiveEffects=stats;EditorUtility.SetDirty(e);return e;}

 static Unit Prefab(string name)=>AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+name+".prefab").GetComponent<Unit>();
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var death=Asset<CompositeSkill>("Korgal_BonfireDeath");var soul=Asset<CompositePassive>("Korgal_SoulHarvest");var harvest=Asset<CompositeSkill>("Korgal_HarvestVisual");var blast=Asset<CompositeSkill>("Korgal_FelDischarge");var spit=Asset<CompositeSkill>("Korgal_RottenSpit");var impact=Asset<CompositeSkill>("Korgal_BileImpact");var rite=Asset<CompositeSkill>("Korgal_SacrificialBonfire");
 var friends=new UnitSelector{isOwn=true,isAlly=true,isUnit=true,isGround=true,isWater=true,isAir=true};var enemies=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isWater=true,isAir=true};var all=friends;all.isEnemy=true;
 var orcs=new[]{"OrcWarrior","OrcWarlock","OrcSlaver","FelFireHurler","FelWarlock","BloodBerserker","FelLord"}.Select(n=>Prefab("Orcs/"+n)).Concat(new[]{Prefab("Heroes/Orcs/Korgal"),Prefab("Heroes/Orcs/Gurtag")}).ToArray();
 var physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");var pure=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Pure.asset");
 foreach(var s in new[]{death,harvest,blast,spit,impact,rite}){s.buttonCast=true;s.maxLevels=1;s.castTime=new[]{.4f};s.manaCost=new[]{0f};s.duration=new[]{0f};s.cooldown=new[]{0f};s.spawnSocket=SkillSocketType.None;s.unitSelector=enemies;}
 death.abilityName=new[]{"Костёр — взрыв при гибели"};death.targetMode=SkillTargetMode.SmartPoint;death.radius=new[]{2f};death.impactVFX=Vfx("BonfireDeath","Area_generic/Area_generic_green_outbreak",.5f);death.impactVfxLifetime=.8f;
 harvest.abilityName=new[]{"Жатва душ — поглощение"};harvest.targetMode=SkillTargetMode.Self;harvest.impactVFX=Vfx("SoulHarvest","Regeneration/Regeneration_health",.35f);harvest.impactVfxLifetime=1.1f;
 soul.abilityName=new[]{"Жатва душ"};soul.description=new[]{"Гибель каждого союзного орка на линии восстанавливает Коргалу25HP независимо от убийцы. Не действует на людей, зверей, огров и осадные машины."};soul.allyDeath=new PassiveAllyDeathBlock{enabled=true,healFlat=25,victimPrefabs=orcs,presentation=harvest};
 blast.abilityName=new[]{"Выброс Скверны"};blast.description=new[]{"Цена60HP, CD7с. Случайный союзный орк впереди взрывается: врагам70чистого, своим оркам25физического, радиус2м. Альфа: поиск перед собой в120°, дальность10м."};blast.targetMode=SkillTargetMode.SmartPoint;blast.targetStrategy=SkillTargetStrategy.RandomOne;blast.unitSelector=friends;blast.targetPrefabs=orcs;blast.targetFrontAngle=120;blast.independentAreaTargets=true;blast.areaSelector=all;blast.includeSelf=true;blast.castRange=new[]{10f};blast.radius=new[]{2f};blast.cooldown=new[]{7f};blast.selfCost=new SkillSelfCostBlock{enabled=true,flatHp=new[]{60f}};blast.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{70f},damageType=pure},new SkillDamageEntry{amount=new[]{25f},damageType=physical,targets=SkillDamageTargets.Allies,targetPrefabs=orcs}}};blast.impactVFX=Vfx("FelDischarge","Area_generic/Area_generic_green_outbreak",.7f);blast.impactVfxLifetime=1.2f;
 var slow=Effect("Korgal_BileSlow","Едкая желчь",4,new AbilityPassiveEffects{exactPercentageReductions=true,moveSpeedPercentageChange=-.25f,attackSpeedPercentageChange=-.25f});slow.VFX=Vfx("BileSlow","Fog/Fog_poison",.18f,true);
 impact.abilityName=new[]{"Гнилой плевок — попадание"};impact.targetMode=SkillTargetMode.SmartPoint;impact.radius=new[]{2f};impact.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{20f},damageType=magic}}};impact.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=slow}}};impact.impactVFX=Vfx("BileSplash","Fire/Fire_cartoon_poison",.55f);impact.impactVfxLifetime=.9f;
 spit.abilityName=new[]{"Гнилой плевок"};spit.description=new[]{"CD8с: желчь в скопление впереди, −25% скорости атаки и движения на4с. Альфа:5магического при прямом попадании +20по области2м, дальность9м."};spit.targetMode=SkillTargetMode.SmartUnit;spit.targetStrategy=SkillTargetStrategy.Cluster;spit.targetFrontAngle=160;spit.radius=new[]{2f};spit.castRange=new[]{9f};spit.cooldown=new[]{8f};spit.delivery=SkillDelivery.Projectile;spit.projectilePrefab=BileProjectile();spit.spawnSocket=SkillSocketType.Weapon;spit.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{5f},damageType=magic}}};spit.projectileImpact=new SkillProjectileImpactBlock{enabled=true,skill=impact};
 rite.abilityName=new[]{"Обряд Жертвенного Костра"};rite.description=new[]{"CD40с, цена20%текущегоHP. Союзные орки текущей волны горят6с: врагам вокруг15магического/с, себе5HP/с, при гибели40AoE. Альфа: аура2м сверх размера, взрыв2м магический; звери, огры и машины исключены."};rite.targetMode=SkillTargetMode.WholeTeam;rite.unitSelector=friends;rite.targetPrefabs=orcs;rite.includeSelf=true;rite.cooldown=new[]{40f};rite.selfCost=new SkillSelfCostBlock{enabled=true,percentOfCurrentHp=new[]{.2f}};rite.buff=new SkillBuffBlock{enabled=true,duration=new[]{6f},auraDamagePerSecond=new[]{15f},auraDamageType=magic,auraRadius=new[]{2f},auraSelector=enemies,selfBurnPerSecond=new[]{5f},detonateOnDeath=true,detonationPresentation=death,detonationDamage=new[]{40f},detonationRadius=new[]{2f},detonationDamageType=magic,detonationSelector=enemies,buffVFX=Vfx("SacrificialFire","Fire/Fire_cartoon_poison",.25f,true)};rite.castVFX=Vfx("BonfireRitual","Area_generic/Area_generic_green",.55f);rite.castVfxLifetime=1.2f;
 foreach(var a in new Ability[]{death,soul,harvest,blast,spit,impact,rite}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_tech_shields.png")};EditorUtility.SetDirty(a);}EditorUtility.SetDirty(slow);spit.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};rite.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_spell_fire_carpet.png")};
 Assign(new Ability[]{blast,spit,rite,soul});AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
 static Projectile BileProjectile(){const string path="Assets/Resources/Projectiles/Korgal_Bile.prefab";var old=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(old)return old.GetComponent<Projectile>();var root=new GameObject("Korgal_Bile");try{var p=root.AddComponent<Projectile>();p.id=Resources.LoadAll<GameObject>("Projectiles").Select(g=>g.GetComponent<Projectile>()).Where(x=>x).Select(x=>x.id).DefaultIfEmpty(0).Max()+1;p.speed=8;p.ArcSpeedCurve=true;p.arcFactor=.12f;
 var ball=GameObject.CreatePrimitive(PrimitiveType.Sphere);ball.name="BileGlob";ball.transform.SetParent(root.transform,false);ball.transform.localScale=new Vector3(.22f,.22f,.35f);UnityEngine.Object.DestroyImmediate(ball.GetComponent<Collider>());var mat=new Material(Shader.Find("Universal Render Pipeline/Lit"));mat.SetColor("_BaseColor",new Color(.15f,.48f,.025f));mat.SetFloat("_Smoothness",.7f);mat.EnableKeyword("_EMISSION");mat.SetColor("_EmissionColor",new Color(.04f,.16f,.003f));AssetDatabase.CreateAsset(mat,V+"BileGlob.mat");ball.GetComponent<Renderer>().sharedMaterial=mat;
 var tr=ball.AddComponent<TrailRenderer>();tr.time=.18f;tr.startWidth=.18f;tr.endWidth=.015f;tr.sharedMaterial=mat;tr.minVertexDistance=.05f;p.renderObject=ball;return PrefabUtility.SaveAsPrefabAsset(root,path).GetComponent<Projectile>();}finally{UnityEngine.Object.DestroyImmediate(root);}}
 static void Assign(Ability[] abilities){const string path="Assets/Resources/UnitPrefabs/Units/Heroes/Orcs/Korgal.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var u=root.GetComponent<Unit>();u.abilities=abilities;u.abilityLevel=new int[abilities.Length];var animator=root.GetComponentInChildren<Animator>(true);string cp=A+"Korgal_Skills.controller";var ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(cp);if(!ctrl){AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),cp);ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(cp);}var sm=ctrl.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast)cast=sm.AddState("cast");var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");string clipPath=A+"Korgal_Cast.anim";var clip=AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);if(!clip){clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);AssetDatabase.CreateAsset(clip,clipPath);}AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);cast.motion=clip;cast.speed=clip.length/.9f;if(cast.transitions.Length==0){var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=ctrl;EditorUtility.SetDirty(ctrl);EditorUtility.SetDirty(clip);PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
}
#endif
