#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class OgreGladiatorSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit ogre,primary,near,ally,outside;static RageFromMissingHp rage;static CompositePassive giant,hammer;static DamageType physical;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start,baseArmor,baseAS,baseMS;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static OgreGladiatorSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("OgreGladiatorSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-ogregladiator.txt")){File.Delete(W+"run-ogregladiator.txt");Begin();return;}
 if(!SessionState.GetBool("OgreGladiatorSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.8f){Mechanics();phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.35f){Check(Mathf.Abs(ogre.moveSpeed-baseMS)<.001f,"Low HP immunity removes movement slow on native tick");Capture("ogregladiator-rage-immunity.png");Edges();ogre.canAttack=true;ogre.attackDamage=30;primary.SetHP(1000);near.SetHP(1000);ogre.SetHP(499);ogre.Attack(primary);phase=3;start=Time.time;return;}
 if(phase==3&&Time.time-start>5f){Check(primary.health<970,"Native animation attacks repeat with rage attack speed");Check(near.health<1000,"Native attack events apply hammer AoE");Capture("ogregladiator-native-hammer.png");ogre.canAttack=false;ogre.Hold();ogre.SetHP(1000);Check(Mathf.Abs(ogre.armor-baseArmor)<.001f&&Mathf.Abs(ogre.attackSpeed-baseAS)<.001f,"Full healing restores original armor and attack interval");Check(!ogre.effectors.Any(e=>e.effector==rage.ragePresentation||e.effector==giant.controlImmunity.presentation),"Full healing removes rage and immunity indicators");ogre.Die(-1,null,false);phase=4;start=Time.time;return;}
 if(phase==4&&Time.time-start>2f){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("Ogre")),"All Ogre skill visuals cleaned after death");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("OgreGladiatorSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}


 static Unit Spawn(Vector3 p,int owner,bool isOgre=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(isOgre?"Orcs/OgreGladiator":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=1000;u.SetHP(1000);if(!isOgre)u.armor=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
 foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
 ogre=Spawn(center,0,true);primary=Spawn(center+Vector3.forward*2,foeOwner);near=Spawn(center+Vector3.left*1.5f,foeOwner);ally=Spawn(center+Vector3.right*1.5f,0);outside=Spawn(center+Vector3.forward*6,foeOwner);
 rage=(RageFromMissingHp)ogre.abilities.First(a=>a.name=="OgreGladiator_SacrificialRage");giant=(CompositePassive)ogre.abilities.First(a=>a.name=="OgreGladiator_UnyieldingGiant");hammer=(CompositePassive)ogre.abilities.First(a=>a.name=="OgreGladiator_CrushingHammer");physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");baseArmor=ogre.armor;baseAS=ogre.attackSpeed;baseMS=ogre.moveSpeed;
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
 camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(6,7,-5);camera.transform.LookAt(center+new Vector3(0,.5f,1));camera.orthographic=true;camera.orthographicSize=5;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"ogregladiator-runtime-results.txt",results);}
 static void Hit(bool direct=true){ogre.DealDamage(primary,100,physical,direct,primary.transform.position);}
 static void Reset(){foreach(var u in new[]{primary,near,ally,outside})u.SetHP(1000);}
 static bool Immune()=>ogre.TryGetComponent<ControlImmunity>(out var ci)&&ci.Active;
 static void Mechanics(){Check(ogre.abilityLocked[Array.IndexOf(ogre.abilities,giant)]&&ogre.abilityLocked[Array.IndexOf(ogre.abilities,hammer)],"Both specializations initially locked");ogre.SetHP(901);Check(ogre.armor==baseArmor&&ogre.attackSpeed==baseAS,"No bonus before first complete 10 percent loss");ogre.SetHP(900);Check(Mathf.Abs(ogre.armor-baseArmor-2)<.001f&&Mathf.Abs(ogre.attackSpeed-baseAS/1.15f)<.001f,"First 10 percent loss gives two armor and 15 percent attack speed");ogre.SetHP(801);Check(Mathf.Abs(ogre.armor-baseArmor-2)<.001f,"Fractional step does not grant next bonus");ogre.SetHP(800);Check(Mathf.Abs(ogre.armor-baseArmor-4)<.001f&&Mathf.Abs(ogre.attackSpeed-baseAS/1.3f)<.001f,"20 percent loss gives four armor and 30 percent attack speed");ogre.SetHP(500);Check(Mathf.Abs(ogre.armor-baseArmor-10)<.001f&&Mathf.Abs(ogre.attackSpeed-baseAS/1.75f)<.001f,"Half HP grants ten armor and 75 percent attack speed");rage.Unlock(ogre,0,0);Check(Mathf.Abs(ogre.armor-baseArmor-10)<.001f,"Repeated unlock does not stack rage");ogre.SetHP(100);Check(!Immune(),"Low health alone cannot bypass locked immunity");TechnologyManager.instance.UnlockTech(giant.requiredTech[0].data[0],0);Check(Immune(),"Unlock at low HP immediately grants immunity");ogre.SetHP(200);Check(!Immune(),"Exactly 20 percent is outside below-threshold immunity");ogre.SetHP(199);Check(Immune(),"Below 20 percent immediately gains control immunity");ogre.Stun(1);Check(!ogre.stunned,"Low HP giant resists stun");var pos=ogre.transform.position;Knockback.Apply(ogre,primary.transform.position,2,0,true);Check(ogre.transform.position==pos,"Low HP giant resists knockback");var slow=AssetDatabase.LoadAssetAtPath<Effector>("Assets/Resources/Effectors/Roster/Orcs/OrcWarrior/OrcWarrior_Hamstrung.asset");Effector.EffectorAdd(ogre,slow,primary,foeOwner);Check(ogre.moveSpeed<baseMS,"Test slow was applied before immunity tick");}
 static void Edges(){TechnologyManager.instance.LockTech(giant.requiredTech[0].data[0],0);Check(!Immune(),"Lock removes only own immunity contribution");TechnologyManager.instance.UnlockTech(giant.requiredTech[0].data[0],0);ogre.SetHP(500);Reset();Hit();Check(near.health==1000,"Locked hammer cannot cleave");TechnologyManager.instance.UnlockTech(hammer.requiredTech[0].data[0],0);Reset();Hit();Check(near.health==1000,"Exactly half HP does not activate hammer");ogre.SetHP(499);Reset();Hit();Check(primary.health==900&&near.health==970,"Below half HP adds 30 percent around caster, primary not doubled");Check(ally.health==1000&&outside.health==1000,"Hammer excludes allies and distant targets");Reset();Hit(false);Check(near.health==1000,"Indirect damage cannot recursively trigger hammer");var other=Spawn(center+Vector3.back*4,0,true);var ownArmor=other.armor;other.SetHP(700);Check(Mathf.Abs(other.armor-ownArmor-6)<.001f&&Mathf.Abs(ogre.armor-baseArmor-10)<.001f,"Concurrent ogres keep independent missing-health stat contributions");other.SetHP(100);other.Die(-1,null,false);Check(other.dead,"Death during rage and immunity safely completes");ogre.SetHP(1000);ogre.Stun(.2f);Check(ogre.stunned,"Healing above threshold restores vulnerability to control");}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("Ogre")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}


 static void Finish(){File.WriteAllLines(W+"ogregladiator-runtime-results.txt",results);File.WriteAllLines(W+"ogregladiator-runtime-errors.txt",errors);File.WriteAllText(W+"ogregladiator-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("OgreGladiatorSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif
