#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class OgreGladiatorSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/OgreGladiator/";
 const string V="Assets/VFX/Skills/OgreGladiator/";
 const string A="Assets/Models/Units/Orcs/OgreGladiator/Animations/";
 static OgreGladiatorSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-ogregladiator.txt"))return;try{File.Delete(W+"configure-ogregladiator.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"ogregladiator-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"ogregladiator-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name,string label,VFXReferencer vfx){const string E="Assets/Resources/Effectors/Roster/Orcs/OgreGladiator/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}e.displayName=label;e.VFX=vfx;e.permanent=true;e.stacks=false;e.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_stat_damage.png");EditorUtility.SetDirty(e);return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);
 var rage=Asset<RageFromMissingHp>("OgreGladiator_SacrificialRage");var giant=Asset<CompositePassive>("OgreGladiator_UnyieldingGiant");var hammer=Asset<CompositePassive>("OgreGladiator_CrushingHammer");var hit=Asset<CompositeSkill>("OgreGladiator_HammerVisual");
 rage.abilityName=new[]{"Ярость Жертвы"};rage.description=new[]{"За каждые полные 10% потерянного здоровья: +2 брони и +15% скорости атаки."};rage.missingHpStep=.1f;rage.armorByMissingHp=AnimationCurve.Linear(0,0,1,20);rage.attackSpeedByMissingHp=AnimationCurve.Linear(0,0,1,1.5f);rage.ragePresentation=Effect("OgreGladiator_Rage","Ярость Жертвы",Vfx("OgreRage","States/Aura_acceleration",.65f,true));rage.presentationMissingHpThreshold=.1f;
 giant.abilityName=new[]{"Непреклонный Гигант"};giant.description=new[]{"Ниже 20% здоровья невосприимчив к оглушению, замедлению и отбрасыванию."};giant.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{Tech("Orki_T6_A1","Непреклонный Гигант")}}};giant.controlImmunity=new PassiveControlImmunityBlock{enabled=true,casterHpBelow=.2f,presentation=Effect("OgreGladiator_Unyielding","Непреклонный Гигант",Vfx("OgreUnyielding","Shields/Shield_wind",.8f,true))};giant.slowImmunity=new PassiveSlowImmunityBlock{enabled=true,casterHpBelow=.2f,alsoRemoveAttackSlow=true};
 hammer.abilityName=new[]{"Сокрушающий Молот"};hammer.description=new[]{"Ниже 50% здоровья каждая атака наносит 30% урона соседним противникам вокруг Огра. Радиус для альфы: 2 м."};hammer.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{Tech("Orki_T6_A2","Сокрушающий Молот")}}};hammer.cleave=new PassiveCleaveBlock{enabled=true,centerOnCaster=true,casterHpBelow=.5f,radius=2,damageFraction=.3f,hitPresentation=hit};
 hit.targetMode=SkillTargetMode.SmartUnit;hit.procAnimationState="";hit.spawnSocket=SkillSocketType.None;hit.impactVFX=Vfx("OgreHammerImpact","Slash/Hit_stone",.5f);hit.impactVfxLifetime=.65f;
 foreach(var v in new[]{rage.ragePresentation.VFX,giant.controlImmunity.presentation.VFX}){var path=AssetDatabase.GetAssetPath(v);var root=PrefabUtility.LoadPrefabContents(path);try{foreach(var ps in root.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.startDelay=0;m.maxParticles=Mathf.Min(m.maxParticles,30);}PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
 const string M="Assets/VFX/Skills/OgreGladiator/Materials/";InterflowEditorUI.EnsureFolder(M);
 var immunityPath=AssetDatabase.GetAssetPath(giant.controlImmunity.presentation.VFX);var immunityRoot=PrefabUtility.LoadPrefabContents(immunityPath);try{
 immunityRoot.transform.GetChild(0).localScale=Vector3.one*.65f;
 foreach(var ps in immunityRoot.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.startColor=new Color(.7f,.76f,.8f,.35f);var color=ps.colorOverLifetime;if(color.enabled){var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(new Color(.7f,.76f,.8f),0),new GradientColorKey(new Color(.7f,.76f,.8f),1)},new[]{new GradientAlphaKey(0,0),new GradientAlphaKey(.55f,.15f),new GradientAlphaKey(.55f,.8f),new GradientAlphaKey(0,1)});color.color=gradient;}}
 foreach(var renderer in immunityRoot.GetComponentsInChildren<Renderer>(true)){var materials=renderer.sharedMaterials;for(int i=0;i<materials.Length;i++){var source=materials[i];if(!source)continue;var path=M+source.name.Replace("Ogre_","")+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(source);mat.name="Ogre_"+source.name;AssetDatabase.CreateAsset(mat,path);for(int j=0;j<mat.shader.GetPropertyCount();j++){if(mat.shader.GetPropertyType(j)!=UnityEngine.Rendering.ShaderPropertyType.Color)continue;var property=mat.shader.GetPropertyName(j);var old=mat.GetColor(property);if(old.maxColorComponent<.01f)continue;mat.SetColor(property,new Color(.6f,.67f,.7f,old.a*.45f));}EditorUtility.SetDirty(mat);}materials[i]=mat;}renderer.sharedMaterials=materials;}
 PrefabUtility.SaveAsPrefabAsset(immunityRoot,immunityPath);}finally{PrefabUtility.UnloadPrefabContents(immunityRoot);}
 foreach(var a in new Ability[]{rage,giant,hammer,hit}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_stat_damage.png")};EditorUtility.SetDirty(a);}
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/OgreGladiator.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=rage&&a!=giant&&a!=hammer).Concat(new Ability[]{rage,giant,hammer}).ToArray();u.abilityLevel=new int[u.abilities.Length];PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
