#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class OrcCatapultSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/OrcCatapult/";
 const string V="Assets/VFX/Skills/OrcCatapult/";
 const string A="Assets/Models/Units/Orcs/OrcCatapult/Animations/";
 static OrcCatapultSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-orccatapult.txt"))return;try{File.Delete(W+"configure-orccatapult.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"orccatapult-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"orccatapult-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name){const string E="Assets/Resources/Effectors/Roster/Orcs/OrcCatapult/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}return e;}
 static UnitSelector Enemies()=>new UnitSelector{isEnemy=true,isUnit=true,isBuilding=true,isGround=true,isWater=true};
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);
 var boulder=Asset<EveryNthAttack>("OrcCatapult_BurningBoulder");var impact=Asset<CompositeSkill>("OrcCatapult_BoulderImpact");var breaker=Asset<BonusDamageVsUnitType>("OrcCatapult_Wallbreaker");var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");var tarTech=Tech("Orki_T3_A1","Смоляная Зарядка");var wallTech=Tech("Orki_T3_A2","Стенобит");
 var tar=Effect("OrcCatapult_Tar");tar.displayName="Горящая смола";tar.duration=.3f;tar.stacks=false;tar.passiveEffectsOn=true;tar.passiveEffects=new AbilityPassiveEffects{moveSpeedPercentageChange=-.35f,exactPercentageReductions=true};tar.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_status_slow.png");EditorUtility.SetDirty(tar);
 string zonePath=V+"BurningGround.prefab";var zoneAsset=AssetDatabase.LoadAssetAtPath<GameObject>(zonePath);if(!zoneAsset){var root=new GameObject("BurningGround");try{var zone=root.AddComponent<GroundDamageZone>();var so=new SerializedObject(zone);so.FindProperty("radius").floatValue=2;so.FindProperty("damagePerSecond").floatValue=10;so.FindProperty("duration").floatValue=4;so.FindProperty("damageType").objectReferenceValue=magic;foreach(var n in new[]{"isEnemy","isUnit","isBuilding","isGround","isWater"})so.FindProperty("targetSelector").FindPropertyRelative(n).boolValue=true;var c=so.FindProperty("conditionalEffectors");c.arraySize=1;c.GetArrayElementAtIndex(0).FindPropertyRelative("effector").objectReferenceValue=tar;c.GetArrayElementAtIndex(0).FindPropertyRelative("requiredTechnology").objectReferenceValue=tarTech;so.ApplyModifiedPropertiesWithoutUndo();
 for(int i=0;i<5;i++){var v=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/Fire/Fire_cartoon_simple.prefab"));v.transform.SetParent(root.transform,false);v.transform.localPosition=i==0?Vector3.zero:new Vector3(Mathf.Cos((i-1)*Mathf.PI/2)*1.25f,0,Mathf.Sin((i-1)*Mathf.PI/2)*1.25f);v.transform.localScale=new Vector3(.5f,.3f,.5f);foreach(var ps in v.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=true;m.startDelay=0;m.startLifetime=.7f;m.maxParticles=16;var e=ps.emission;e.rateOverTime=8;}}
 zoneAsset=PrefabUtility.SaveAsPrefabAsset(root,zonePath);}finally{UnityEngine.Object.DestroyImmediate(root);}}
 impact.abilityName=new[]{"Горящий Валун — падение"};impact.targetMode=SkillTargetMode.SmartPoint;impact.unitSelector=Enemies();impact.castTime=new[]{0f};impact.cooldown=new[]{0f};impact.manaCost=new[]{0f};impact.radius=new[]{2f};impact.spawnSocket=SkillSocketType.None;impact.procAnimationState="";impact.groundZone=new SkillGroundZoneBlock{enabled=true,zonePrefab=zoneAsset};impact.knockback=new SkillKnockbackBlock{enabled=true,distance=1.2f,maxTier=2,categories=new[]{Unit.UnitCategory.Fighter,Unit.UnitCategory.Tank,Unit.UnitCategory.Shooter,Unit.UnitCategory.Mage}};impact.impactVFX=Vfx("BoulderExplosion","Fire/Fire_explosion_earth",.8f);impact.impactVfxLifetime=1.2f;
 boulder.abilityName=new[]{"Горящий Валун"};boulder.description=new[]{"Попадание оставляет огонь на 4 секунды и отбрасывает пехоту Т1–Т2. Смоляная Зарядка: враги в огне замедлены на 35%."};boulder.everyN=1;boulder.procAtProjectileImpact=true;boulder.onProcSkill=impact;boulder.onlyDirectAttack=true;breaker.abilityName=new[]{"Стенобит"};breaker.damageMultiplier=new[]{1.6f};breaker.targetUnitType=UnitType.Building;breaker.onlyDirectAttack=true;breaker.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{wallTech}}};
 foreach(var a in new Ability[]{boulder,impact,breaker}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};EditorUtility.SetDirty(a);}
 const string path="Assets/Resources/UnitPrefabs/Units/Orcs/OrcCatapult.prefab";var go=PrefabUtility.LoadPrefabContents(path);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(x=>x&&x!=boulder&&x!=breaker).Concat(new Ability[]{boulder,breaker}).ToArray();u.abilityLevel=new int[u.abilities.Length];u.isSplash=true;u.splashRadius=2;u.splashReduction=1;u.projectileFollowTarget=false;u.splashUnitSelector=Enemies();u.preferAttackClusters=true;u.attackClusterRadius=2;
 string projectilePath="Assets/Resources/Projectiles/OrcCatapult_BurningBoulder.prefab";InterflowEditorUI.EnsureFolder("Assets/Resources/Projectiles");if(!AssetDatabase.LoadAssetAtPath<GameObject>(projectilePath)){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(u.projectileGO),projectilePath))throw new Exception("Projectile clone failed");var ball=PrefabUtility.LoadPrefabContents(projectilePath);try{var projectile=ball.GetComponent<Projectile>();projectile.id=Resources.LoadAll<GameObject>("Projectiles").Select(g=>g.GetComponent<Projectile>()).Where(c=>c).Select(c=>c.id).DefaultIfEmpty(0).Max()+1;var flame=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/Fire/Fire_small.prefab"));flame.transform.SetParent(projectile.renderObject?projectile.renderObject.transform:ball.transform,false);flame.transform.localScale=Vector3.one*.35f;foreach(var ps in flame.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=true;m.startDelay=0;m.maxParticles=20;}PrefabUtility.SaveAsPrefabAsset(ball,projectilePath);}finally{PrefabUtility.UnloadPrefabContents(ball);}}
 u.projectileGO=AssetDatabase.LoadAssetAtPath<GameObject>(projectilePath);PrefabUtility.SaveAsPrefabAsset(go,path);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
