#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class OrcSlaverSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,warrior,wolf,ogre,wrong,enemy,rear,second;static CompositeSkill whip;static Technology haste,sacrifice;static AutoAbilityUser auto;static int phase,foeOwner,casts;static float start,damage,speed;static double boot;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static OrcSlaverSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string m,string s,LogType t){if(SessionState.GetBool("OrcSlaverSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(m+"\n"+s);}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-orcslaver.txt")){File.Delete(W+"run-orcslaver.txt");Begin();return;}
 if(!SessionState.GetBool("OrcSlaverSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.5f){Check(whip.IsEligibleTarget(warrior,0,caster)&&whip.IsEligibleTarget(wolf,0,caster)&&whip.IsEligibleTarget(ogre,0,caster),"Warrior wolf and ogre allowed");Check(!whip.IsEligibleTarget(wrong,0,caster)&&!whip.IsEligibleTarget(enemy,0,caster)&&!whip.IsEligibleTarget(rear,0,caster)&&!whip.IsEligibleTarget(caster,0,caster),"Wrong prefab enemy rear ally and caster excluded");var picked=new HashSet<Unit>();for(int i=0;i<90;i++){CheckPick(whip.AutoCastReady(caster,0,out var t),t);if(t)picked.Add(t);}Check(picked.Count==3,"Random targeting samples all three eligible allies");Check(!Cast(wrong)&&!Cast(rear)&&!Cast(enemy),"Manual targeting obeys same filters");Check(Cast(warrior),"Native cast accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.6f){Check(Mathf.Abs(warrior.health-425)<.01f,"Whip removes fifteen percent current health");Check(Mathf.Abs(warrior.attackDamage-damage*1.4f)<.01f,"Whip grants forty percent attack damage");Check(warrior.attackSpeed==speed,"Locked specialization does not grant attack speed");Check(!Cast(wolf),"Cooldown blocks second cast");Capture("orcslaver-whip.png");phase=3;return;}
 if(phase==3&&Time.time-start>5.7f){Check(Mathf.Abs(warrior.attackDamage-damage)<.01f&&!warrior.GetComponent<SkillBuff>(),"Buff and damage expire after five seconds");Check(!caster.IsCooldownGood(Array.IndexOf(caster.abilities,whip),false),"Eight second cooldown outlasts buff");phase=4;return;}
 if(phase==4&&Time.time-start>8.8f){TechnologyManager.instance.UnlockTech(haste,0);Check(Cast(warrior),"Ability reusable after cooldown");phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>.7f){Check(Mathf.Abs(warrior.health-361.25f)<.01f,"Second cast uses current rather than max health");Check(Mathf.Abs(warrior.attackSpeed-speed/1.25f)<.01f,"Exhausting Whip grants twenty-five percent attack speed");caster.health=100;warrior.Die(foeOwner,enemy,false);Check(caster.health==100&&!caster.IsCooldownGood(Array.IndexOf(caster.abilities,whip),false),"Locked sacrifice gives no heal or reset");TechnologyManager.instance.LockTech(haste,0);TechnologyManager.instance.UnlockTech(sacrifice,0);Reset();Check(Cast(wolf),"Sacrifice specialization cast starts");phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>.7f){wolf.Die(foeOwner,enemy,false);Check(caster.health==600,"Buffed ally death heals caster fifty percent max health");Check(caster.IsCooldownGood(Array.IndexOf(caster.abilities,whip),false),"Buffed ally death resets native cooldown");Check(Cast(ogre),"Reset permits immediate reuse");Capture("orcslaver-sacrifice.png");phase=7;start=Time.time;return;}
 if(phase==7&&Time.time-start>5.8f){caster.health=100;caster.ChangeAbilityCooldown(8,Array.IndexOf(caster.abilities,whip),false);ogre.Die(foeOwner,enemy,false);Check(caster.health==100&&!caster.IsCooldownGood(Array.IndexOf(caster.abilities,whip),false),"Death after buff expiry gives no reward");Check(!whip.AutoCastReady(caster,0,out _),"No eligible target prevents autocast");warrior=Spawn("OrcWarrior",center+Vector3.forward*2,0);Reset();Check(Cast(warrior),"Cast begins before target death");warrior.Die(foeOwner,enemy,false);phase=8;start=Time.time;return;}
 if(phase==8&&Time.time-start>1){Check(caster.health==100,"Death during windup gives no unearned reward");warrior=Spawn("OrcWarrior",center+Vector3.forward*2,0);Reset();auto.enabled=true;casts=0;phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>10){auto.enabled=false;Check(casts>=2,"AutoAbilityUser performs repeated animated casts");Check(!caster.GetComponentInChildren<Animator>().GetCurrentAnimatorStateInfo(0).IsName("cast"),"Animator returns from cast");Capture("orcslaver-auto.png");second=Spawn("OrcSlaver",center+Vector3.left*2,0);second.health=100;Reset();whip.Use(caster,0,0,warrior);whip.Use(second,0,0,warrior);caster.health=100;warrior.Die(foeOwner,enemy,false);Check(second.health==600&&caster.health==100,"Refresh assigns death reward once to latest caster");Check(Mathf.Abs(second.attackDamage-AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Orcs/OrcSlaver.prefab").GetComponent<Unit>().attackDamage)<.01f,"Casting buff does not amplify caster");warrior=Spawn("OrcWarrior",center+Vector3.forward*2,0);Reset();Cast(warrior);caster.Die(foeOwner,enemy,false);phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>1){Check(warrior.health==500,"Caster death during cast cancels effect");Check(!Cast(warrior),"Dead caster cannot cast");whip.Use(second,0,0,warrior);second.Die(foeOwner,enemy,false);warrior.Die(foeOwner,enemy,false);phase=11;start=Time.time;return;}
 if(phase==11&&Time.time-start>7){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("WhipCast")||v.name.StartsWith("WhipImpact")||v.name.StartsWith("WhippedRage")||v.name.StartsWith("SacrificeReward")),"All temporary VFX clean up after deaths");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("OrcSlaverSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}

 static Unit Spawn(string name,Vector3 position,int owner){var p=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Orcs/"+name+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(p,position,0,owner);u.maxHealth=1000;u.health=500;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();var auto=u.GetComponent<AutoAbilityUser>();if(auto)auto.enabled=false;return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);caster=Spawn("OrcSlaver",center,0);warrior=Spawn("OrcWarrior",center+new Vector3(0,0,2),0);wolf=Spawn("WarWolf",center+new Vector3(-2,0,2),0);ogre=Spawn("OgreGladiator",center+new Vector3(2,0,2),0);wrong=Spawn("OrcWarlock",center+new Vector3(0,0,1),0);rear=Spawn("OrcWarrior",center+Vector3.back*2,0);enemy=Spawn("OrcWarrior",center+Vector3.forward*3,foeOwner);caster.LookAtInstant(new Vector2(center.x,center.z+2));whip=(CompositeSkill)caster.abilities.First(a=>a.name=="OrcSlaver_Whip");auto=caster.GetComponent<AutoAbilityUser>();haste=AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Orki_T4_A1.asset");sacrifice=AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Orki_T4_A2.asset");damage=warrior.attackDamage;speed=warrior.attackSpeed;Check(GameManager.instance.gameEffectors.ContainsKey(whip.effectors.records[0].effector.id),"Buff registered in native effectors registry");SkillPresentationEvents.SkillFired+=(u,id,l,t,p)=>{if(u==caster&&id==whip.id)casts++;};foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(6,7,-5);camera.transform.LookAt(center+new Vector3(0,.5f,1));camera.orthographic=true;camera.orthographicSize=4.5f;}
 static void CheckPick(bool ok,Unit t){if(!ok||(t!=warrior&&t!=wolf&&t!=ogre))throw new Exception("Invalid autocast target");}
 static bool Cast(Unit target)=>caster.UseAbilityItem(Array.IndexOf(caster.abilities,whip),false,target,Vector3.zero);
 static void Reset()=>caster.ChangeAbilityCooldown(-1,Array.IndexOf(caster.abilities,whip),false);
 static void Check(bool ok,string message){results.Add((ok?"PASS ":"FAIL ")+message);if(!ok)errors.Add(message);File.WriteAllLines(W+"orcslaver-runtime-results.txt",results);}
 static void Capture(string name){var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"orcslaver-runtime-results.txt",results);File.WriteAllLines(W+"orcslaver-runtime-errors.txt",errors);File.WriteAllText(W+"orcslaver-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("OrcSlaverSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


