#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class OrcSlaverSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/OrcSlaver/";
 const string V="Assets/VFX/Skills/OrcSlaver/";
 const string A="Assets/Models/Units/Orcs/OrcSlaver/Animations/";
 static OrcSlaverSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-orcslaver.txt"))return;try{File.Delete(W+"configure-orcslaver.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"orcslaver-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"orcslaver-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name){const string E="Assets/Resources/Effectors/Roster/Orcs/OrcSlaver/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
var whip=Asset<CompositeSkill>("OrcSlaver_Whip");var reward=Asset<CompositeSkill>("OrcSlaver_SacrificeVisual");var hasteTech=Tech("Orki_T4_A1","Изнуряющая Плеть");var sacrifice=Tech("Orki_T4_A2","Жертвоприношение Вождя");
var damage=Effect("OrcSlaver_Whipped");damage.displayName="Под ударом кнута";damage.duration=5;damage.stacks=false;damage.passiveEffectsOn=true;damage.passiveEffects=new AbilityPassiveEffects{damagePercentageChange=.4f};damage.VFX=Vfx("WhippedRage","States/Aura_acceleration",.25f,true);damage.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_stat_damage.png");
var rageRoot=PrefabUtility.LoadPrefabContents(AssetDatabase.GetAssetPath(damage.VFX));try{rageRoot.transform.GetChild(0).localScale=Vector3.one*.5f;foreach(var ps in rageRoot.GetComponentsInChildren<ParticleSystem>(true)){var main=ps.main;main.startDelay=0;main.maxParticles=Mathf.Min(main.maxParticles,40);}PrefabUtility.SaveAsPrefabAsset(rageRoot,AssetDatabase.GetAssetPath(damage.VFX));}finally{PrefabUtility.UnloadPrefabContents(rageRoot);}
var haste=Effect("OrcSlaver_ExhaustingWhip");haste.displayName="Изнуряющая Плеть";haste.duration=5;haste.stacks=false;haste.passiveEffectsOn=true;haste.passiveEffects=new AbilityPassiveEffects{attackSpeedPercentageChange=.25f};haste.icon=damage.icon;
whip.abilityName=new[]{"Удар Кнутом"};whip.description=new[]{"Случайный Орк, Волк или Огр впереди теряет 15% текущего здоровья и получает +40% урона атаки на 5 секунд. Изнуряющая Плеть: +25% скорости атаки. Жертвоприношение Вождя: гибель носителя лечит Погонщика на 50% максимального здоровья и сбрасывает откат."};whip.maxLevels=1;whip.targetMode=SkillTargetMode.SmartUnit;whip.targetStrategy=SkillTargetStrategy.RandomOne;whip.targetFrontAngle=180;whip.targetPrefabs=new[]{"OrcWarrior","WarWolf","OgreGladiator"}.Select(n=>AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Orcs/"+n+".prefab").GetComponent<Unit>()).Concat(new[]{AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Heroes/Orcs/Gurtag.prefab").GetComponent<Unit>()}).ToArray();whip.unitSelector=new UnitSelector{isOwn=true,isAlly=true,isUnit=true,isGround=true};whip.castRange=new[]{4f};whip.castTime=new[]{.45f};whip.cooldown=new[]{8f};whip.manaCost=new[]{0f};whip.drain=new SkillDrainBlock{enabled=true,percentOfCurrentHp=new[]{.15f}};whip.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=damage,duration=new[]{5f}},new SkillEffectorRecord{effector=haste,duration=new[]{5f},requiredTechnology=hasteTech}}};
whip.buff=new SkillBuffBlock{enabled=true,duration=new[]{5f},rewardCasterOnDeath=true,deathRewardTechnology=sacrifice,deathRewardHealFraction=new[]{.5f},deathRewardResetCooldown=true,deathRewardPresentation=reward};whip.spawnSocket=SkillSocketType.RightHand;whip.castVFX=Vfx("WhipCast","Range_attack/Hit_wind",.15f);whip.castVfxLifetime=.45f;whip.impactVFX=Vfx("WhipImpact","Slash/Hit_stone",.4f);whip.impactVfxLifetime=.7f;
reward.targetMode=SkillTargetMode.Self;reward.procAnimationState="";reward.spawnSocket=SkillSocketType.None;reward.impactVFX=Vfx("SacrificeReward","Regeneration/Regeneration_health",.65f);reward.impactVfxLifetime=1.2f;
foreach(var a in new Ability[]{whip,reward}){a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};EditorUtility.SetDirty(a);}EditorUtility.SetDirty(damage);EditorUtility.SetDirty(haste);
const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/OrcSlaver.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=whip).Concat(new Ability[]{whip}).ToArray();u.abilityLevel=new int[u.abilities.Length];var auto=go.GetComponent<AutoAbilityUser>()??go.AddComponent<AutoAbilityUser>();var so=new SerializedObject(auto);var list=so.FindProperty("autoAbilities");list.arraySize=1;list.GetArrayElementAtIndex(0).objectReferenceValue=whip;so.ApplyModifiedPropertiesWithoutUndo();
var animator=go.GetComponentInChildren<Animator>(true);var sockets=go.GetComponent<CharacterSockets>()??go.AddComponent<CharacterSockets>();var hand=animator.isHuman?animator.GetBoneTransform(HumanBodyBones.RightHand):go.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name=="Hand_R"||t.name=="RightHand"||t.name=="hand_r");if(!hand)throw new Exception("Missing hand");var sd=new SerializedObject(sockets);sd.FindProperty("rightHand").objectReferenceValue=hand;sd.ApplyModifiedPropertiesWithoutUndo();
string controllerPath=A+"OrcSlaver_Skills.controller";var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);if(!controller){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),controllerPath))throw new Exception("Cannot copy animator");controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);}var sm=controller.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");var clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);clip.name="OrcSlaver_WhipCast";AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);AssetDatabase.CreateAsset(clip,A+"OrcSlaver_WhipCast.anim");cast=sm.AddState("cast");cast.motion=clip;cast.speed=clip.length/.75f;var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=controller;EditorUtility.SetDirty(controller);File.WriteAllLines(W+"orcslaver-animation.txt",sm.states.Select(x=>x.state.name+" | "+(x.state.motion?x.state.motion.name:"none")));PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
}
}
#endif

