#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class OrcWarlockSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/OrcWarlock/";
 const string V="Assets/VFX/Skills/OrcWarlock/";
 const string A="Assets/Models/Units/Orcs/OrcWarlock/Animations/";
 static OrcWarlockSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-orcwarlock.txt"))return;try{File.Delete(W+"configure-orcwarlock.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"orcwarlock-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"orcwarlock-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static Effector Effect(string name){const string E="Assets/Resources/Effectors/Roster/Orcs/OrcWarlock/";InterflowEditorUI.EnsureFolder(E);var e=AssetDatabase.LoadAssetAtPath<Effector>(E+name+".asset");if(!e){e=ScriptableObject.CreateInstance<Effector>();e.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(e,E+name+".asset");}return e;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);
 var fire=Asset<EveryNthAttack>("OrcWarlock_Fireball");var hit=Asset<CompositeSkill>("OrcWarlock_FireballHit");var curse=Asset<CompositeSkill>("OrcWarlock_Curse");var splashVisual=Asset<CompositeSkill>("OrcWarlock_SplashVisual");
 var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");var caustic=Tech("Orki_T2_A1","Едкое Проклятие");var splash=Tech("Orki_T2_A2","Огненный Всплеск");
 var armor=Effect("OrcWarlock_ArmorCurse");armor.displayName="Проклятие резистов";armor.description="Броня снижена на 3.";armor.duration=5;armor.stacks=false;armor.passiveEffectsOn=true;armor.passiveEffects=new AbilityPassiveEffects{armorChange=-3};armor.VFX=Vfx("ArmorCurse","Fog/Fog_poison",.18f,true);armor.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_stat_armor.png");
 var vulnerability=Effect("OrcWarlock_CausticCurse");vulnerability.displayName="Едкое Проклятие";vulnerability.description="Получаемый магический урон увеличен на 15%.";vulnerability.duration=5;vulnerability.stacks=false;vulnerability.incomingDamageType=magic;vulnerability.incomingDamageMultiplier=1.15f;vulnerability.icon=armor.icon;
 foreach(var a in new[]{hit,curse,splashVisual}){a.targetMode=SkillTargetMode.SmartUnit;a.unitSelector=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isWater=true,isAir=true,includeInvisible=true};a.castTime=new[]{0f};a.cooldown=new[]{0f};a.manaCost=new[]{0f};a.castRange=new[]{9f};a.procAnimationState="";a.spawnSocket=SkillSocketType.None;}
 fire.abilityName=new[]{"Фаербол"};fire.description=new[]{"Каждая четвертая атака наносит дополнительно 40 магического урона. Огненный Всплеск: двум ближайшим врагам рядом достается по 20 урона."};fire.everyN=4;fire.onlyDirectAttack=true;fire.onProcSkill=hit;fire.bonusDamageMultiplier=new[]{0f};
 hit.abilityName=new[]{"Фаербол — попадание"};hit.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{40f},damageType=magic}}};hit.impactVFX=Vfx("FireballImpact","Fire/Fire_explosion_air",.6f);hit.impactVfxLifetime=1.2f;
 splashVisual.impactVFX=Vfx("FireSplash","Range_attack/Hit_fire",.5f);splashVisual.impactVfxLifetime=.8f;
 hit.secondary=new SkillSecondaryBlock{enabled=true,requiredTechnology=splash,radius=3,selector=new UnitSelector{isEnemy=true,isUnit=true,isGround=true,isWater=true,isAir=true,includeInvisible=true},onlyAttackersOfTarget=false,maxSecondaryTargets=2,nearestFirst=true,applyWhenPrimaryDies=true,damagePercentOfBaseDamage=.5f,damageType=magic,hitPresentation=splashVisual};
 curse.abilityName=new[]{"Проклятие резистов"};curse.description=new[]{"Снижает броню цели на 3 на 5 секунд. Едкое Проклятие дополнительно увеличивает получаемый магический урон на 15%."};curse.cooldown=new[]{10f};curse.castTime=new[]{.6f};curse.spawnSocket=SkillSocketType.RightHand;curse.castVFX=Vfx("CurseCast","Range_attack/Hit_dark_magic",.25f);curse.castVfxLifetime=.7f;curse.impactVFX=Vfx("CurseImpact","Range_attack/Hit_dark_magic",.45f);curse.impactVfxLifetime=.8f;curse.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=armor,power=new[]{1f},duration=new[]{5f}},new SkillEffectorRecord{effector=vulnerability,power=new[]{1f},duration=new[]{5f},requiredTechnology=caustic}}};
 foreach(var a in new Ability[]{fire,hit,curse,splashVisual}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_fireball.png")};EditorUtility.SetDirty(a);}EditorUtility.SetDirty(armor);EditorUtility.SetDirty(vulnerability);
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/OrcWarlock.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(x=>x&&x!=fire&&x!=curse&&AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(x))!="745d7ba2997971a49a5ae87f4199a234").Concat(new Ability[]{fire,curse}).ToArray();u.abilityLevel=new int[u.abilities.Length];var auto=go.GetComponent<AutoAbilityUser>()??go.AddComponent<AutoAbilityUser>();var so=new SerializedObject(auto);var list=so.FindProperty("autoAbilities");list.arraySize=1;list.GetArrayElementAtIndex(0).objectReferenceValue=curse;so.ApplyModifiedPropertiesWithoutUndo();
 var animator=go.GetComponentInChildren<Animator>(true);var sockets=go.GetComponent<CharacterSockets>()??go.AddComponent<CharacterSockets>();var hand=animator.isHuman?animator.GetBoneTransform(HumanBodyBones.RightHand):go.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name=="Hand_R"||t.name=="RightHand"||t.name=="hand_r");if(!hand)throw new Exception("Missing right hand bone");var socketData=new SerializedObject(sockets);socketData.FindProperty("rightHand").objectReferenceValue=hand;socketData.ApplyModifiedPropertiesWithoutUndo();
string controllerPath=A+"OrcWarlock_Skills.controller";var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);if(!controller){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),controllerPath))throw new Exception("Cannot copy caster animator");controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);}var sm=controller.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");var clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);clip.name="OrcWarlock_Cast";AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);AssetDatabase.CreateAsset(clip,A+"OrcWarlock_Cast.anim");cast=sm.AddState("cast");cast.motion=clip;cast.speed=clip.length/.7f;var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=controller;EditorUtility.SetDirty(controller);File.WriteAllLines(W+"orcwarlock-animation.txt",sm.states.Select(x=>x.state.name+" | "+(x.state.motion?x.state.motion.name:"none")));PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
