#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class OrcWarlockSkillRuntimeCheck
{
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,near,far,foe,outside,third;static EveryNthAttack fire;static CompositeSkill curse;static Technology caustic,splash;static DamageType physical,magic;static AutoAbilityUser auto;static float start,hp;static int phase,foeOwner,casts;static double boot;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static OrcWarlockSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("OrcWarlockSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
  if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
  if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-orcwarlock.txt")){try{File.Delete(W+"run-orcwarlock.txt");}catch(IOException){return;}Begin();return;}
  if(!SessionState.GetBool("OrcWarlockSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
  if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}

  if(phase==1&&Time.time-start>1){NthTest();Check(Cast(foe),"Curse accepted through unit workflow");phase=2;start=Time.time;return;}
  if(phase==2&&Time.time-start>.2f){Check(foe.armor==10,"Curse waits for cast animation");Check(caster.hasCastAnim,"Dedicated cast state discovered");Capture("orcwarlock-casting.png");phase=3;return;}
  if(phase==3&&Time.time-start>1.2f){Check(foe.armor==7,"Curse subtracts three armor");Check(near.armor==10,"Curse excludes nearby units");hp=foe.health;foe.GetDamage(100,magic,0,caster,false,out _);Check(Mathf.Abs(hp-foe.health-100)<.01f,"Locked caustic specialization leaves magic damage unchanged");Check(caster.GetAbilityCooldown(Array.IndexOf(caster.abilities,curse),false)>8,"Ten second cooldown running");Check(!Cast(foe),"Cooldown rejects repeat");Capture("orcwarlock-curse.png");phase=4;return;}
  if(phase==4&&Time.time-start>6){Check(foe.armor==10,"Five second curse restores armor");Check(caster.unitState!=UnitStates.AbilityCasting,"Caster leaves cast state");TechnologyManager.instance.UnlockTech(caustic,0);TechnologyManager.instance.UnlockTech(splash,0);SplashTests();auto.enabled=true;phase=5;start=Time.time;return;}
  if(phase==5&&Time.time-start>.15f){Capture("orcwarlock-fireball.png");phase=6;return;}
  if(phase==6&&Time.time-start>6){auto.enabled=false;Check(casts>=2,"Autocast repeats after cooldown");Check(foe.effectors.Any(x=>x.effector.name=="OrcWarlock_CausticCurse"),"Unlocked caustic effect applied");hp=foe.health;foe.GetDamage(100,magic,0,caster,false,out _);Check(Mathf.Abs(hp-foe.health-115)<.01f,"Caustic increases received magic damage fifteen percent");phase=7;start=Time.time;return;}
  if(phase==7&&Time.time-start>11){Check(foe.armor==10,"Autocast curse expires");hp=foe.health;foe.GetDamage(100,magic,0,caster,false,out _);Check(Mathf.Abs(hp-foe.health-100)<.01f,"Vulnerability removed on expiry");Check(Cast(foe),"Curse reusable");foe.Die(0,caster,false);phase=8;start=Time.time;return;}
  if(phase==8&&Time.time-start>1.5f){Check(caster.unitState!=UnitStates.AbilityCasting,"Target death during cast safely exits");EdgeTests();caster.canAttack=true;caster.attackDamage=10;near.health=10000;caster.Attack(near);phase=9;start=Time.time;return;}
  if(phase==9&&Time.time-start>9){Check(near.health<9960,"Ordinary animated projectiles hit target repeatedly");caster.canAttack=false;caster.Hold();foreach(var u in new[]{near,far,third,outside})if(u&&!u.dead)u.Die(0,caster,false);Check(!curse.AutoCastReady(caster,0,out _),"No eligible enemies prevents autocast");caster.Die(foeOwner,null,false);Check(!Cast(near),"Dead caster rejected");phase=10;start=Time.time;return;}
  if(phase==10&&Time.time-start>6){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("CurseCast")||v.name.StartsWith("CurseImpact")||v.name.StartsWith("ArmorCurse")||v.name.StartsWith("FireballImpact")||v.name.StartsWith("FireSplash")),"Spell and persistent visuals cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("OrcWarlockSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static Unit Spawn(Vector3 p,int owner,bool orcwarlock=false){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(orcwarlock?"Orcs/OrcWarlock":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(prefab,p,0,owner);u.maxHealth=1000;u.health=500;u.armor=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  caster=Spawn(center,0,true);foe=Spawn(center+Vector3.forward*3,foeOwner);near=Spawn(center+new Vector3(1,0,3),foeOwner);far=Spawn(center+new Vector3(-1.7f,0,3),foeOwner);third=Spawn(center+new Vector3(2.5f,0,3),foeOwner);outside=Spawn(center+Vector3.forward*7,foeOwner);
  fire=(EveryNthAttack)caster.abilities.First(a=>a.name=="OrcWarlock_Fireball");curse=(CompositeSkill)caster.abilities.First(a=>a.name=="OrcWarlock_Curse");auto=caster.GetComponent<AutoAbilityUser>();auto.enabled=false;caster.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));
  physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");caustic=AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Orki_T2_A1.asset");splash=AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Orki_T2_A2.asset");
  foreach(var u in new[]{foe,near,far,third,outside}){u.maxHealth=10000;u.health=10000;u.armor=10;}
  SkillPresentationEvents.SkillFired+=(u,id,l,t,pt)=>{if(u==caster&&id==curse.id)casts++;};
  Check(GameManager.instance.gameEffectors.ContainsKey(curse.effectors.records[0].effector.id)&&GameManager.instance.gameEffectors.ContainsKey(curse.effectors.records[1].effector.id),"Both curse effectors registered");
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(6,7,-5);camera.transform.LookAt(center+new Vector3(0,.5f,1));camera.orthographic=true;camera.orthographicSize=4.5f;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"orcwarlock-runtime-results.txt",results);}

 static bool Cast(Unit target)=>caster.UseAbilityItem(Array.IndexOf(caster.abilities,curse),false,target,Vector3.zero);
 static void Hit(Unit source,Unit victim,bool direct=true){source.DealDamage(victim,10,magic,direct,victim.transform.position);}
 static void NthTest(){Hit(caster,foe,false);for(int i=0;i<3;i++)Hit(caster,foe);Check(foe.health==9960,"First three direct hits have no bonus; indirect hit ignored");Hit(caster,foe);Check(foe.health==9910,"Fourth direct hit adds forty magic damage");Check(near.health==10000&&far.health==10000,"Locked splash leaves neighbours untouched");fire.Unlock(caster,0,0);Check(caster.OnAfterDamageDealCallbacks.Count(x=>x.Ability==fire)==1,"Unlock cannot duplicate every fourth attack callback");Check(!Cast(caster),"Enemy targeting rejects own unit");Check(Cast(null),"Button cast accepts native smart target selection");}
 static void SplashTests(){var ally=Spawn(foe.transform.position+Vector3.back*.5f,0);float hpA=near.health,hpB=far.health,hpC=third.health,hpD=outside.health;for(int i=0;i<4;i++)Hit(caster,foe);Check(near.health==hpA-20&&far.health==hpB-20,"Two nearest enemies receive half bonus damage");Check(third.health==hpC&&outside.health==hpD&&ally.health==500,"Third enemy, out of radius and ally excluded");ally.Die(-1,null,false);}
 static void EdgeTests(){var a=Spawn(center+Vector3.left,0,true);var b=Spawn(center+Vector3.right,0,true);a.GetComponent<AutoAbilityUser>().enabled=false;b.GetComponent<AutoAbilityUser>().enabled=false;near.health=10000;far.health=10000;for(int i=0;i<3;i++)Hit(a,near);Hit(b,far);Hit(a,near);Check(near.health==9920&&far.health==9970,"Concurrent casters maintain separate fourth-hit counters");for(int i=0;i<3;i++)Hit(a,near);near.health=20;float h=far.health;Hit(a,near);Check(near.dead&&far.health==h-20,"Splash occurs when bonus kills primary");near=Spawn(center+new Vector3(1,0,3),foeOwner);for(int i=0;i<2;i++)Hit(b,near);near.health=1;h=far.health;Hit(b,near);Check(near.dead&&far.health==h-20,"Splash occurs when ordinary hit already killed primary");near=Spawn(center+Vector3.forward*3,foeOwner);near.maxHealth=10000;near.health=10000;Check(a.UseAbilityItem(Array.IndexOf(a.abilities,curse),false,near,Vector3.zero),"Cast starts before caster death");a.Die(foeOwner,near,false);b.Die(foeOwner,near,false);}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("CurseCast")||v.name.StartsWith("CurseImpact")||v.name.StartsWith("ArmorCurse")||v.name.StartsWith("FireballImpact")||v.name.StartsWith("FireSplash")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"orcwarlock-runtime-results.txt",results);File.WriteAllLines(W+"orcwarlock-runtime-errors.txt",errors);File.WriteAllText(W+"orcwarlock-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("OrcWarlockSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


