#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class OrcWarriorSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Orcs/OrcWarrior/";
 const string V="Assets/VFX/Skills/OrcWarrior/";
 const string A="Assets/Models/Units/Orcs/OrcWarrior/Animations/";
 static OrcWarriorSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-orcwarrior.txt"))return;try{File.Delete(W+"configure-orcwarrior.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"orcwarrior-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"orcwarrior-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}



 static Technology Tech(string name,string label){var path="Assets/Resources/Technology/"+name+".asset";var t=AssetDatabase.LoadAssetAtPath<Technology>(path);if(!t){t=ScriptableObject.CreateInstance<Technology>();t.id=InterflowEditorUI.NextFreeId("t:Technology",o=>((Technology)o).id);t.displayName=label;AssetDatabase.CreateAsset(t,path);}return t;}
 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);
 var heavy=Asset<EveryNthAttack>("OrcWarrior_HeavyCleaver");var resilience=Asset<CompositePassive>("OrcWarrior_Resilience");var hit=Asset<CompositeSkill>("OrcWarrior_CleaverHit");var heal=Asset<CompositeSkill>("OrcWarrior_ResilienceVisual");
 var physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");var cannon=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/CannonDMGType.asset");if(!physical||!cannon)throw new Exception("Physical damage type missing");
 const string E="Assets/Resources/Effectors/Roster/Orcs/OrcWarrior/";InterflowEditorUI.EnsureFolder(E);var slow=AssetDatabase.LoadAssetAtPath<Effector>(E+"OrcWarrior_Hamstrung.asset");if(!slow){slow=ScriptableObject.CreateInstance<Effector>();slow.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(slow,E+"OrcWarrior_Hamstrung.asset");}slow.displayName="Подрезанные сухожилия";slow.duration=1.5f;slow.stacks=false;slow.passiveEffectsOn=true;slow.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_status_slow.png");slow.passiveEffects=new AbilityPassiveEffects{exactPercentageReductions=true,moveSpeedPercentageChange=-.2f};slow.VFX=Vfx("Hamstrung","States/Aura_slowdown",.14f,true);EditorUtility.SetDirty(slow);
 hit.targetMode=SkillTargetMode.SmartUnit;hit.unitSelector=new UnitSelector{isEnemy=true,isOwn=true,isAlly=true,isUnit=true,isGround=true,isWater=true,isAir=true,includeInvisible=true};hit.castTime=new[]{0f};hit.cooldown=new[]{0f};hit.castRange=new[]{100f};hit.manaCost=new[]{0f};hit.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=slow,power=new[]{1f},duration=new[]{1.5f}}}};hit.impactVFX=Vfx("CleaverImpact","Slash/Hit_stone",.55f);hit.impactVfxLifetime=.7f;hit.procAnimationState="";hit.spawnSocket=SkillSocketType.None;
 heal.targetMode=SkillTargetMode.Self;heal.impactVFX=Vfx("OrcResilience","Regeneration/Regeneration_health",.5f);heal.impactVfxLifetime=1.1f;heal.procAnimationState="";heal.spawnSocket=SkillSocketType.None;
 heavy.abilityName=new[]{"Тяжелый Тесак"};heavy.description=new[]{"Каждая третья атака наносит +30% физического урона и замедляет цель на 20% на 1.5 секунды."};heavy.everyN=3;heavy.bonusDamageMultiplier=new[]{.3f};heavy.bonusDamageType=physical;heavy.onlyDirectAttack=true;heavy.onProcSkill=hit;
 resilience.abilityName=new[]{"Орочья Стойкость"};resilience.description=new[]{"После физического урона восстанавливает 5% максимального HP. Перезарядка 6 секунд."};resilience.damageReaction=new PassiveDamageReactionBlock{enabled=true,damageTypes=new[]{physical,cannon},healMaxHpFraction=.05f,cooldown=6,presentation=heal};
 heavy.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{Tech("Orki_T1_A1","Тяжелый Тесак")}}};resilience.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{Tech("Orki_T1_A2","Орочья Стойкость")}}};
 foreach(var a in new Ability[]{heavy,resilience,hit,heal}){a.maxLevels=1;a.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_tech_shields.png")};EditorUtility.SetDirty(a);}
 const string prefab="Assets/Resources/UnitPrefabs/Units/Orcs/OrcWarrior.prefab";var root=PrefabUtility.LoadPrefabContents(prefab);try{var unit=root.GetComponent<Unit>();unit.abilities=(unit.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=heavy&&a!=resilience&&AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(a))!="745d7ba2997971a49a5ae87f4199a234").Concat(new Ability[]{heavy,resilience}).ToArray();unit.abilityLevel=new int[unit.abilities.Length];PrefabUtility.SaveAsPrefabAsset(root,prefab);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
