#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class OrcWarriorSkillRuntimeCheck
{
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,near,far,foe,outside;static EveryNthAttack heavy;static CompositePassive resilience;static DamageType physical,magic,cannon;static float baseSpeed;static float start,baseDamage;static int phase;static double boot;static int foeOwner;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static OrcWarriorSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("OrcWarriorSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
  if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
  if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-orcwarrior.txt")){try{File.Delete(W+"run-orcwarrior.txt");}catch(IOException){return;}Begin();return;}
  if(!SessionState.GetBool("OrcWarriorSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
  if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}

  if(phase==1&&Time.time-start>1){NthTest();phase=2;start=Time.time;return;}
  if(phase==2&&Time.time-start>.2f){Capture("orcwarrior-cleaver.png");phase=3;return;}
  if(phase==3&&Time.time-start>1.8f){Check(Mathf.Abs(foe.moveSpeed-baseSpeed)<.001f,"Slow restores movement after1.5sec");TechnologyManager.instance.LockTech(heavy.requiredTech[0].data[0],0);var hp=foe.health;for(int i=0;i<3;i++)Hit(caster,foe);Check(Mathf.Abs(foe.health-(hp-300))<.01f,"Locked cleaver no extra damage");TechnologyManager.instance.UnlockTech(heavy.requiredTech[0].data[0],0);foe.health=1000;caster.attackDamage=30;caster.canAttack=true;caster.Attack(foe);phase=4;start=Time.time;return;}
  if(phase==4&&Time.time-start>6){Check(foe.health<910,"Ordinary animation attacks repeatedly");Check(Mathf.Abs(foe.health%30-10)>.01f,"Animated attacks include boosted hit");caster.canAttack=false;caster.Hold();TechnologyManager.instance.LockTech(heavy.requiredTech[0].data[0],0);ReactionTest();phase=5;start=Time.time;return;}
  if(phase==5&&Time.time-start>.2f){Capture("orcwarrior-resilience.png");phase=6;return;}
  if(phase==6&&Time.time-start>6.2f){float hp=caster.health;caster.GetDamage(20,cannon,foeOwner,foe,false,out var damage);Check(Mathf.Abs(caster.health-(hp-damage+50))<.01f,"Cannon physical damage triggers after six seconds, indirect included");EdgeTests();phase=7;start=Time.time;return;}
  if(phase==7&&Time.time-start>2){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("CleaverImpact")||v.name.StartsWith("Hamstrung")||v.name.StartsWith("OrcResilience")),"Reaction and slow visuals cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("OrcWarriorSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static Unit Spawn(Vector3 p,int owner,bool orcwarrior=false){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(orcwarrior?"Orcs/OrcWarrior":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(prefab,p,0,owner);u.maxHealth=1000;u.health=500;u.armor=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  caster=Spawn(center,0,true);near=Spawn(center+Vector3.right,0);far=Spawn(center+Vector3.left*2,0);foe=Spawn(center+Vector3.forward*2,foeOwner);outside=Spawn(center+Vector3.forward*6,foeOwner);
  heavy=(EveryNthAttack)caster.abilities.First(a=>a.name=="OrcWarrior_HeavyCleaver");resilience=(CompositePassive)caster.abilities.First(a=>a.name=="OrcWarrior_Resilience");
  physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");cannon=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/CannonDMGType.asset");
  Check(caster.abilityLocked[Array.IndexOf(caster.abilities,heavy)]&&caster.abilityLocked[Array.IndexOf(caster.abilities,resilience)],"Both specializations tech locked");
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(6,7,-5);camera.transform.LookAt(center+new Vector3(0,.5f,1));camera.orthographic=true;camera.orthographicSize=4.5f;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"orcwarrior-runtime-results.txt",results);}

 static void Hit(Unit source,Unit victim,bool direct=true){source.DealDamage(victim,100,physical,direct,victim.transform.position);}
 static void NthTest(){foe.health=1000;Hit(caster,foe);Hit(caster,foe);Hit(caster,foe);Check(foe.health==700,"Locked cleaver leaves three basic attacks unchanged");TechnologyManager.instance.UnlockTech(heavy.requiredTech[0].data[0],0);foe.health=1000;Hit(caster,foe,false);Hit(caster,foe);Hit(caster,foe);Check(foe.health==700,"Indirect damage not counted toward third hit");baseSpeed=foe.moveSpeed;Hit(caster,foe);Check(Mathf.Abs(foe.health-570)<.01f,"Third direct attack adds thirty percent physical damage");Check(Mathf.Abs(foe.moveSpeed-baseSpeed*.8f)<.001f,"Third attack slows movement exactly twenty percent");Check(foe.effectors.Any(x=>x.effector.name=="OrcWarrior_Hamstrung"),"Registered hamstring effector applied");heavy.Unlock(caster,0,0);Check(caster.OnAfterDamageDealCallbacks.Count(x=>x.Ability==heavy)==1,"Duplicate unlock does not duplicate proc");}
 static void ReactionTest(){caster.health=500;caster.GetDamage(20,physical,foeOwner,foe,true,out _);Check(caster.health==480,"Locked resilience no heal");TechnologyManager.instance.UnlockTech(resilience.requiredTech[0].data[0],0);caster.GetDamage(20,magic,foeOwner,foe,true,out _);Check(caster.health==460,"Magic damage does not heal or consume cooldown");caster.GetDamage(20,physical,foeOwner,foe,true,out _);Check(caster.health==490,"Physical hit restores five percent maximum HP after damage");caster.GetDamage(20,physical,foeOwner,foe,true,out _);Check(caster.health==470,"Cooldown prevents immediate repeat heal");caster.GetDamage(0,physical,foeOwner,foe,true,out _);Check(caster.health==470,"Zero damage no heal");}
 static void EdgeTests(){var a=Spawn(center+Vector3.left,0,true);var b=Spawn(center+Vector3.right,0,true);a.GetDamage(20,physical,foeOwner,foe,true,out _);b.GetDamage(20,physical,foeOwner,foe,true,out _);Check(a.health==530&&b.health==530,"Concurrent warriors have independent heal cooldowns");TechnologyManager.instance.LockTech(resilience.requiredTech[0].data[0],0);float hp=a.health;a.GetDamage(20,physical,foeOwner,foe,true,out _);Check(a.health==hp-20,"Tech lock removes damage reaction");TechnologyManager.instance.UnlockTech(resilience.requiredTech[0].data[0],0);a.health=990;a.GetDamage(1,physical,foeOwner,null,false,out _);Check(a.health==1000,"No attacker required and heal capped");b.health=5;b.GetDamage(100,physical,foeOwner,foe,true,out _);Check(b.dead,"Lethal hit cannot be undone by resilience");a.Die(-1,null,false);Check(a.dead,"Caster death completes during reaction cooldown");TechnologyManager.instance.LockTech(resilience.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(heavy.requiredTech[0].data[0],0);a=Spawn(center,0,true);b=Spawn(center+Vector3.left,0,true);var x=Spawn(center+Vector3.forward*2,foeOwner);var y=Spawn(center+Vector3.forward*3,foeOwner);x.health=1000;y.health=1000;Hit(a,x);Hit(a,x);Hit(b,y);Hit(a,x);Check(x.health==670&&y.health==900,"Each attacker counts its own cleaver hits");x.health=1;Hit(a,x);Check(x.dead,"Target killed before proc safely exits");caster.Hold();Check(caster.unitState!=UnitStates.AbilityCasting,"Passive procs do not leave cast state");}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("CleaverImpact")||v.name.StartsWith("OrcResilience")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"orcwarrior-runtime-results.txt",results);File.WriteAllLines(W+"orcwarrior-runtime-errors.txt",errors);File.WriteAllText(W+"orcwarrior-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("OrcWarriorSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


