#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class PriestOfLightSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Humans/PriestOfLight/";
 const string V="Assets/VFX/Skills/PriestOfLight/";
 const string A="Assets/Models/Units/Humans/PriestOfLight/Animations/";
 static PriestOfLightSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-priestoflight.txt"))return;try{File.Delete(W+"configure-priestoflight.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"priestoflight-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"priestoflight-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}

 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);InterflowEditorUI.EnsureFolder("Assets/Resources/Effectors/Roster/Humans/PriestOfLight");
 var smite=Asset<CompositeSkill>("PriestOfLight_Smite");var shield=Asset<CompositeSkill>("PriestOfLight_SalvationShield");
 foreach(var s in new[]{smite,shield}){s.maxLevels=1;s.targetMode=SkillTargetMode.SmartUnit;s.castRange=new[]{9f};s.castTime=new[]{.6f};s.manaCost=new[]{0f};s.spawnSocket=SkillSocketType.RightHand;s.castVFX=Vfx("HolyCast","Range_attack/Hit_light",.25f);s.castVfxLifetime=.7f;}
 smite.abilityName=new[]{"Кара Небесная"};smite.description=new[]{"Столб света наносит 80 магического урона и ослепляет на 2 секунды: шанс промаха 50%."};smite.cooldown=new[]{6f};smite.targetStrategy=SkillTargetStrategy.Nearest;smite.unitSelector=new UnitSelector(false,false,true,true,false,false,false,true,true,true,false,false);smite.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{80f},damageType=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset"),targets=SkillDamageTargets.Enemies}}};smite.blind=new SkillBlindBlock{enabled=true,chance=new[]{.5f},duration=new[]{2f}};smite.impactVFX=Vfx("HolyColumn","Top_down_attack/top_down_beam_dot_purple",.45f);smite.impactVfxLifetime=1.5f;
 var effectPath="Assets/Resources/Effectors/Roster/Humans/PriestOfLight/PriestOfLight_Salvation.asset";var visual=AssetDatabase.LoadAssetAtPath<Effector>(effectPath);if(!visual){visual=ScriptableObject.CreateInstance<Effector>();visual.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(visual,effectPath);}visual.displayName="Щит Спасения";visual.description="Поглощает урон до 20% максимального здоровья. Исчезает при пробитии.";visual.duration=6;visual.VFX=Vfx("SalvationShield","Shields/Shield_gold",.65f,true);visual.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_tech_shields.png");EditorUtility.SetDirty(visual);
 shield.abilityName=new[]{"Щит Спасения"};shield.description=new[]{"Защищает ближайшего союзника с HP ниже 30% щитом на 20% максимального здоровья на 6 секунд."};shield.cooldown=new[]{9f};shield.targetStrategy=SkillTargetStrategy.NearestBelowThreshold;shield.strategyHpThreshold=.3f;shield.unitSelector=new UnitSelector(true,true,false,true,false,false,false,true,true,true,false,false);shield.shield=new SkillShieldBlock{enabled=true,percentOfMaxHp=new[]{.2f},duration=new[]{6f},skipIfAlreadyShielded=true,visualEffector=visual};shield.impactVFX=Vfx("ShieldArrival","Range_attack/Hit_light",.4f);shield.impactVfxLifetime=.8f;
 foreach(var pair in new[]{new[]{"HolyColumn",""}}){var root=PrefabUtility.LoadPrefabContents(V+pair[0]+".prefab");try{foreach(var ps in root.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.startDelay=0;m.simulationSpeed=2; m.startColor=new Color(1f,.9f,.6f,1f);var e=ps.emission;for(int i=0;i<e.burstCount;i++){var b=e.GetBurst(i);b.time=0;e.SetBurst(i,b);}if(ps.name.StartsWith("target_")||ps.name=="marker"||ps.name.Contains("electric"))ps.gameObject.SetActive(false);}InterflowEditorUI.EnsureFolder(V+"Materials");int index=0;foreach(var renderer in root.GetComponentsInChildren<ParticleSystemRenderer>(true)){var mats=renderer.sharedMaterials;for(int i=0;i<mats.Length;i++){if(!mats[i])continue;string path=V+"Materials/HolyColumn_"+(index++)+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(mats[i]);for(int k=0;k<ShaderUtil.GetPropertyCount(mat.shader);k++)if(ShaderUtil.GetPropertyType(mat.shader,k)==ShaderUtil.ShaderPropertyType.Color)mat.SetColor(ShaderUtil.GetPropertyName(mat.shader,k),new Color(1f,.85f,.45f,1f));AssetDatabase.CreateAsset(mat,path);}mats[i]=mat;}renderer.sharedMaterials=mats;}PrefabUtility.SaveAsPrefabAsset(root,V+pair[0]+".prefab");}finally{PrefabUtility.UnloadPrefabContents(root);}}
 smite.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_heal.png")};shield.icon=new[]{visual.icon};
 smite.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Lyudi_T3_B1.asset")}}};shield.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Lyudi_T3_B2.asset")}}};EditorUtility.SetDirty(smite);EditorUtility.SetDirty(shield);
 const string prefab="Assets/Resources/UnitPrefabs/Units/Humans/PriestOfLight.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(x=>x&&x!=smite&&x!=shield&&AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(x))!="745d7ba2997971a49a5ae87f4199a234").Concat(new Ability[]{smite,shield}).ToArray();u.abilityLevel=new int[u.abilities.Length];var auto=go.GetComponent<AutoAbilityUser>()??go.AddComponent<AutoAbilityUser>();var so=new SerializedObject(auto);var list=so.FindProperty("autoAbilities");list.arraySize=2;list.GetArrayElementAtIndex(0).objectReferenceValue=smite;list.GetArrayElementAtIndex(1).objectReferenceValue=shield;so.ApplyModifiedPropertiesWithoutUndo();
 var sockets=go.GetComponent<CharacterSockets>()??go.AddComponent<CharacterSockets>();var hand=go.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name=="Hand_R"||t.name=="RightHand"||t.name=="hand_r");if(!hand)throw new Exception("Missing right hand bone");var socketData=new SerializedObject(sockets);socketData.FindProperty("rightHand").objectReferenceValue=hand;socketData.ApplyModifiedPropertiesWithoutUndo();
 var animator=go.GetComponentInChildren<Animator>(true);string controllerPath=A+"PriestOfLight_Skills.controller";var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);if(!controller){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),controllerPath))throw new Exception("Cannot copy caster animator");controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);}var sm=controller.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");var clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);clip.name="PriestOfLight_Cast";AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);AssetDatabase.CreateAsset(clip,A+"PriestOfLight_Cast.anim");cast=sm.AddState("cast");cast.motion=clip;cast.speed=clip.length/.7f;var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=controller;EditorUtility.SetDirty(controller);File.WriteAllLines(W+"priestoflight-animation.txt",sm.states.Select(x=>x.state.name+" | "+(x.state.motion?x.state.motion.name:"none")));PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
