#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class PriestOfLightSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit archer,foe,foe2,ally,far,second;static CompositeSkill smite,shield;static AutoAbilityUser auto;static float start,speed,interval,hp;static int phase,foeOwner,smites,shields;static double boot;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static PriestOfLightSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("PriestOfLightSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void OnFired(Unit u,int id,int level,Unit target,Vector3 point){if(u!=archer)return;if(id==smite.id)smites++;if(id==shield.id)shields++;}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-priestoflight.txt")){try{File.Delete(W+"run-priestoflight.txt");}catch(IOException){return;}Begin();return;}
 if(!SessionState.GetBool("PriestOfLightSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}

 if(phase==1&&Time.time-start>1){Check(!Cast(smite,foe),"Locked Smite cannot cast");TechnologyManager.instance.UnlockTech(smite.requiredTech[0].data[0],0);Check(Cast(smite,foe),"Smite accepted through Unit workflow");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.2f){Check(foe.health==10000,"Smite waits for cast time");Check(archer.hasCastAnim,"Priest has cast animation");Check(archer.GetComponent<CharacterSockets>()!=null&&archer.GetComponent<CharacterSockets>().GetSocket(SkillSocketType.RightHand)!=archer.transform,"Cast origin bound to right hand");Capture("priestoflight-casting.png");phase=3;return;}
 if(phase==3&&Time.time-start>.75f){Check(Mathf.Abs(foe.health-9920)<.1f,"Smite deals 80 magic ignoring armor");Check(foe.GetComponent<BlindDebuff>()!=null,"Smite applies blind");int misses=0;for(int i=0;i<400;i++)if(InterflowCombat.ModifyIncomingDamage(ally,foe,null,1,true)==0)misses++;Check(misses>150&&misses<250,"Blind produces approximately 50 percent misses");Check(InterflowCombat.ModifyIncomingDamage(ally,foe,null,1,false)==1,"Blind does not suppress indirect spell damage");Check(foe2.health==10000&&ally.health==10000,"Smite excludes other targets");Check(archer.GetAbilityCooldown(Index(smite),false)>4,"Six-second cooldown running");Check(!Cast(smite,foe),"Cooldown prevents immediate reuse");Capture("priestoflight-smite.png");phase=4;return;}
 if(phase==4&&Time.time-start>3.2f){Check(foe.GetComponent<BlindDebuff>()==null,"Blind expires after two seconds");Check(!InterflowCombat.IsBlinded(foe),"Blind combat rule cleared");Check(archer.unitState!=UnitStates.AbilityCasting,"Animator and caster leave cast state");auto.enabled=true;phase=5;return;}
 if(phase==5&&Time.time-start>8f){auto.enabled=false;Check(smites>=2,"Autocast reuses Smite after cooldown");TechnologyManager.instance.LockTech(smite.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(shield.requiredTech[0].data[0],0);Check(!shield.AutoCastReady(archer,0,out var healthy),"Healthy allies do not trigger shield");ally.health=3000;Check(!shield.AutoCastReady(archer,0,out var boundary),"Exactly 30 percent HP does not trigger shield: hp="+ally.health.ToString("R")+" max="+ally.maxHealth.ToString("R")+" threshold="+shield.strategyHpThreshold.ToString("R")+" target="+(boundary?boundary.name:"none"));ally.health=2999;Check(shield.AutoCastReady(archer,0,out var target)&&target==ally,"Shield selects wounded ally below 30 percent");Check(!Cast(shield,foe),"Shield rejects enemy");Check(Cast(shield,ally),"Shield cast accepted");phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>1.2f){Check(AbsorbShield.IsActiveOn(ally),"Shield applied");Check(ally.effectors.Any(e=>e.effector==shield.shield.visualEffector),"Shield visual tied to protected ally");Check(!shield.IsEligibleTarget(ally,0),"Already shielded ally excluded");Capture("priestoflight-shield.png");hp=ally.health;ally.GetDamage(1500,AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset"),foeOwner,foe,false,out var absorbed);Check(Mathf.Abs(ally.health-hp)<.1f,"Shield absorbs first 1500 damage");ally.GetDamage(600,AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset"),foeOwner,foe,false,out var overflow);Check(Mathf.Abs(ally.health-(hp-100))<.1f,"Shield capacity exactly 20 percent max HP");phase=7;return;}
 if(phase==7&&Time.time-start>2f){Check(!AbsorbShield.IsActiveOn(ally),"Broken shield removed");Check(!ally.effectors.Any(e=>e.effector==shield.shield.visualEffector),"Broken shield removes visual early");Check(archer.GetAbilityCooldown(Index(shield),false)>6,"Nine-second shield cooldown running");phase=8;return;}
 if(phase==8&&Time.time-start>10f){Check(Cast(shield,ally),"Shield reusable after cooldown");phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>7.5f){Check(!AbsorbShield.IsActiveOn(ally),"Unbroken shield expires at six seconds");Check(!ally.effectors.Any(e=>e.effector==shield.shield.visualEffector),"Expiry removes shield visual");phase=10;return;}
 if(phase==10&&Time.time-start>10f){Check(Cast(shield,ally),"Shield can cast again after expiry");ally.health=5000;phase=11;start=Time.time;return;}
 if(phase==11&&Time.time-start>1.5f){Check(!AbsorbShield.IsActiveOn(ally),"Ally healed above threshold during cast gets no shield");Check(archer.unitState!=UnitStates.AbilityCasting,"Invalid target leaves caster free");TechnologyManager.instance.LockTech(shield.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(smite.requiredTech[0].data[0],0);Check(Cast(smite,foe),"Smite begins before target death");foe.Die(0,archer,false);phase=12;start=Time.time;return;}
 if(phase==12&&Time.time-start>2f){Check(archer.unitState!=UnitStates.AbilityCasting,"Target death does not trap caster");second=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/PriestOfLight.prefab").GetComponent<Unit>(),center+Vector3.left*2,0,0);second.canAttack=false;second.doNotLookForTargets=true;second.Hold();second.GetComponent<AutoAbilityUser>().enabled=false;phase=13;return;}
 if(phase==13&&Time.time-start>7f){hp=foe2.health;Check(Cast(smite,foe2)&&second.UseAbilityItem(Array.IndexOf(second.abilities,smite),false,foe2,Vector3.zero),"Two priests cast simultaneously");phase=14;start=Time.time;return;}
 if(phase==14&&Time.time-start>1.5f){Check(Mathf.Abs(hp-foe2.health-160)<.1f,"Concurrent Smite damage applied once each");Check(foe2.GetComponents<BlindDebuff>().Length==1,"Concurrent blind refreshes without duplicate components");TechnologyManager.instance.LockTech(smite.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(shield.requiredTech[0].data[0],0);ally.health=2000;Check(Cast(shield,ally),"Shield begins before caster death");phase=15;start=Time.time;return;}
 if(phase==15&&Time.time-start>1.2f){Check(AbsorbShield.IsActiveOn(ally),"Shield exists before caster death");archer.Die(foeOwner,foe2,false);Check(AbsorbShield.IsActiveOn(ally),"Caster death preserves already applied shield");ally.Die(foeOwner,foe2,false);phase=16;start=Time.time;return;}
 if(phase==16&&Time.time-start>3f){Check(!AbsorbShield.IsActiveOn(ally),"Target death removes shield");Check(!Cast(smite,foe2),"Dead priest cannot cast");foe2.Die(0,second,false);far.Die(0,second,false);Check(!smite.AutoCastReady(second,0,out var none),"No enemies produces no target");second.Die(foeOwner,null,false);phase=17;start=Time.time;return;}
 if(phase==17&&Time.time-start>4f){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("HolyCast")||v.name.StartsWith("HolyColumn")||v.name.StartsWith("SalvationShield")||v.name.StartsWith("ShieldArrival")),"All priest VFX cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static int Index(CompositeSkill s)=>Array.IndexOf(archer.abilities,s);
 static bool Cast(CompositeSkill s,Unit t)=>archer.UseAbilityItem(Index(s),false,s.targetMode==SkillTargetMode.SmartUnit?t:null,s.targetMode==SkillTargetMode.SmartPoint?t.transform.position:Vector3.zero);
 static Unit Spawn(Unit sample,Vector3 pos,int owner){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(prefab,pos,0,owner);u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("PriestOfLightSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/PriestOfLight.prefab").GetComponent<Unit>();archer=Unit.SpawnInternal(prefab,center,0,0);foe=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>(),center+Vector3.forward*3,0,foeOwner);
  foreach(var u in new[]{archer,foe}){u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();}
  archer.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));
  smite=(CompositeSkill)archer.abilities.First(a=>a.name=="PriestOfLight_Smite");shield=(CompositeSkill)archer.abilities.First(a=>a.name=="PriestOfLight_SalvationShield");auto=archer.GetComponent<AutoAbilityUser>();auto.enabled=false;
  foe2=Spawn(foe,center+new Vector3(1.5f,0,3),foeOwner);ally=Spawn(foe,center+new Vector3(-1.5f,0,3),0);far=Spawn(foe,center+new Vector3(0,0,8),foeOwner);foe2.attackDamage=500;foe2.attackSpeed=1;speed=foe.moveSpeed;interval=foe.attackSpeed;
  Check(GameManager.instance.gameEffectors.TryGetValue(shield.shield.visualEffector.id,out var registered)&&registered==shield.shield.visualEffector,"Shield effector registered for native network/save pipeline");
  SkillPresentationEvents.SkillFired+=OnFired;
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-5);camera.transform.LookAt(center+new Vector3(0,.5f,3));camera.orthographic=true;camera.orthographicSize=6;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"priestoflight-runtime-results.txt",results);}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("Smite")||v.name.StartsWith("Chilled")||v.name.StartsWith("FrostCast")).ToArray();var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"priestoflight-runtime-results.txt",results);File.WriteAllLines(W+"priestoflight-runtime-errors.txt",errors);File.WriteAllText(W+"priestoflight-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("PriestOfLightSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


