#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class RoyalArcherSkillRuntimeCheck
{
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit archer,foe;static CompositePassive pierce,range;static float start,attackHp;static int phase;static double boot;static int foeOwner;static Vector3 center;static Camera camera;static bool captured;static List<string> results=new List<string>(),errors=new List<string>();
 static RoyalArcherSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("RoyalArcherSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
  if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
  if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-royalarcher.txt")){try{File.Delete(W+"run-royalarcher.txt");}catch(IOException){return;}Begin();return;}
  if(!SessionState.GetBool("RoyalArcherSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
  if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}
  if(phase==1&&Time.time-start>1){PierceTest();phase=2;start=Time.time;return;}
  if(phase==2&&Time.time-start>.12f){Capture("royalarcher-pierce.png");phase=3;return;}
  if(phase==3&&Time.time-start>1){RangeTest();phase=4;start=Time.time;return;}
  if(phase==4){if(!captured&&Time.time-start>1&&UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("LongShotHit")&&v.GetComponentsInChildren<ParticleSystem>().Any(p=>p.particleCount>0))){Capture("royalarcher-longshot.png");captured=true;}if(Time.time-start>8){Check(foe.health<attackHp,"Ordinary arrow attacks deal damage at extended range");Check((archer.transform.position-center).sqrMagnitude<.25f,"Archer fires at distance 9 without walking closer");Check(captured,"Actual arrow impact produces specialization visual");DeathTests();phase=5;start=Time.time;}return;}
  if(phase==5&&Time.time-start>4){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("PiercingHit")||v.name.StartsWith("LongShotHit")),"Impact VFX cleaned up after death");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("RoyalArcherSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/RoyalArcher.prefab").GetComponent<Unit>();archer=Unit.SpawnInternal(prefab,center,0,0);foe=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>(),center+Vector3.forward*3,0,foeOwner);
  foreach(var u in new[]{archer,foe}){u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();}
  archer.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));
  pierce=(CompositePassive)archer.abilities.First(a=>a.name=="RoyalArcher_ArmorPierce");range=(CompositePassive)archer.abilities.First(a=>a.name=="RoyalArcher_LongShot");
  Check(archer.abilityLocked[Array.IndexOf(archer.abilities,pierce)]&&archer.abilityLocked[Array.IndexOf(archer.abilities,range)],"Both skills initially tech locked");
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-5);camera.transform.LookAt(center+new Vector3(0,.5f,3));camera.orthographic=true;camera.orthographicSize=6;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"royalarcher-runtime-results.txt",results);}
 static float Hit(){float hp=foe.health;archer.DealDamage(foe,100,archer.damageType,true,foe.transform.position+Vector3.up);return hp-foe.health;}
 static void PierceTest(){float baseline=Hit();TechnologyManager.instance.UnlockTech(pierce.requiredTech[0].data[0],0);float empowered=Hit();Check(Mathf.Abs(InterflowCombat.EffectiveArmor(foe,archer,10)-7)<.001f,"Armor pierce ignores exactly 30% armor");Check(Mathf.Abs(empowered/baseline-(1.6f/1.42f))<.002f,"Armor pierce increases actual damage according to armor formula");TechnologyManager.instance.UnlockTech(pierce.requiredTech[0].data[0],0);Check(Mathf.Abs(InterflowCombat.EffectiveArmor(foe,archer,10)-7)<.001f,"Repeated technology unlock does not stack pierce");}
 static void RangeTest(){TechnologyManager.instance.LockTech(pierce.requiredTech[0].data[0],0);Check(InterflowCombat.EffectiveArmor(foe,archer,10)==10,"Closing pierce restores armor calculation");float baseline=archer.attackRange;TechnologyManager.instance.UnlockTech(range.requiredTech[0].data[0],0);Check(Mathf.Abs(archer.attackRange-baseline*1.2f)<.001f,"Long shot adds exactly 20% range");TechnologyManager.instance.UnlockTech(range.requiredTech[0].data[0],0);Check(Mathf.Abs(archer.attackRange-baseline*1.2f)<.001f,"Repeated unlock does not stack range");TechnologyManager.instance.LockTech(range.requiredTech[0].data[0],0);Check(Mathf.Abs(archer.attackRange-baseline)<.001f,"Closing long shot restores range");TechnologyManager.instance.UnlockTech(range.requiredTech[0].data[0],0);foe.transform.position=center+Vector3.forward*9;attackHp=foe.health;archer.canAttack=true;archer.Attack(foe);}
 static void DeathTests(){archer.canAttack=false;archer.Hold();var shot=Projectile.Spawn(archer.owner,archer,archer.projectileGO.GetComponent<Projectile>(),archer.transform.position+Vector3.up,Quaternion.identity,foe,true,100,archer.damageType,true,false);Check(shot!=null,"Arrow in flight for death edge case");foe.Die(0,archer,false);archer.Die(foeOwner,foe,false);Check(foe.dead&&archer.dead,"Target and caster can die with arrow in flight");}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("PiercingHit")||v.name.StartsWith("LongShotHit")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"royalarcher-runtime-results.txt",results);File.WriteAllLines(W+"royalarcher-runtime-errors.txt",errors);File.WriteAllText(W+"royalarcher-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("RoyalArcherSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


