#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class SteelPaladinSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit archer,foe,foe2,ally,far,second;static CompositeSkill smite,shield;static AutoAbilityUser auto;static float start,speed,interval,hp;static int filmFrame;static int phase,foeOwner,smites,shields;static double boot;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static SteelPaladinSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("SteelPaladinSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void OnFired(Unit u,int id,int level,Unit target,Vector3 point){if(u!=archer)return;if(id==smite.id)smites++;if(id==shield.id)shields++;}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-steelpaladin.txt")){try{File.Delete(W+"run-steelpaladin.txt");}catch(IOException){return;}Begin();return;}
 if(!SessionState.GetBool("SteelPaladinSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}


 if((phase==2||phase==3)&&filmFrame<10&&Time.time-start>filmFrame*.1f){Capture("steelpaladin-frame-"+filmFrame+".png");filmFrame++;}
 if(phase==1&&Time.time-start>1){Check(!Cast(smite,null),"Locked smash rejected");TechnologyManager.instance.UnlockTech(smite.requiredTech[0].data[0],0);Check(smite.damage.entries[0].damageType!=null,"Physical damage asset assigned");Check(Cast(smite,null),"Ground smash accepted");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.2f){Check(foe.health==10000,"Damage waits for impact");Check(archer.hasCastAnim,"Paladin cast animation registered");Capture("steelpaladin-cast.png");phase=3;return;}
 if(phase==3&&Time.time-start>.8f){var dt=smite.damage.entries[0].damageType;float expected=80*GameManager.instance.damageToArmor[foe.armorType.index*GameManager.instance.DTAWidth+dt.index]/1.6f;Check(Mathf.Abs(10000-foe.health-expected)<.1f,"AoE deals 80 physical scaled by armor");Check(foe.stunned&&foe2.stunned,"Both nearby enemies stunned");Check(ally.health==10000&&!ally.stunned&&far.health==10000&&!far.stunned,"Allies and distant enemy excluded");Check(!Cast(smite,null)&&archer.GetAbilityCooldown(Index(smite),false)>6,"Smash cooldown eight seconds");Capture("steelpaladin-smash.png");phase=4;return;}
 if(phase==4&&Time.time-start>3.2f){Check(!foe.stunned&&!foe2.stunned,"Two-second stun expires");Check(archer.unitState!=UnitStates.AbilityCasting,"Cast leaves animation state");auto.enabled=true;phase=5;return;}
 if(phase==5&&Time.time-start>10){auto.enabled=false;Check(smites>=2,"Smash automatically repeats after cooldown");TechnologyManager.instance.LockTech(smite.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(shield.requiredTech[0].data[0],0);Check(!shield.AutoCastReady(archer,0,out _)&&!Cast(shield,null),"Healthy caster cannot trigger guard manually or automatically");archer.health=3000;Check(!shield.AutoCastReady(archer,0,out _),"Exactly thirty percent does not trigger");archer.health=2999;Check(shield.AutoCastReady(archer,0,out _),"Below thirty percent enables guard");Check(Cast(shield,null),"Guard begins");phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>1.1f){Check(Mathf.Abs(archer.armor-12.5f)<.01f&&Mathf.Abs(ally.armor-12.5f)<.01f,"Caster and ally gain twenty-five percent armor");Check(foe.armor==10&&foe2.armor==10&&far.armor==10,"Enemies gain no armor");Check(ally.effectors.Any(e=>e.effector==shield.effectors.records[0].effector),"Protective visual effector attached");Capture("steelpaladin-protection.png");Check(!Cast(shield,null),"Guard cooldown prevents immediate reuse");phase=7;return;}
 if(phase==7&&Time.time-start>7.3f){Check(Mathf.Abs(ally.armor-10)<.01f&&Mathf.Abs(archer.armor-10)<.01f,"Armor restored after six seconds");Check(!ally.effectors.Any(e=>e.effector==shield.effectors.records[0].effector),"Protection visual expires");phase=8;return;}
 if(phase==8&&Time.time-start>13){Check(Cast(shield,null),"Guard reusable after twelve seconds");archer.health=8000;phase=9;start=Time.time;return;}
 if(phase==9&&Time.time-start>1.5f){Check(ally.armor==10,"Healing caster during windup cancels health-conditional effect");Check(archer.unitState!=UnitStates.AbilityCasting,"Cancelled cast releases unit");TechnologyManager.instance.LockTech(shield.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(smite.requiredTech[0].data[0],0);second=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/SteelPaladin.prefab").GetComponent<Unit>(),center+Vector3.left,0,0);second.canAttack=false;second.doNotLookForTargets=true;second.Hold();second.GetComponent<AutoAbilityUser>().enabled=false;phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>1){hp=foe.health;Check(Cast(smite,null)&&second.UseAbilityItem(Array.IndexOf(second.abilities,smite),false,null,Vector3.zero),"Two paladins cast simultaneously");phase=11;start=Time.time;return;}
 if(phase==11&&Time.time-start>1.2f){var dt=smite.damage.entries[0].damageType;float expected=160*GameManager.instance.damageToArmor[foe.armorType.index*GameManager.instance.DTAWidth+dt.index]/1.6f;Check(Mathf.Abs(hp-foe.health-expected)<.1f,"Concurrent AoE applies once per caster");foe.Die(0,archer,false);foe2.Die(0,archer,false);Check(!smite.AutoCastReady(archer,0,out _),"No living enemy in radius prevents empty cast");phase=12;return;}
 if(phase==12&&Time.time-start>9){far.transform.position=center+Vector3.forward*2;Check(Cast(smite,null),"Cast begins before last target dies");far.Die(0,archer,false);phase=13;start=Time.time;return;}
 if(phase==13&&Time.time-start>1.5f){Check(archer.unitState!=UnitStates.AbilityCasting,"All targets dying releases caster");TechnologyManager.instance.LockTech(smite.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(shield.requiredTech[0].data[0],0);archer.health=2000;Check(Cast(shield,null),"Guard begins before caster death");archer.Die(foeOwner,null,false);phase=14;start=Time.time;return;}
 if(phase==14&&Time.time-start>1.5f){Check(ally.armor==10,"Dead caster cannot finish pending buff");Check(!Cast(shield,null),"Dead paladin rejected");second.maxHealth=10000;second.health=2000;Check(second.UseAbilityItem(Array.IndexOf(second.abilities,shield),false,null,Vector3.zero),"Second caster protects surviving ally");phase=15;start=Time.time;return;}
 if(phase==15&&Time.time-start>1.2f){Check(ally.armor>10,"Second guard applied");ally.Die(foeOwner,null,false);second.Die(foeOwner,null,false);phase=16;start=Time.time;return;}
 if(phase==16&&Time.time-start>8){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("GroundShock")||v.name.StartsWith("SteelProtection")||v.name.StartsWith("VanguardWave")),"All paladin VFX cleaned up including death");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static int Index(CompositeSkill s)=>Array.IndexOf(archer.abilities,s);
 static bool Cast(CompositeSkill s,Unit t)=>archer.UseAbilityItem(Index(s),false,s.targetMode==SkillTargetMode.SmartUnit?t:null,s.targetMode==SkillTargetMode.SmartPoint?t.transform.position:Vector3.zero);
 static Unit Spawn(Unit sample,Vector3 pos,int owner){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(prefab,pos,0,owner);u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("SteelPaladinSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/SteelPaladin.prefab").GetComponent<Unit>();archer=Unit.SpawnInternal(prefab,center,0,0);foe=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>(),center+Vector3.forward*2,0,foeOwner);
  foreach(var u in new[]{archer,foe}){u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();}
  archer.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));
  smite=(CompositeSkill)archer.abilities.First(a=>a.name=="SteelPaladin_GroundSmash");shield=(CompositeSkill)archer.abilities.First(a=>a.name=="SteelPaladin_StalwartVanguard");auto=archer.GetComponent<AutoAbilityUser>();auto.enabled=false;
  foe2=Spawn(foe,center+new Vector3(1.5f,0,1.5f),foeOwner);ally=Spawn(foe,center+new Vector3(-1.5f,0,1.5f),0);far=Spawn(foe,center+new Vector3(0,0,8),foeOwner);foe2.attackDamage=500;foe2.attackSpeed=1;speed=foe.moveSpeed;interval=foe.attackSpeed;
  Check(GameManager.instance.gameEffectors.TryGetValue(shield.effectors.records[0].effector.id,out var registered)&&registered==shield.effectors.records[0].effector,"Shield effector registered for native network/save pipeline");
  SkillPresentationEvents.SkillFired+=OnFired;
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-5);camera.transform.LookAt(center+new Vector3(0,.5f,3));camera.orthographic=true;camera.orthographicSize=6;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"steelpaladin-runtime-results.txt",results);}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("Smite")||v.name.StartsWith("Chilled")||v.name.StartsWith("FrostCast")).ToArray();var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"steelpaladin-runtime-results.txt",results);File.WriteAllLines(W+"steelpaladin-runtime-errors.txt",errors);File.WriteAllText(W+"steelpaladin-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("SteelPaladinSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


