#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class SteelPaladinSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Humans/SteelPaladin/";
 const string V="Assets/VFX/Skills/SteelPaladin/";
 const string A="Assets/Models/Units/Humans/SteelPaladin/Animations/";
 static SteelPaladinSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-steelpaladin.txt"))return;try{File.Delete(W+"configure-steelpaladin.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"steelpaladin-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"steelpaladin-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}


 static void Configure(){InterflowEditorUI.EnsureFolder(F);InterflowEditorUI.EnsureFolder(V);InterflowEditorUI.EnsureFolder(A);InterflowEditorUI.EnsureFolder("Assets/Resources/Effectors/Roster/Humans/SteelPaladin");
 var smash=Asset<CompositeSkill>("SteelPaladin_GroundSmash");var guard=Asset<CompositeSkill>("SteelPaladin_StalwartVanguard");
 foreach(var skill in new[]{smash,guard}){skill.maxLevels=1;skill.targetMode=SkillTargetMode.AreaAroundSelf;skill.castTime=new[]{.65f};skill.manaCost=new[]{0f};skill.procAnimationState="";skill.spawnSocket=SkillSocketType.None;skill.dontTurn=true;}
 smash.abilityName=new[]{"Сокрушение земли"};smash.description=new[]{"Удар по земле наносит 80 физического урона врагам в радиусе 3 м и оглушает их на 2 секунды."};smash.radius=new[]{3f};smash.cooldown=new[]{8f};smash.unitSelector=new UnitSelector(false,false,true,true,false,false,false,true,true,false,false,false);smash.castConditions=new SkillCastConditions{requireAreaTarget=true};smash.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{80f},damageType=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset"),targets=SkillDamageTargets.Enemies}}};smash.status=new SkillStatusBlock{enabled=true,stunSeconds=new[]{2f}};smash.impactVFX=Vfx("GroundShock","Range_attack/Hit_wind",1.1f);smash.impactVfxLifetime=1.2f;
 var path="Assets/Resources/Effectors/Roster/Humans/SteelPaladin/SteelPaladin_Protection.asset";var protection=AssetDatabase.LoadAssetAtPath<Effector>(path);if(!protection){protection=ScriptableObject.CreateInstance<Effector>();protection.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(protection,path);}protection.displayName="Авангард Стали";protection.description="Физическая броня увеличена на 25% на 6 секунд.";protection.duration=6;protection.passiveEffectsOn=true;protection.passiveEffects=new AbilityPassiveEffects{armorPercentageChange=.25f};protection.VFX=Vfx("SteelProtection","Shields/Shield_freezing",.65f,true);protection.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_tech_shields.png");EditorUtility.SetDirty(protection);
 guard.abilityName=new[]{"Авангард Стали"};guard.description=new[]{"При HP ниже 30% увеличивает физическую броню союзников в радиусе 5 м на 25% на 6 секунд."};guard.radius=new[]{5f};guard.cooldown=new[]{12f};guard.castConditions=new SkillCastConditions{casterHpBelow=.3f};guard.unitSelector=new UnitSelector(true,true,false,true,false,false,false,true,true,true,false,false);guard.includeSelf=true;guard.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=protection}}};guard.impactVFX=Vfx("VanguardWave","Range_attack/Hit_wind",1.5f);guard.impactVfxLifetime=1.2f;
 smash.icon=new[]{protection.icon};guard.icon=new[]{protection.icon};smash.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Lyudi_T6_A1.asset")}}};guard.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Lyudi_T6_A2.asset")}}};EditorUtility.SetDirty(smash);EditorUtility.SetDirty(guard);
 const string prefab="Assets/Resources/UnitPrefabs/Units/Humans/SteelPaladin.prefab";var root=PrefabUtility.LoadPrefabContents(prefab);try{var unit=root.GetComponent<Unit>();unit.abilities=(unit.abilities??Array.Empty<Ability>()).Where(a=>a&&a!=smash&&a!=guard&&AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(a))!="745d7ba2997971a49a5ae87f4199a234").Concat(new Ability[]{smash,guard}).ToArray();unit.abilityLevel=new int[unit.abilities.Length];var auto=root.GetComponent<AutoAbilityUser>()??root.AddComponent<AutoAbilityUser>();var data=new SerializedObject(auto);var list=data.FindProperty("autoAbilities");list.arraySize=2;list.GetArrayElementAtIndex(0).objectReferenceValue=smash;list.GetArrayElementAtIndex(1).objectReferenceValue=guard;data.ApplyModifiedPropertiesWithoutUndo();
 var animator=root.GetComponentInChildren<Animator>(true);string ctrlPath=A+"SteelPaladin_Skills.controller";var ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(ctrlPath);if(!ctrl){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),ctrlPath))throw new Exception("Cannot copy Paladin controller");ctrl=AssetDatabase.LoadAssetAtPath<AnimatorController>(ctrlPath);}var sm=ctrl.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");var clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);clip.name="SteelPaladin_Cast";AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);AssetDatabase.CreateAsset(clip,A+"SteelPaladin_Cast.anim");cast=sm.AddState("cast");cast.motion=clip;cast.speed=clip.length/.9f;var transition=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));transition.hasExitTime=true;transition.exitTime=1;transition.duration=.08f;}var sourceClip=AssetDatabase.LoadAllAssetsAtPath("Assets/DoubleL/FBX_Animations/Two Hand Base/Skills/InPlace/2Hand_Base_Skill_7_InPlace.fbx").OfType<AnimationClip>().First(c=>!c.name.StartsWith("__preview__"));var castClip=(AnimationClip)cast.motion;EditorUtility.CopySerialized(sourceClip,castClip);castClip.name="SteelPaladin_Cast";AnimationUtility.SetAnimationEvents(castClip,Array.Empty<AnimationEvent>());var clipSettings=AnimationUtility.GetAnimationClipSettings(castClip);clipSettings.loopTime=false;AnimationUtility.SetAnimationClipSettings(castClip,clipSettings);cast.speed=castClip.length/1.5f;EditorUtility.SetDirty(castClip);File.WriteAllText(W+"steelpaladin-clip.txt",AssetDatabase.GetAssetPath(sourceClip)+" length="+sourceClip.length+" events="+string.Join(";",AnimationUtility.GetAnimationEvents(sourceClip).Select(e=>e.time+":"+e.functionName)));animator.runtimeAnimatorController=ctrl;EditorUtility.SetDirty(ctrl);PrefabUtility.SaveAsPrefabAsset(root,prefab);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
