#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class SupremePunisherSkillRuntimeCheck
{
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit caster,near,far,foe,outside;static CompositePassive burst,blessing;static float start,baseDamage;static int phase;static double boot;static int foeOwner;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static SupremePunisherSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("SupremePunisherSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
  if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
  if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-supremepunisher.txt")){try{File.Delete(W+"run-supremepunisher.txt");}catch(IOException){return;}Begin();return;}
  if(!SessionState.GetBool("SupremePunisherSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
  if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}

  if(phase==1&&Time.time-start>1){HarvestTest();phase=2;start=Time.time;return;}
  if(phase==2&&Time.time-start>.15f){Capture("supremepunisher-harvest.png");phase=3;return;}
  if(phase==3&&Time.time-start>1){TechnologyManager.instance.LockTech(blessing.requiredTech[0].data[0],0);Check(Mathf.Abs(caster.attackDamage-baseDamage)<.01f,"Tech lock removes accumulated damage");var target=Spawn(center+Vector3.forward*2,foeOwner);float hp=caster.health;Kill(target,caster);Check(caster.health==hp&&Mathf.Abs(caster.attackDamage-baseDamage)<.01f,"Locked harvest has no effect");TechnologyManager.instance.UnlockTech(blessing.requiredTech[0].data[0],0);caster.health=500;foe=Spawn(center+Vector3.forward*2,foeOwner);foe.health=1;foe.armor=0;caster.canAttack=true;caster.Attack(foe);phase=4;start=Time.time;return;}
  if(phase==4&&Time.time-start>4){Check(foe.dead,"Normal animated attack kills enemy");Check(Mathf.Abs(caster.health-650)<.01f&&Mathf.Abs(caster.attackDamage-baseDamage*1.1f)<.01f,"Normal attack awards heal and one damage stack");caster.canAttack=false;caster.Hold();BurstTest();phase=5;start=Time.time;return;}
  if(phase==5&&Time.time-start>.45f){Capture("supremepunisher-explosion.png");phase=6;return;}
  if(phase==6&&Time.time-start>3){EdgeTests();phase=7;start=Time.time;return;}
  if(phase==7&&Time.time-start>4){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("HarvestGrace")||v.name.StartsWith("SacredExplosion")),"Harvest and explosion VFX cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("SupremePunisherSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static Unit Spawn(Vector3 p,int owner,bool supremepunisher=false){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/"+(supremepunisher?"SupremePunisher":"Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(prefab,p,0,owner);u.maxHealth=1000;u.health=500;u.armor=100;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  caster=Spawn(center,0,true);near=Spawn(center+Vector3.right,0);far=Spawn(center+Vector3.left*2,0);foe=Spawn(center+Vector3.forward*2,foeOwner);outside=Spawn(center+Vector3.forward*6,foeOwner);
  burst=(CompositePassive)caster.abilities.First(a=>a.name=="SupremePunisher_SacredExplosion");blessing=(CompositePassive)caster.abilities.First(a=>a.name=="SupremePunisher_UnholyHarvest");
  Check(caster.abilityLocked[Array.IndexOf(caster.abilities,burst)]&&caster.abilityLocked[Array.IndexOf(caster.abilities,blessing)],"Both skills initially tech locked");
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(6,7,-5);camera.transform.LookAt(center+new Vector3(0,.5f,1));camera.orthographic=true;camera.orthographicSize=4.5f;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"supremepunisher-runtime-results.txt",results);}

 static void Kill(Unit victim,Unit source){victim.GetDamage(100000,AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset"),source?source.owner:-1,source,true,out _);}
 static void HarvestTest(){baseDamage=caster.attackDamage;float hp=caster.health;Kill(foe,caster);Check(caster.health==hp&&caster.attackDamage==baseDamage,"Locked harvest does not react to enemy death");TechnologyManager.instance.UnlockTech(blessing.requiredTech[0].data[0],0);baseDamage=caster.attackDamage;foe=Spawn(center+Vector3.forward*2,foeOwner);MatchManager.instance.ObserveUnitForDeathHub(foe);MatchManager.instance.ObserveUnitForDeathHub(foe);Kill(foe,caster);Check(Mathf.Abs(caster.health-650)<.01f,"Kill restores fifteen percent maximum HP");Check(Mathf.Abs(caster.attackDamage-baseDamage*1.1f)<.01f,"First kill grants ten percent damage");foe.Die(0,caster,false);Check(Mathf.Abs(caster.attackDamage-baseDamage*1.1f)<.01f,"Repeated death and hub registration do not duplicate reward");Kill(Spawn(center+Vector3.forward*2,foeOwner),caster);Check(Mathf.Abs(caster.health-800)<.01f&&Mathf.Abs(caster.attackDamage-baseDamage*1.2f)<.01f,"Two kills add twenty percent rather than compound");hp=caster.health;Kill(near,caster);Check(caster.health==hp&&Mathf.Abs(caster.attackDamage-baseDamage*1.2f)<.01f,"Friendly kill grants no harvest");caster.health=950;Kill(Spawn(center+Vector3.forward*2,foeOwner),caster);Check(caster.health==1000,"Harvest healing capped at maximum");float damage=caster.attackDamage;blessing.Unlock(caster,0,0);Check(caster.attackDamage==damage,"Duplicate unlock preserves stack without duplication");}
 static void BurstTest(){TechnologyManager.instance.LockTech(blessing.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(burst.requiredTech[0].data[0],0);caster=Spawn(center,0,true);near=Spawn(center+Vector3.right,0);foe=Spawn(center+Vector3.forward*2,foeOwner);var hp=foe.health;Kill(caster,foe);Check(caster.dead,"Lethal hit kills caster");Check(Mathf.Abs(foe.health-(hp-250))<.01f,"Death burst deals 250 magic through armor");Check(near.health==500,"Burst excludes allies");Check(outside.health==500,"Burst excludes targets beyond four meters");hp=foe.health;caster.Die(foeOwner,foe,false);Check(foe.health==hp,"Death explosion executes once");}
 static void EdgeTests(){foe.health=1000;var a=Spawn(center,0,true);var b=Spawn(center+Vector3.right*.3f,0,true);a.Die(foeOwner,foe,false);b.Die(foeOwner,foe,false);Check(Mathf.Abs(foe.health-500)<.01f,"Concurrent explosions each deal one hit");TechnologyManager.instance.LockTech(burst.requiredTech[0].data[0],0);a=Spawn(center,0,true);float hp=foe.health;a.Die(foeOwner,foe,false);Check(foe.health==hp,"Locked explosion does not damage");TechnologyManager.instance.UnlockTech(blessing.requiredTech[0].data[0],0);a=Spawn(center,0,true);b=Spawn(center+Vector3.left,0,true);float da=a.attackDamage,db=b.attackDamage;var x=Spawn(center+Vector3.forward*2,foeOwner);var y=Spawn(center+Vector3.forward*3,foeOwner);Kill(x,a);Kill(y,b);Check(Mathf.Abs(a.attackDamage-da*1.1f)<.01f&&Mathf.Abs(b.attackDamage-db*1.1f)<.01f,"Two killers keep independent damage stacks");Check(a.health==650&&b.health==650,"Each killer receives only its own heal");x=Spawn(center+Vector3.forward*2,foeOwner);x.Die(-1,null,false);Check(a.health==650&&b.health==650,"Death without killer grants no harvest");a.Die(foeOwner,null,false);float old=a.attackDamage;Kill(Spawn(center+Vector3.forward*2,foeOwner),a);Check(a.attackDamage==old,"Dead killer cannot collect harvest");TechnologyManager.instance.LockTech(blessing.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(burst.requiredTech[0].data[0],0);a=Spawn(center+Vector3.back*12,0,true);a.Die(-1,null,false);Check(a.dead,"Explosion with no target finishes");}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("SacredExplosion")||v.name.StartsWith("HarvestGrace")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"supremepunisher-runtime-results.txt",results);File.WriteAllLines(W+"supremepunisher-runtime-errors.txt",errors);File.WriteAllText(W+"supremepunisher-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("SupremePunisherSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


