#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;using StrategyCore;
[InitializeOnLoad] public static class VanguardMageSkillSetup {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string F="Assets/Resources/Ability/Roster/Humans/VanguardMage/";
 const string V="Assets/VFX/Skills/VanguardMage/";
 const string A="Assets/Models/Units/Humans/VanguardMage/Animations/";
 static VanguardMageSkillSetup(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode||!File.Exists(W+"configure-vanguardmage.txt"))return;try{File.Delete(W+"configure-vanguardmage.txt");}catch(IOException){return;}try{Configure();File.WriteAllText(W+"vanguardmage-configured.txt","OK");}catch(Exception e){File.WriteAllText(W+"vanguardmage-configured.txt",e.ToString());Debug.LogException(e);}}
 static T Asset<T>(string name)where T:Ability{var a=AssetDatabase.LoadAssetAtPath<T>(F+name+".asset");if(a)return a;a=ScriptableObject.CreateInstance<T>();a.id=InterflowEditorUI.NextFreeId("t:Ability",o=>((Ability)o).id);a.abilityName=new[]{name};AssetDatabase.CreateAsset(a,F+name+".asset");return a;}
 static VFXReferencer Vfx(string name,string source,float scale,bool loop=false){var old=AssetDatabase.LoadAssetAtPath<GameObject>(V+name+".prefab");if(old)return old.GetComponent<VFXReferencer>();var root=new GameObject(name);try{root.AddComponent<VFXReferencer>();var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/"+source+".prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*scale;foreach(var ps in visual.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.loop=loop;m.playOnAwake=true;}return PrefabUtility.SaveAsPrefabAsset(root,V+name+".prefab").GetComponent<VFXReferencer>();}finally{UnityEngine.Object.DestroyImmediate(root);}}
 static void TuneBlizzard(){var root=PrefabUtility.LoadPrefabContents(V+"Blizzard.prefab");try{root.transform.GetChild(0).localScale=Vector3.one*.85f;foreach(var ps in root.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.startDelay=0;m.simulationSpeed=3f;var e=ps.emission;for(int i=0;i<e.burstCount;i++){var b=e.GetBurst(i);b.time=0;e.SetBurst(i,b);}if(ps.name.StartsWith("target_"))ps.gameObject.SetActive(false);if(ps.name=="glow"||ps.name=="dust"||ps.name=="area")m.startColor=new Color(.65f,.85f,1f,.35f);}PrefabUtility.SaveAsPrefabAsset(root,V+"Blizzard.prefab");}finally{PrefabUtility.UnloadPrefabContents(root);}}
 static void PlaceEffectors(){foreach(var pair in new[]{"InquisitionArcher/InquisitionArcher_Burning","InquisitionArcher/InquisitionArcher_MagicVulnerability","VanguardMage/VanguardMage_Chilled"}){string old="Assets/Resources/Ability/Roster/Humans/"+pair+".asset",target="Assets/Resources/Effectors/Roster/Humans/"+pair+".asset";InterflowEditorUI.EnsureFolder(Path.GetDirectoryName(target));if(AssetDatabase.LoadAssetAtPath<Effector>(old)&&!AssetDatabase.LoadAssetAtPath<Effector>(target)){string error=AssetDatabase.MoveAsset(old,target);if(!string.IsNullOrEmpty(error))throw new Exception(error);}}}
 static void ExistingIcons(){string[] pairs={"Swordsman/Swordsman_ShieldWall|humans_tech_shields","Swordsman/Swordsman_Parry|humans_tech_long_sword","Inquisition/Inquisition_DyingFlame|humans_ability_fireball","Inquisition/Inquisition_FallenBlessing|humans_ability_heal","RoyalArcher/RoyalArcher_ArmorPierce|humans_tech_heavy_bolts","RoyalArcher/RoyalArcher_LongShot|humans_tech_archer_range","InquisitionArcher/InquisitionArcher_CleansingFire|ui_status_burn","InquisitionArcher/InquisitionArcher_CausticJudgment|ui_status_poison"};foreach(var pair in pairs){var parts=pair.Split('|');var skill=AssetDatabase.LoadAssetAtPath<Ability>("Assets/Resources/Ability/Roster/Humans/"+parts[0]+".asset");if(!skill)continue;skill.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/"+parts[1]+".png")};EditorUtility.SetDirty(skill);}foreach(var name in new[]{"Burning","MagicVulnerability"}){var eff=AssetDatabase.LoadAssetAtPath<Effector>("Assets/Resources/Effectors/Roster/Humans/InquisitionArcher/InquisitionArcher_"+name+".asset");if(eff){eff.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_status_"+(name=="Burning"?"burn":"poison")+".png");EditorUtility.SetDirty(eff);}}}
 static void Configure(){PlaceEffectors();ExistingIcons();Directory.CreateDirectory(F);Directory.CreateDirectory(V);Directory.CreateDirectory(A);AssetDatabase.Refresh();
 var blizzard=Asset<CompositeSkill>("VanguardMage_Blizzard");var arrow=Asset<CompositeSkill>("VanguardMage_IceArrow");var magic=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/Magic.asset");
 var slow=AssetDatabase.LoadAssetAtPath<Effector>("Assets/Resources/Effectors/Roster/Humans/VanguardMage/VanguardMage_Chilled.asset");if(!slow){slow=ScriptableObject.CreateInstance<Effector>();slow.id=InterflowEditorUI.NextFreeId("t:Effector",o=>((Effector)o).id);AssetDatabase.CreateAsset(slow,"Assets/Resources/Effectors/Roster/Humans/VanguardMage/VanguardMage_Chilled.asset");}slow.displayName="Переохлаждение";slow.description="Скорость движения и атаки снижены на 40%.";slow.duration=3;slow.stacks=false;slow.passiveEffectsOn=true;slow.passiveEffects=new AbilityPassiveEffects{exactPercentageReductions=true,moveSpeedPercentageChange=-.4f,attackSpeedPercentageChange=-.4f};slow.VFX=Vfx("Chilled","Fire/Fire_cartoon_frost",.3f,true);EditorUtility.SetDirty(slow);
 foreach(var s in new[]{blizzard,arrow}){s.maxLevels=1;s.castRange=new[]{9f};s.castTime=new[]{.6f};s.manaCost=new[]{0f};s.spawnSocket=SkillSocketType.RightHand;s.unitSelector=new UnitSelector(false,false,true,true,false,false,false,true,true,true,false,false);s.castVFX=Vfx("FrostCast","Range_attack/Hit_frost",.25f);s.castVfxLifetime=.7f;s.procAnimationState="";s.damage=new SkillDamageBlock{enabled=true,entries=new[]{new SkillDamageEntry{amount=new[]{s==blizzard?40f:60f},damageType=magic,targets=SkillDamageTargets.Enemies}}};}
 blizzard.abilityName=new[]{"Ледяной Шквал"};blizzard.description=new[]{"Ледяной дождь наносит 40 магического урона врагам в радиусе 3 и замедляет движение и атаку на 40% на 3 секунды."};blizzard.targetMode=SkillTargetMode.SmartPoint;blizzard.targetStrategy=SkillTargetStrategy.Cluster;blizzard.radius=new[]{3f};blizzard.cooldown=new[]{8f};blizzard.effectors=new SkillEffectorsBlock{enabled=true,records=new[]{new SkillEffectorRecord{effector=slow,power=new[]{1f},duration=new[]{3f}}}};blizzard.impactVFX=Vfx("Blizzard","Top_down_attack/top_down_ice_circle",1.5f);blizzard.impactVfxLifetime=1.8f;TuneBlizzard();
 arrow.abilityName=new[]{"Ледяная Стрела"};arrow.description=new[]{"Ледяной снаряд наносит 60 магического урона опаснейшей цели и оглушает её на 1.5 секунды."};arrow.targetMode=SkillTargetMode.SmartUnit;arrow.targetStrategy=SkillTargetStrategy.HighestDps;arrow.cooldown=new[]{4f};arrow.status=new SkillStatusBlock{enabled=true,stunSeconds=new[]{1.5f}};arrow.delivery=SkillDelivery.Projectile;arrow.projectileFollowsTarget=true;
 string projectilePath="Assets/Resources/Projectiles/VanguardMage_IceArrow.prefab";var projectile=AssetDatabase.LoadAssetAtPath<GameObject>(projectilePath);if(!projectile){var root=new GameObject("VanguardMage_IceArrow");try{var pr=root.AddComponent<Projectile>();pr.id=AssetDatabase.FindAssets("t:Prefab",new[]{"Assets/Resources/Projectiles"}).Select(g=>AssetDatabase.LoadAssetAtPath<GameObject>(AssetDatabase.GUIDToAssetPath(g)).GetComponent<Projectile>()).Where(x=>x).Select(x=>x.id).DefaultIfEmpty(0).Max()+1;pr.speed=12;var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/Range_attack/Projectiles_frost.prefab"));visual.transform.SetParent(root.transform,false);visual.transform.localScale=Vector3.one*.35f;pr.renderObject=visual;pr.impactVFX=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Lana Studio/Casual RPG VFX/Prefabs/Range_attack/Hit_frost.prefab").GetComponent<ParticleSystem>();projectile=PrefabUtility.SaveAsPrefabAsset(root,projectilePath);}finally{UnityEngine.Object.DestroyImmediate(root);}}arrow.projectilePrefab=projectile.GetComponent<Projectile>();
 var hit=Vfx("IceImpact","Range_attack/Hit_frost",.4f);var hitRoot=PrefabUtility.LoadPrefabContents(V+"IceImpact.prefab");try{var ps=hitRoot.GetComponentInChildren<ParticleSystem>();var m=ps.main;m.loop=false;m.duration=2;m.stopAction=ParticleSystemStopAction.Destroy;PrefabUtility.SaveAsPrefabAsset(hitRoot,V+"IceImpact.prefab");}finally{PrefabUtility.UnloadPrefabContents(hitRoot);}var pRoot=PrefabUtility.LoadPrefabContents(projectilePath);try{pRoot.GetComponent<Projectile>().impactVFX=AssetDatabase.LoadAssetAtPath<GameObject>(V+"IceImpact.prefab").GetComponentInChildren<ParticleSystem>();PrefabUtility.SaveAsPrefabAsset(pRoot,projectilePath);}finally{PrefabUtility.UnloadPrefabContents(pRoot);}
 blizzard.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/humans_ability_snowfall.png")};arrow.icon=new[]{AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_status_stun.png")};slow.icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Icons/icons/ui_status_slow.png");
 blizzard.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Lyudi_T3_A1.asset")}}};arrow.requiredTech=new[]{new MultiLevel<Technology>{data=new[]{AssetDatabase.LoadAssetAtPath<Technology>("Assets/Resources/Technology/Lyudi_T3_A2.asset")}}};foreach(var s in new[]{blizzard,arrow})EditorUtility.SetDirty(s);
 const string prefab="Assets/Resources/UnitPrefabs/Units/Humans/VanguardMage.prefab";var go=PrefabUtility.LoadPrefabContents(prefab);try{var u=go.GetComponent<Unit>();u.abilities=(u.abilities??Array.Empty<Ability>()).Where(x=>x&&x!=blizzard&&x!=arrow&&AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(x))!="745d7ba2997971a49a5ae87f4199a234").Concat(new Ability[]{blizzard,arrow}).ToArray();u.abilityLevel=new int[u.abilities.Length];var auto=go.GetComponent<AutoAbilityUser>()??go.AddComponent<AutoAbilityUser>();var so=new SerializedObject(auto);var list=so.FindProperty("autoAbilities");list.arraySize=2;list.GetArrayElementAtIndex(0).objectReferenceValue=blizzard;list.GetArrayElementAtIndex(1).objectReferenceValue=arrow;so.ApplyModifiedPropertiesWithoutUndo();
 var sockets=go.GetComponent<CharacterSockets>()??go.AddComponent<CharacterSockets>();var hand=go.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name=="Hand_R"||t.name=="RightHand"||t.name=="hand_r");if(!hand)throw new Exception("Missing right hand bone");var socketData=new SerializedObject(sockets);socketData.FindProperty("rightHand").objectReferenceValue=hand;socketData.ApplyModifiedPropertiesWithoutUndo();
 var animator=go.GetComponentInChildren<Animator>(true);string controllerPath=A+"VanguardMage_Skills.controller";var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);if(!controller){if(!AssetDatabase.CopyAsset(AssetDatabase.GetAssetPath(animator.runtimeAnimatorController),controllerPath))throw new Exception("Cannot copy caster animator");controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);}var sm=controller.layers[0].stateMachine;var cast=sm.states.Select(x=>x.state).FirstOrDefault(x=>x.name=="cast");if(!cast){var attack=sm.states.Select(x=>x.state).First(x=>x.name=="attack0");var clip=UnityEngine.Object.Instantiate((AnimationClip)attack.motion);clip.name="VanguardMage_Cast";AnimationUtility.SetAnimationEvents(clip,Array.Empty<AnimationEvent>());var settings=AnimationUtility.GetAnimationClipSettings(clip);settings.loopTime=false;AnimationUtility.SetAnimationClipSettings(clip,settings);AssetDatabase.CreateAsset(clip,A+"VanguardMage_Cast.anim");cast=sm.AddState("cast");cast.motion=clip;cast.speed=clip.length/.7f;var tr=cast.AddTransition(sm.states.Select(x=>x.state).First(x=>x.name=="idleReady"));tr.hasExitTime=true;tr.exitTime=1;tr.duration=.08f;}animator.runtimeAnimatorController=controller;EditorUtility.SetDirty(controller);File.WriteAllLines(W+"vanguardmage-animation.txt",sm.states.Select(x=>x.state.name+" | "+(x.state.motion?x.state.motion.name:"none")));PrefabUtility.SaveAsPrefabAsset(go,prefab);}finally{PrefabUtility.UnloadPrefabContents(go);}AssetDatabase.SaveAssets();InterflowAbilityUsage.InvalidateCache();InterflowAbilityGroups.InvalidateCache();
 }
}
#endif
