#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class VanguardMageSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit archer,foe,foe2,ally,far,second;static CompositeSkill blizzard,arrow;static AutoAbilityUser auto;static float start,speed,interval,hp;static int phase,foeOwner,blizzards,arrows;static double boot;static Vector3 center;static Camera camera;static List<string> results=new List<string>(),errors=new List<string>();
 static VanguardMageSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("VanguardMageSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void OnFired(Unit u,int id,int level,Unit target,Vector3 point){if(u!=archer)return;if(id==blizzard.id)blizzards++;if(id==arrow.id)arrows++;}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-vanguardmage.txt")){try{File.Delete(W+"run-vanguardmage.txt");}catch(IOException){return;}Begin();return;}
 if(!SessionState.GetBool("VanguardMageSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Game initialization timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>1){Check(!Cast(blizzard,foe),"Locked skill cannot cast");TechnologyManager.instance.UnlockTech(blizzard.requiredTech[0].data[0],0);Check(blizzard.AutoCastReady(archer,0,out var cluster)&&cluster!=null,"Cluster targeting finds enemy group");Check(Cast(blizzard,foe),"Blizzard accepted through Unit ability workflow");phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.2f){Check(foe.health==10000,"Damage waits for cast time");Check(archer.hasCastAnim,"Caster has cast animation");Capture("vanguardmage-casting.png");phase=3;return;}
 if(phase==3&&Time.time-start>1.2f){Check(Mathf.Abs(foe.health-9960)<.1f&&Mathf.Abs(foe2.health-9960)<.1f,"Blizzard damages multiple enemies for 40 magic each");Check(ally.health==10000&&far.health==10000,"Allies and outside-radius enemy excluded");Check(Mathf.Abs(foe.moveSpeed-speed*.6f)<.01f,"Movement reduced exactly 40%");Check(Mathf.Abs(foe.attackSpeed-interval/.6f)<.01f,"Attack frequency reduced exactly 40%");Check(archer.GetAbilityCooldown(Index(blizzard),false)>6,"Eight-second cooldown running");Check(!Cast(blizzard,foe),"Cooldown blocks repeated use");Capture("vanguardmage-blizzard.png");phase=4;return;}
 if(phase==4&&Time.time-start>4.3f){Check(Mathf.Abs(foe.moveSpeed-speed)<.01f&&Mathf.Abs(foe.attackSpeed-interval)<.01f,"Slow expires and restores both stats");auto.enabled=true;phase=5;return;}
 if(phase==5&&Time.time-start>10.5f){auto.enabled=false;Check(blizzards>=2,"Autocast reuses Blizzard after cooldown");TechnologyManager.instance.LockTech(blizzard.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(arrow.requiredTech[0].data[0],0);Check(arrow.AutoCastReady(archer,0,out var target)&&target==foe2,"Ice arrow selects highest DPS enemy");hp=foe2.health;Check(Cast(arrow,foe2),"Ice arrow accepted");phase=6;start=Time.time;return;}
 if(phase==6&&Time.time-start>.7f){Capture("vanguardmage-projectile.png");phase=7;return;}
 if(phase==7&&Time.time-start>1.3f){Check(Mathf.Abs(hp-foe2.health-60)<.1f,"Ice projectile deals 60 magic damage");Check(foe2.stunned,"Ice projectile stuns on impact");Check(!foe.stunned&&!ally.stunned,"Ice arrow affects only chosen target");Check(archer.GetAbilityCooldown(Index(arrow),false)>2,"Four-second arrow cooldown running");Capture("vanguardmage-freeze.png");phase=8;return;}
 if(phase==8&&Time.time-start>3f){Check(!foe2.stunned,"Freeze expires after 1.5 seconds");Check(archer.unitState!=UnitStates.AbilityCasting,"Caster leaves casting state");phase=9;return;}
 if(phase==9&&Time.time-start>5f){Check(Cast(arrow,foe2),"Arrow reusable after cooldown");foe2.Die(0,archer,false);phase=10;start=Time.time;return;}
 if(phase==10&&Time.time-start>2){Check(archer.unitState!=UnitStates.AbilityCasting,"Dead target does not trap caster");TechnologyManager.instance.LockTech(arrow.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(blizzard.requiredTech[0].data[0],0);second=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/VanguardMage.prefab").GetComponent<Unit>(),center+Vector3.left*2,0,0);second.canAttack=false;second.doNotLookForTargets=true;second.Hold();second.GetComponent<AutoAbilityUser>().enabled=false;second.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));hp=foe.health;Check(Cast(blizzard,foe)&&second.UseAbilityItem(Array.IndexOf(second.abilities,blizzard),false,null,foe.transform.position),"Two mages can cast simultaneously");phase=11;start=Time.time;return;}
 if(phase==11&&Time.time-start>1.5f){Check(Mathf.Abs(hp-foe.health-80)<.1f,"Concurrent Blizzard damage applied once per caster");Check(foe.effectors.Count(e=>e.effector==blizzard.effectors.records[0].effector)==1,"Concurrent slows refresh without multiplying");TechnologyManager.instance.LockTech(blizzard.requiredTech[0].data[0],0);TechnologyManager.instance.UnlockTech(arrow.requiredTech[0].data[0],0);hp=foe.health;Check(Cast(arrow,foe),"Arrow starts before caster death");phase=12;start=Time.time;return;}
 if(phase==12&&Time.time-start>.7f){Check(UnityEngine.Object.FindObjectsByType<Projectile>(FindObjectsSortMode.None).Any(p=>p.name.StartsWith("VanguardMage_IceArrow")),"Skill projectile in flight at caster death");archer.Die(foeOwner,foe,false);phase=13;return;}
 if(phase==13&&Time.time-start>2){Check(Mathf.Abs(hp-foe.health-60)<.1f,"Launched spell still hits after caster dies");foe.Die(0,second,false);far.Die(0,second,false);Check(!arrow.AutoCastReady(second,0,out var none),"No enemies means no autocast target");Check(!Cast(arrow,ally),"Dead caster cannot use skill");second.Die(foeOwner,null,false);phase=14;start=Time.time;return;}
 if(phase==14&&Time.time-start>5){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("Blizzard")||v.name.StartsWith("Chilled")||v.name.StartsWith("FrostCast")),"All skill effects cleaned up");Check(!UnityEngine.Object.FindObjectsByType<ParticleSystem>(FindObjectsSortMode.None).Any(p=>p.name=="Hit_frost(Clone)"),"Projectile impact particle roots cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static int Index(CompositeSkill s)=>Array.IndexOf(archer.abilities,s);
 static bool Cast(CompositeSkill s,Unit t)=>archer.UseAbilityItem(Index(s),false,s.targetMode==SkillTargetMode.SmartUnit?t:null,s.targetMode==SkillTargetMode.SmartPoint?t.transform.position:Vector3.zero);
 static Unit Spawn(Unit sample,Vector3 pos,int owner){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(prefab,pos,0,owner);u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("VanguardMageSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}
  if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
  if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
  foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
  var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/VanguardMage.prefab").GetComponent<Unit>();archer=Unit.SpawnInternal(prefab,center,0,0);foe=Unit.SpawnInternal(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/Humans/Swordsman.prefab").GetComponent<Unit>(),center+Vector3.forward*3,0,foeOwner);
  foreach(var u in new[]{archer,foe}){u.maxHealth=10000;u.health=10000;u.armor=10;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();}
  archer.LookAtInstant(new Vector2(foe.transform.position.x,foe.transform.position.z));
  blizzard=(CompositeSkill)archer.abilities.First(a=>a.name=="VanguardMage_Blizzard");arrow=(CompositeSkill)archer.abilities.First(a=>a.name=="VanguardMage_IceArrow");auto=archer.GetComponent<AutoAbilityUser>();auto.enabled=false;
  foe2=Spawn(foe,center+new Vector3(1.5f,0,3),foeOwner);ally=Spawn(foe,center+new Vector3(-1.5f,0,3),0);far=Spawn(foe,center+new Vector3(0,0,8),foeOwner);foe2.attackDamage=500;foe2.attackSpeed=1;speed=foe.moveSpeed;interval=foe.attackSpeed;
  Check(GameManager.instance.gameEffectors.TryGetValue(blizzard.effectors.records[0].effector.id,out var registered)&&registered==blizzard.effectors.records[0].effector,"Chill registered for network/save resolution");
  Check(Resources.LoadAll<Effector>("Effectors/Roster").All(e=>GameManager.instance.gameEffectors.ContainsKey(e.id)),"Roster effectors registered by native pipeline");
  SkillPresentationEvents.SkillFired+=OnFired;
  foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
  camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(7,9,-5);camera.transform.LookAt(center+new Vector3(0,.5f,3));camera.orthographic=true;camera.orthographicSize=6;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"vanguardmage-runtime-results.txt",results);}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("Blizzard")||v.name.StartsWith("Chilled")||v.name.StartsWith("FrostCast")).ToArray();var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}
 static void Finish(){File.WriteAllLines(W+"vanguardmage-runtime-results.txt",results);File.WriteAllLines(W+"vanguardmage-runtime-errors.txt",errors);File.WriteAllText(W+"vanguardmage-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("VanguardMageSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif


