#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.AI;using StrategyCore;
[InitializeOnLoad]public static class WarWolfSkillRuntimeCheck {
 const string W=@"C:\Users\aleks\Documents\Codex\2026-09-11\v\work\skills-28\";
 const string Scene="Assets/Scenes/Archive/Artsiom_SkillChecks.unity";
 static Unit wolf,primary,close,wide,ally,outside;static CompositePassive cleave;static EveryNthAttack grip;static DamageType physical;static Vector3 center;static Camera camera;static int foeOwner,phase;static float start;static double boot;static List<string> results=new List<string>(),errors=new List<string>();
 static WarWolfSkillRuntimeCheck(){boot=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 static void Log(string msg,string stack,LogType t){if(SessionState.GetBool("WarWolfSkillCheck",false)&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert))errors.Add(msg+"\n"+stack);}
 static void Tick(){try{
 if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;
 if(!EditorApplication.isPlaying&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists(W+"run-warwolf.txt")){File.Delete(W+"run-warwolf.txt");Begin();return;}
 if(!SessionState.GetBool("WarWolfSkillCheck",false)||!EditorApplication.isPlaying||EditorApplication.isPaused)return;
 if(phase==0){if(!SlotManager.instance||!SlotManager.instance.gameOn){if(EditorApplication.timeSinceStartup-boot>90)throw new Exception("Startup timeout");return;}Setup();phase=1;start=Time.time;return;}
 if(phase==1&&Time.time-start>.8f){Mechanics();phase=2;start=Time.time;return;}
 if(phase==2&&Time.time-start>.15f){Capture("warwolf-cleave-grip.png");Check(primary.stunned,"Grip lasts past first frame");phase=3;return;}
 if(phase==3&&Time.time-start>1f){Check(!primary.stunned,"Grip expires after 0.8 seconds");Edges();wolf.canAttack=true;wolf.attackDamage=30;primary.health=1000;close.health=1000;wolf.Attack(primary);phase=4;start=Time.time;return;}
 if(phase==4&&Time.time-start>6f){Check(primary.health<970,"Native animation attacks repeatedly");Check(close.health<1000,"Native attack events trigger cleave");Capture("warwolf-native-attacks.png");wolf.canAttack=false;wolf.Hold();Check(wolf.unitState!=UnitStates.AbilityCasting,"Passive does not stick Animator in cast state");phase=5;start=Time.time;return;}
 if(phase==5&&Time.time-start>2f){Check(!UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Any(v=>v.name.StartsWith("Wolf")),"All transient wolf VFX cleaned up");Finish();}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Begin(){if(UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!="Assets/Scenes/Artsiom.unity"&&UnityEngine.SceneManagement.SceneManager.GetActiveScene().path!=Scene)throw new Exception("Open basic Artsiom before this check");if(!AssetDatabase.LoadAssetAtPath<SceneAsset>(Scene)){if(!AssetDatabase.CopyAsset("Assets/Scenes/Artsiom.unity",Scene))throw new Exception("Cannot copy Artsiom");}EditorSceneManager.OpenScene(Scene);foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="MatchManager")m.enabled=false;foreach(var f in UnityEngine.Object.FindObjectsByType<FogOfWar>(FindObjectsSortMode.None))f.TurnOff=true;
 EditorSceneManager.sceneSaved-=SceneCustomData.OnSceneSaved;try{EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}finally{EditorSceneManager.sceneSaved+=SceneCustomData.OnSceneSaved;}
 SessionState.SetBool("WarWolfSkillCheck",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}

 static Unit Spawn(Vector3 p,int owner,bool isWolf=false){var asset=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/UnitPrefabs/Units/"+(isWolf?"Orcs/WarWolf":"Humans/Swordsman")+".prefab").GetComponent<Unit>();var u=Unit.SpawnInternal(asset,p,0,owner);u.maxHealth=10000;u.health=1000;u.armor=0;u.canAttack=false;u.doNotLookForTargets=true;u.Hold();u.FoWVisible=true;u.ShowRenderers();return u;}
 static void Setup(){foreach(var u in UnityEngine.Object.FindObjectsByType<Unit>(FindObjectsSortMode.None)){u.canAttack=false;u.doNotLookForTargets=true;u.Hold();var a=u.GetComponent<AutoAbilityUser>();if(a)a.enabled=false;}if(FogOfWar.instance)FogOfWar.instance.TurnOff=true;
 if(!NavMesh.SamplePosition(new Vector3(113,0,33),out var hit,10,NavMesh.AllAreas))throw new Exception("No navmesh");center=hit.position;
 foeOwner=Enumerable.Range(1,SlotManager.instance.playerTeam.Length-2).First(i=>SlotManager.instance.playerTeam[i]!=SlotManager.instance.playerTeam[0]);
 wolf=Spawn(center,0,true);primary=Spawn(center+Vector3.forward*2,foeOwner);close=Spawn(primary.transform.position+Vector3.right,foeOwner);wide=Spawn(primary.transform.position+Vector3.left*(1.75f+primary.unitRadius),foeOwner);ally=Spawn(primary.transform.position+Vector3.forward,0);outside=Spawn(primary.transform.position+Vector3.forward*5,foeOwner);
 cleave=(CompositePassive)wolf.abilities.First(a=>a.name=="WarWolf_Cleave");grip=(EveryNthAttack)wolf.abilities.First(a=>a.name=="WarWolf_Grip");physical=AssetDatabase.LoadAssetAtPath<DamageType>("Assets/Resources/DamageTypes/DontRemove/DamageType.asset");
 foreach(var m in UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None))if(m.GetType().Name=="Camera_TopDown"||m.GetType().Name=="CameraAxisLock")m.enabled=false;
 camera=Camera.main;camera.transform.SetParent(null,true);camera.transform.position=center+new Vector3(6,7,-5);camera.transform.LookAt(center+new Vector3(0,.5f,1));camera.orthographic=true;camera.orthographicSize=4.5f;}
 static void Check(bool ok,string text){results.Add((ok?"PASS ":"FAIL ")+text);if(!ok)errors.Add(text);File.WriteAllLines(W+"warwolf-runtime-results.txt",results);}
 static void Hit(bool direct=true){wolf.DealDamage(primary,100,physical,direct,primary.transform.position);}
 static void ClearStun(){if(!primary.stunned)return;primary.stunTime=0;typeof(Unit).GetMethod("StunUpdate",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).Invoke(primary,null);}
 static void Reset(){foreach(var u in new[]{primary,close,wide,ally,outside})u.health=1000;}
 static void Mechanics(){Reset();Check(!wolf.isSplash,"Native falloff splash disabled to prevent duplicate cleave");Check(!wolf.abilityLocked[Array.IndexOf(wolf.abilities,cleave)]&&wolf.abilityLocked[Array.IndexOf(wolf.abilities,grip)],"Base cleave unlocked and grip specialization locked");Hit();Check(primary.health==900,"Primary takes exactly one full attack");Check(close.health==960,"Neighbour takes exactly 40 percent");Check(wide.health==1000&&outside.health==1000,"Base radius excludes distant enemies");Check(ally.health==1000,"Cleave excludes allies");Check(!primary.stunned,"Locked grip no stun");Reset();Hit(false);Check(close.health==1000,"Indirect damage does not cleave recursively");TechnologyManager.instance.UnlockTech(cleave.cleave.upgradeTechnology,0);Reset();Hit();Check(close.health==940&&wide.health==940,"Upgrade changes fraction to 60 percent and expands radius");cleave.Unlock(wolf,0,0);Check(wolf.OnAfterDamageDealCallbacks.Count(c=>c.Ability==cleave)==1,"Repeated unlock no duplicate cleave");TechnologyManager.instance.LockTech(cleave.cleave.upgradeTechnology,0);Reset();Hit();Check(close.health==960&&wide.health==1000,"Upgrade removal restores base fraction and radius");
 TechnologyManager.instance.UnlockTech(grip.requiredTech[0].data[0],0);var cleaveVisual=cleave.cleave.hitPresentation;var gripVisual=grip.onProcSkill.impactVFX;cleave.cleave.hitPresentation=null;grip.onProcSkill.impactVFX=null;var random=UnityEngine.Random.state;UnityEngine.Random.InitState(48123);int procs=0;for(int i=0;i<400;i++){ClearStun();primary.health=1000;close.health=1000;Hit();if(primary.stunned)procs++;}UnityEngine.Random.state=random;cleave.cleave.hitPresentation=cleaveVisual;grip.onProcSkill.impactVFX=gripVisual;Check(procs>=40&&procs<=85,"Seeded 400 attacks produce approximately 15 percent stuns: "+procs);ClearStun();for(int i=0;i<100&&!primary.stunned;i++){Reset();Hit();}Check(primary.stunned&&Mathf.Abs(primary.stunTime-.8f)<.001f,"Grip applies exact 0.8 second stun");Check(!close.stunned&&!wide.stunned,"Cleave victims are not stunned by primary proc");}
 static void Edges(){var ci=primary.gameObject.AddComponent<ControlImmunity>();ci.Add();ClearStun();for(int i=0;i<50;i++){Reset();Hit();}Check(!primary.stunned,"Control immunity prevents grip");ci.Remove();TechnologyManager.instance.LockTech(grip.requiredTech[0].data[0],0);Reset();primary.health=1;Hit();Check(primary.dead&&close.health==960,"Killing primary still cleaves neighbours");primary=Spawn(center+Vector3.forward*2,foeOwner);Reset();var other=Spawn(center+Vector3.left*3,0,true);other.DealDamage(primary,100,physical,true,primary.transform.position);Check(close.health==960,"Second wolf has its own functioning passive");other.Die(-1,null,false);Check(other.dead,"Wolf death safely removes carrier on later unlock");cleave.Unlock(wolf,0,0);float hp=close.health;wolf.DealDamage(null,0,physical,true,Vector3.zero);Check(close.health==hp,"Missing target and zero damage safely ignored");Reset();}
 static void Capture(string name){var fx=UnityEngine.Object.FindObjectsByType<VFXReferencer>(FindObjectsSortMode.None).Where(v=>v.name.StartsWith("Wolf")).ToArray();Check(fx.Length>0,"Presentation spawned: "+name);var rt=new RenderTexture(1280,800,24);var prior=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var t=new Texture2D(1280,800,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,1280,800),0,0);t.Apply();File.WriteAllBytes(W+name,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}finally{camera.targetTexture=prior;RenderTexture.active=active;UnityEngine.Object.DestroyImmediate(rt);}}

 static void Finish(){File.WriteAllLines(W+"warwolf-runtime-results.txt",results);File.WriteAllLines(W+"warwolf-runtime-errors.txt",errors);File.WriteAllText(W+"warwolf-runtime-finished.txt","Checks="+results.Count+" errors="+errors.Count);SessionState.SetBool("WarWolfSkillCheck",false);EditorApplication.isPaused=true;}
}
#endif
