Name: Hero_incvisitor
Species: 1
Parts:
- Name: SK_ELVN_WARR_01_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_ELVN_WARR_01_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_ELVN_WARR_01_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_ELVN_WARR_01_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_ELVN_WARR_01_26AHPB_HU01
  PartType: AttachmentHipsBack
  PartVersion: 1
- Name: SK_ELVN_WARR_01_31AEBL_HU01
  PartType: AttachmentElbowLeft
  PartVersion: 1
- Name: SK_ELVN_WARR_01_32AEBR_HU01
  PartType: AttachmentElbowRight
  PartVersion: 1
- Name: SK_ELVN_WARR_03_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_ELVN_WARR_03_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_FANT_KNGT_01_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_FANT_KNGT_01_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_01_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_FANT_KNGT_01_25AHPF_HU01
  PartType: AttachmentHipsFront
  PartVersion: 1
- Name: SK_FANT_KNGT_02_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_02_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_FANT_KNGT_02_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_FANT_KNGT_02_33AKNL_HU01
  PartType: AttachmentKneeLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_02_34AKNR_HU01
  PartType: AttachmentKneeRight
  PartVersion: 1
- Name: SK_FANT_KNGT_03_22AHED_HU01
  PartType: AttachmentHead
  PartVersion: 1
- Name: SK_FANT_KNGT_04_27AHPL_HU01
  PartType: AttachmentHipsLeft
  PartVersion: 1
- Name: SK_FANT_VILL_03_02HAIR_HU01
  PartType: Hair
  PartVersion: 1
- Name: SK_HUMN_BASE_01_01HEAD_HU01
  PartType: Head
  PartVersion: 1
- Name: SK_HUMN_BASE_01_03EBRL_HU01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_04EBRR_HU01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_05EYEL_HU01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_06EYER_HU01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_07EARL_HU01
  PartType: EarLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_08EARR_HU01
  PartType: EarRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_HUMN_BASE_03_36TETH_HU01
  PartType: Teeth
  PartVersion: 1
ColorSet:
  Species: 1
  Name: Default
  SourceColorPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: BF9062
- ColorProperty: 2
  MainColor: C7986A
- ColorProperty: 3
  MainColor: C7986A
- ColorProperty: 4
  MainColor: AF8057
- ColorProperty: 5
  MainColor: C7986A
- ColorProperty: 6
  MainColor: BF9062
- ColorProperty: 7
  MainColor: BF9062
- ColorProperty: 8
  MainColor: AF8057
- ColorProperty: 9
  MainColor: AF8057
- ColorProperty: 10
  MainColor: AF8057
- ColorProperty: 11
  MainColor: AF8057
- ColorProperty: 12
  MainColor: AF8057
- ColorProperty: 13
  MainColor: AF8057
- ColorProperty: 14
  MainColor: BF9062
- ColorProperty: 15
  MainColor: E79A9C
- ColorProperty: 16
  MainColor: FFF3CE
- ColorProperty: 17
  MainColor: E5D8AF
- ColorProperty: 18
  MainColor: E79A9C
- ColorProperty: 19
  MainColor: E79A9C
- ColorProperty: 20
  MainColor: D0D0D0
- ColorProperty: 21
  MainColor: D0D0D0
- ColorProperty: 22
  MainColor: 32281D
- ColorProperty: 23
  MainColor: 32281D
- ColorProperty: 24
  MainColor: 262626
- ColorProperty: 25
  MainColor: 262626
- ColorProperty: 26
  MainColor: 503E2B
- ColorProperty: 27
  MainColor: 503E2B
- ColorProperty: 28
  MainColor: FFFFFF
- ColorProperty: 29
  MainColor: FFFFFF
- ColorProperty: 30
  MainColor: 26272D
- ColorProperty: 31
  MainColor: 26272D
- ColorProperty: 32
  MainColor: 26272D
- ColorProperty: 33
  MainColor: 26272D
- ColorProperty: 34
  MainColor: CAA58E
- ColorProperty: 35
  MainColor: 26272D
- ColorProperty: 36
  MainColor: 26272D
- ColorProperty: 37
  MainColor: CAA58E
- ColorProperty: 38
  MainColor: B35149
- ColorProperty: 39
  MainColor: 944842
- ColorProperty: 40
  MainColor: AFA382
- ColorProperty: 41
  MainColor: 94896F
- ColorProperty: 42
  MainColor: 414C57
- ColorProperty: 43
  MainColor: 566470
- ColorProperty: 44
  MainColor: 382F2A
- ColorProperty: 45
  MainColor: 3F4850
- ColorProperty: 46
  MainColor: 363433
- ColorProperty: 47
  MainColor: 3F3737
- ColorProperty: 48
  MainColor: 625140
- ColorProperty: 49
  MainColor: 382F2A
- ColorProperty: 50
  MainColor: 3F4850
- ColorProperty: 51
  MainColor: 363433
- ColorProperty: 52
  MainColor: 3F3737
- ColorProperty: 53
  MainColor: 625140
- ColorProperty: 54
  MainColor: 382F2A
- ColorProperty: 55
  MainColor: 3F4850
- ColorProperty: 56
  MainColor: 363433
- ColorProperty: 57
  MainColor: 6B513B
- ColorProperty: 58
  MainColor: 3A3D43
- ColorProperty: 59
  MainColor: 363433
- ColorProperty: 60
  MainColor: 3F4850
- ColorProperty: 61
  MainColor: 363433
- ColorProperty: 62
  MainColor: 6B513B
- ColorProperty: 63
  MainColor: 3A3D43
- ColorProperty: 64
  MainColor: 363433
- ColorProperty: 65
  MainColor: 3F4850
- ColorProperty: 66
  MainColor: 363433
- ColorProperty: 67
  MainColor: 414C57
- ColorProperty: 68
  MainColor: 330004
- ColorProperty: 69
  MainColor: 515456
- ColorProperty: 70
  MainColor: 957632
- ColorProperty: 71
  MainColor: 483D34
- ColorProperty: 72
  MainColor: 808080
- ColorProperty: 73
  MainColor: 50443A
- ColorProperty: 74
  MainColor: 363433
- ColorProperty: 75
  MainColor: 907151
- ColorProperty: 76
  MainColor: 784D49
- ColorProperty: 77
  MainColor: 3F3737
- ColorProperty: 78
  MainColor: 3F3737
- ColorProperty: 79
  MainColor: 363433
- ColorProperty: 80
  MainColor: 907151
- ColorProperty: 81
  MainColor: 784D49
- ColorProperty: 82
  MainColor: 500008
- ColorProperty: 83
  MainColor: 50443A
- ColorProperty: 84
  MainColor: 363433
- ColorProperty: 85
  MainColor: 907151
- ColorProperty: 86
  MainColor: 784D49
- ColorProperty: 87
  MainColor: 500008
- ColorProperty: 88
  MainColor: 50443A
- ColorProperty: 89
  MainColor: 363433
- ColorProperty: 90
  MainColor: 907151
- ColorProperty: 91
  MainColor: 784D49
- ColorProperty: 92
  MainColor: 625343
- ColorProperty: 93
  MainColor: 985D41
- ColorProperty: 94
  MainColor: B5B6B5
- ColorProperty: 95
  MainColor: 9AA1A5
- ColorProperty: 96
  MainColor: 848484
- ColorProperty: 97
  MainColor: 383838
- ColorProperty: 98
  MainColor: 383838
- ColorProperty: 99
  MainColor: 383838
- ColorProperty: 100
  MainColor: 383838
- ColorProperty: 101
  MainColor: 383838
- ColorProperty: 102
  MainColor: 383838
- ColorProperty: 103
  MainColor: 383838
- ColorProperty: 104
  MainColor: 383838
- ColorProperty: 105
  MainColor: 355A70
- ColorProperty: 106
  MainColor: 848484
- ColorProperty: 107
  MainColor: 383838
- ColorProperty: 108
  MainColor: 383838
- ColorProperty: 109
  MainColor: 383838
- ColorProperty: 110
  MainColor: 43708A
- ColorProperty: 111
  MainColor: 383838
- ColorProperty: 112
  MainColor: 383838
- ColorProperty: 113
  MainColor: 383838
- ColorProperty: 114
  MainColor: 383838
- ColorProperty: 115
  MainColor: 43708A
- ColorProperty: 116
  MainColor: 383838
- ColorProperty: 117
  MainColor: 383838
- ColorProperty: 118
  MainColor: 383838
- ColorProperty: 119
  MainColor: 383838
- ColorProperty: 120
  MainColor: 43708A
- ColorProperty: 121
  MainColor: 383838
- ColorProperty: 122
  MainColor: 383838
- ColorProperty: 123
  MainColor: 383838
- ColorProperty: 124
  MainColor: 383838
- ColorProperty: 125
  MainColor: 43708A
- ColorProperty: 126
  MainColor: 383838
- ColorProperty: 127
  MainColor: 383838
- ColorProperty: 128
  MainColor: 383838
- ColorProperty: 129
  MainColor: 383838
- ColorProperty: 130
  MainColor: 43708A
- ColorProperty: 131
  MainColor: 383838
- ColorProperty: 132
  MainColor: 383838
- ColorProperty: 133
  MainColor: 383838
- ColorProperty: 134
  MainColor: 383838
- ColorProperty: 135
  MainColor: 43708A
- ColorProperty: 136
  MainColor: 383838
- ColorProperty: 137
  MainColor: 383838
- ColorProperty: 138
  MainColor: 383838
- ColorProperty: 139
  MainColor: 383838
- ColorProperty: 140
  MainColor: 355A70
- ColorProperty: 141
  MainColor: 4A4540
- ColorProperty: 142
  MainColor: 90694D
- ColorProperty: 143
  MainColor: 383838
- ColorProperty: 144
  MainColor: 383838
- ColorProperty: 145
  MainColor: 5D4837
- ColorProperty: 146
  MainColor: 7D634C
- ColorProperty: 147
  MainColor: AC9B8F
- ColorProperty: 148
  MainColor: 383838
- ColorProperty: 149
  MainColor: 383838
- ColorProperty: 150
  MainColor: 5D4837
- ColorProperty: 151
  MainColor: 7D634C
- ColorProperty: 152
  MainColor: AC9B8F
- ColorProperty: 153
  MainColor: 383838
- ColorProperty: 154
  MainColor: 383838
- ColorProperty: 155
  MainColor: 4A0006
- ColorProperty: 156
  MainColor: 888888
- ColorProperty: 157
  MainColor: AC9B8F
- ColorProperty: 158
  MainColor: 383838
- ColorProperty: 159
  MainColor: 383838
- ColorProperty: 160
  MainColor: 636363
- ColorProperty: 161
  MainColor: 31030A
- ColorProperty: 162
  MainColor: 8A8A8A
- ColorProperty: 163
  MainColor: 474850
- ColorProperty: 164
  MainColor: 9B9B9B
- ColorProperty: 165
  MainColor: 745555
- ColorProperty: 166
  MainColor: D51800
- ColorProperty: 167
  MainColor: 723F83
- ColorProperty: 168
  MainColor: 6CB0C1
- ColorProperty: 169
  MainColor: 619978
- ColorProperty: 170
  MainColor: 00FFE4
- ColorProperty: 171
  MainColor: 0074FF
- ColorProperty: 172
  MainColor: 9A9FA2
- ColorProperty: 173
  MainColor: 949AA2
- ColorProperty: 174
  MainColor: 8D997D
- ColorProperty: 175
  MainColor: 838865
- ColorProperty: 176
  MainColor: 3B3936
- ColorProperty: 177
  MainColor: 2E2C29
- ColorProperty: 178
  MainColor: 8B8580
- ColorProperty: 179
  MainColor: 5F6269
- ColorProperty: 180
  MainColor: A0967F
- ColorProperty: 181
  MainColor: 897D63
- ColorProperty: 182
  MainColor: 8B7B69
- ColorProperty: 183
  MainColor: 746352
- ColorProperty: 184
  MainColor: 785F49
- ColorProperty: 185
  MainColor: 695441
- ColorProperty: 186
  MainColor: ACACAC
- ColorProperty: 187
  MainColor: 614E3D
- ColorProperty: 188
  MainColor: 9C7B4F
- ColorProperty: 189
  MainColor: 746451
- ColorProperty: 190
  MainColor: 63594B
- ColorProperty: 191
  MainColor: 7F715F
- ColorProperty: 192
  MainColor: BDB7B0
- ColorProperty: 193
  MainColor: A8A39F
- ColorProperty: 194
  MainColor: 7D6652
- ColorProperty: 195
  MainColor: 8E7661
- ColorProperty: 196
  MainColor: 954039
- ColorProperty: 197
  MainColor: 6D403D
- ColorProperty: 198
  MainColor: 7B7879
- ColorProperty: 199
  MainColor: 565656
- ColorProperty: 200
  MainColor: FFFFFF
- ColorProperty: 201
  MainColor: FFFFFF
- ColorProperty: 202
  MainColor: FFFFFF
- ColorProperty: 203
  MainColor: FFFFFF
- ColorProperty: 204
  MainColor: FFFFFF
- ColorProperty: 205
  MainColor: FFFFFF
- ColorProperty: 206
  MainColor: FFFFFF
- ColorProperty: 207
  MainColor: FFFFFF
- ColorProperty: 208
  MainColor: FFFFFF
- ColorProperty: 209
  MainColor: FFFFFF
BlendShapes:
  BodyTypeValue: -83.4000015
